### ISSUE TITLE
Add method for testing pdf content

### ISSUE THREAD

**Issue by cbxp** [codeborne/selenide#132]

**Comment by previousdeveloper** [comment]
https://github.com/previousdeveloper/selenide/commit/2d2b9bfa88e3bd3e65aa08612e32884b8d4cf462

**Comment by leslyarun** [comment]
If Selenide provides support for testing PDF docs (using Apache PDFBox or anyother), it will be very helpful

**Comment by asolntsev** [comment]
@leslyarun I am in doubt if it should be a part of Selenide. Because it's not directly connected to WebDriver and browser automation. Probably it would be better to create a separate project like "github.com/codeborbe/pdf-asserts".

Can you specify, what exactly do you need to test in PDF?
As I see, you can only test that PDF contains required text. So, the API could look like this:

```java
  File pdf = $("#cv").download();
  assertPdfContains(pdf, "John Belushi", "Birthday", "31.12.1956");
```

Is it what you want?

**Comment by leslyarun** [comment]
File pdf = $("#cv").download();
  assertPdfContains(pdf, "John Belushi", "Birthday", "31.12.1956");

ya, this is what I want.

Ya, maybe we can have a separate project for PDF Automation.

Plus, If we are able to render the exact text (like, if there is a table in pdf, it should be rendered xactly in the same way), it would be great.

One more thing is, the text we are searching will be found if it is present in the entire PDF. I want to  search the text based on specific criteria. 

(E.g.) If I want to search the word "hello" in a pdf, and if there are 10 instances where "hello" is displayed, then I don't want it to find the 1st instance and tell that the search term is found .

Instead I want to find the particular search term based on some criteria like - "hello" should be present in 3rd column of a table.

**Comment by asolntsev** [comment]
@leslyarun Ok, thank you for detailed explanation.
It's easy to assert text in the entire PDF file.
But I am not sure it's technically possible to make more specific texts like you have described. I am not sure if PDFBox or any other library allow it. I need to investigate it. 

By the way, I found a similar library (quite old): http://jpdfunit.sourceforge.net/docs/GettingStarted.html

**Comment by asolntsev** [comment]
@leslyarun I created a first version of library PDFest (like "PDF Test"): https://github.com/codeborne/pdfest

Probably you can suggest better name? Name that would sound cool? Like "PDFUnit", "PDFee", "PDFium", "PDFilla", "PDFico", "VerifyPDF", "AssertPDF", "PDFool", "...

**Comment by leslyarun** [comment]
Wow that's great . Very fast @asolntsev.
What about PDFium or PDFide ???

**Comment by asolntsev** [comment]
PDFium is unfortunately already used. PDFium is a pdf rendering engine from Google.

And PDFide sounds like "pdf IDE" (the same problem is with Selenide too).

And I think that this name should be applicable for other formats too. Probably we will also create libraries for testing xls, epub, doc files. They could be named in the same manner.

Sent from my HTC

----- Reply message -----

**Comment by leslyarun** [comment]
We will be doing only PDF docs , or xls, epub also in this? @asolntsev

**Comment by asolntsev** [comment]
Only pdf. I would create separate project "xls-test" for testing excel files. Testing epub is technically possible, but I am not sure if anybody actually needs it.

Sent from my HTC

----- Reply message -----

**Comment by leslyarun** [comment]
@asolntsev 
pdf-test is OK. Is it possible to integrate Apache Lucene in the project, so that we can search more efficiently???

**Comment by asolntsev** [comment]
@leslyarun what do you want to search during test run? Please describe the case.

**Comment by dysen** [comment]
I try to do it on my project. We have a lot of printing documents, which user is unable to see before they are printed. I found a way to print a single document on a virtual printer and then read it from the code

**Comment by leslyarun** [comment]
@asolntsev 
The text we are searching will be found if it is present in the entire PDF. I want to search the text based on specific criteria.

(E.g.) If I want to search the word "hello" in a pdf, and if there are 10 instances where "hello" is displayed, then I don't want it to find the 1st instance and tell that the search term is found .

Instead I want to find the particular search term based on some criteria like - "hello" should be present in 3rd column of a table.

Also, assert will find all the words that starts with "hello" ? 
Or will it only assert the exact text ?
(e.g. If there is a word "hellouis'', will it tell "hello" is present???)

**Comment by asolntsev** [comment]
@leslyarun How Apache Lucene would help us? As much as I understand, Apache Lucene can quickly search for a substring in huge texts. In most cases, PDFs that we test are not very big. It's typically some payment PDF form consisting of 1-2 pages. 

The question actually is: is it techically possible to extract layout information from PDF. I don't know yet. I need to investigate it. At the moment pdf-test only allows you to assert that PDF contains some substring. In most cases it's good enough. We typivcally test that PDF contains correct amount, bill date and payer name.

**Comment by leslyarun** [comment]
I have to test 250 pages, so I thought , Lucene will help to search efficiently. 

Also, assert will find all the words that starts with "hello" ? 
Or will it only assert the exact text ?
(e.g. If there is a word "hellouis'', will it tell "hello" is present???)

Assert will find the 1st instance and tell that text is present ?

**Comment by asolntsev** [comment]
Yes, right now assertThat(pdf, containsText("hello")) finds any occurrence of "hello" in pdf, including "hellouius".

Sent from my HTC

----- Reply message -----

**Comment by leslyarun** [comment]
can u give me the maven code for pdf-test ? I need to experiment

**Comment by asolntsev** [comment]
Sure.
groupIe: com.codeborne
artifactId: pdf-test
version: 1.1

Actually you can find this info from mavens repo:

http://search.maven.org/#search%7Cga%7C1%7CCodeborne

Sent from my HTC

----- Reply message -----

**Comment by asolntsev** [comment]
@leslyarun 
You said: "I have to test 250 pages, so I thought , Lucene will help to search efficiently."
Lucene will not make your tests faster. Typical usage of Lucene is as follows:

1. Index all large texts on startup (one time)   - it's **long** operation
2. Serve multiple search requests many times  - it's fast operation

In tests, you need to perform both 1. and 2. steps. You still need to waste time to Index your pdf during test run.

**Comment by leslyarun** [comment]
Fine.
Then we don't need lucene

Regards,
Lesly Arun Franco

**Comment by leslyarun** [comment]
@asolntsev 

when will this become possible ???? :

File pdf = $("#cv").download();
  assertPdfContains(pdf, "John Belushi", "Birthday", "31.12.1956");

**Comment by asolntsev** [comment]
@leslyarun It has been possible for a while.
Just add dependency [pdf-test](https://github.com/codeborne/pdf-test) to your project:

```xml
  <dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>pdf-test</artifactId>
    <version>1.2</version>
    <scope>test</scope>
  </dependency>
```

and use it:

```java
PDF pdf = new PDF($("#cv").download());
assertThat(pdf, containsText("John Belushi"));
assertThat(pdf, containsText("Birthday"));
assertThat(pdf, containsText("31.12.1956"));
```

**Comment by leslyarun** [comment]
@asolntsev  Thanks a lot :)

**Comment by leslyarun** [comment]
@asolntsev  there is no assertThat method in testng. 
I can only directly use this :
```import static org.hamcrest.MatcherAssert.assertThat;```

But if I use pdf-test and xls-test in the same class, then it will show error for the second asserthat of xls-test:

```PDF pdf =new PDF( $(By.cssSelector("#pers-new-left > div.grid_6.content > p:nth-child(16) > em > a:nth-child(1)")).download());		
assertThat(pdf, containsText("checks"));```

```XLS spreadsheet = new XLS (getClass().getClassLoader().getResource("statement.xls"));
assertThat(spreadsheet, containsText("Statement"));```

any support for testng???

**Comment by asolntsev** [comment]
There is no special support needed for TestNG. Both pdf-test and xls-test can be used with TestNG, exactly as you described.

The problem is, that they cannot be used together. More exactly, they can be used in the same test, but you need to use full-qualified class name. Like this:

assertThat(pdf, com.codeborne.pdftest.PDFMatchers.containsText());

It's not nice. I will think how to solve this problem. But probably it's not a good idea to test both pdf and xls in the same test? They are different things. 

Sent from my HTC

----- Reply message -----

**Comment by leslyarun** [comment]
@asolntsev  In my application, pdf file opens in a new window.
How can I test PDF in this scenario? 
I don't want to manually download the PDF and test it using pdf-test.
download() works only in href.
Any Workarounds ?

**Comment by asolntsev** [comment]
You can catch the file using proxy server. It's quite easy. Just search how to use "mob browser proxy" with Selenium.

I will try to make it even simpler in future versions of Selenide.

Sent from my HTC

----- Reply message -----
