### ISSUE TITLE
Selenide could automatically download chromedriver

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#133]
1. Check if chrome driver is not installed yet
2. Check the latest version of chromedriver from here: 
   http://chromedriver.storage.googleapis.com/LATEST_RELEASE
3. Download binary and install to /home/USER/.selenide/chromedriver

**Comment by ozzimpact** [comment]
Hi. I managed to work it out. It works both Mac or Windows.You can check it out [here](https://github.com/ozzimpact/ChromeDriverChecker.git). 
We can put this into Selenide boot, it checks whenever starts or we can create maven or gradle dependency. How do you want it to be?

**Comment by asolntsev** [comment]
Cool! Thank you!
I thought about including this functionality in Selenide. Simpler is better.

**Comment by BorisOsipov** [comment]
Done https://github.com/codeborne/selenide/pull/610
