### ISSUE TITLE
NoClassDefFoundError: com/google/common/base/MoreObjects

### ISSUE THREAD

**Issue by dmak** [codeborne/selenide#160]
I think the triggering of this issue depends on the environment (e.g. classpath of particular project), but in my case I get this exception in Selenide v2.16:

    java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenShot(ScreenShotLaboratory.java:81)
    	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenShot(ScreenShotLaboratory.java:58)

The given class `ScreenShotLaboratory` imports `com.google.common.base.MoreObjects`, but `com.google.guava:guava:jar` is not listed as compile-time dependency in Selenide POM. It might happen that this dependency is propagated through Selenium, but depending on that is not good idea, as this dependency may disappear in a while (or version may change).

**Comment by asolntsev** [comment]
It is a guava - dependency of selenium webdriver. Selenium uses guava anyway.

I believe you just have an old guava version in classpath. 

Sent from my HTC

----- Reply message -----

**Comment by asolntsev** [comment]
Try using guava 18.0 or later:
```xml
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>18.0</version>
</dependency>
```

**Comment by dmak** [comment]
First of all, I took the [POM file from maven](https://repo1.maven.org/maven2/com/codeborne/selenide/2.16/selenide-2.16.pom) and placed it into Selenide source tree. Do you agree that project should compile? However it does not:

    selenide\src\main\java\com\codeborne\selenide\impl\WebDriverThreadLocalContainer.java:[8,35] error: package org.openqa.selenium.htmlunit does not exist
    selenide\src\main\java\com\codeborne\selenide\junit\BrowserStrategy.java:[3,22] error: package org.junit.rules does not exist
    selenide\src\main\java\com\codeborne\selenide\junit\ScreenShooter.java:[7,23] error: package org.junit.runner does not exist
    selenide\src\main\java\com\codeborne\selenide\testng\BrowserPerTest.java:[3,17] error: package org.testng does not exist
    selenide\src\main\java\com\codeborne\selenide\testng\BrowserPerTest.java:[4,27] error: package org.testng.reporters does not exist

In `build.gradle` you have marked `junit:junit:4.12` and `org.testng:testng:6.8.17` as `provided`, but they are not put to POM with `<scope>provided</scope>`. Is it possible to configure Gradle so that is pushes provided dependencies to POM? 

Now back to Guava. Here is the output of `mvn dependency:tree`:

    com.codeborne:selenide:jar:2.16
    +- org.mockito:mockito-all:jar:1.10.19:test
    +- org.seleniumhq.selenium:selenium-java:jar:2.44.0:compile
    |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.44.0:compile
    |  |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:2.44.0:compile
    |  |     +- cglib:cglib-nodep:jar:2.1_3:compile
    |  |     +- com.google.code.gson:gson:jar:2.3:compile
    |  |     +- org.seleniumhq.selenium:selenium-api:jar:2.37.1:compile
    |  |     +- org.apache.httpcomponents:httpclient:jar:4.2.3:compile
    |  |     |  +- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
    |  |     |  +- commons-logging:commons-logging:jar:1.0.4:compile
    |  |     |  \- commons-codec:commons-codec:jar:1.2:compile
    |  |     \- com.google.guava:guava:jar:r07:compile

This odd version r07 will be used, I don't see any chances for v18 to come to classpath. Here is the output of `mvn install`:

    selenide\src\main\java\com\codeborne\selenide\impl\ScreenShotLaboratory.java:[21,36] error: cannot find symbol

which is absolutely fair from my point of view. There is no configuration that forces to use Guava v18.

**Comment by asolntsev** [comment]
Hm... It seems that selenium-remote-driver does not declare a concrete
version of guava. Look at its pom:

<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
</dependency>

But selenium-parent does declare:

<dependencyManagement>
<dependencies>
<dependency>
<groupId>cglib</groupId>
<artifactId>cglib-nodep</artifactId>
<version>2.1_3</version>
</dependency>
<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>18.0</version>
</dependency>


So, I believe guava 18.0 should be used unless it's a bug in maven
dependency resolver.

You can just declare guava 18.0 dependency in your project, it definitely
resolves the problem.

Andrei Solntsev

2015-02-04 12:57 GMT+02:00 Dmitry Katsubo <notifications@github.com>:

**Comment by dmak** [comment]
You're right. But I also have rationale. It took me a while to realize that dependency resolution depends not on Maven itself, but rather on `maven-dependency-plugin` version. Indeed, Selenuim uses v18.0, and r07 was crappy resolution. However there is another dependency tree:

    com.codeborne:selenide:jar:2.16
    +- com.opera:operadriver:jar:1.5:test
    |  +- com.opera:operalaunchers:jar:1.1:test
    |  +- com.google.protobuf:protobuf-java:jar:2.4.1:test
    |  +- com.google.guava:guava:jar:14.0:compile
    |  +- commons-jxpath:commons-jxpath:jar:1.3:test
    |  +- org.apache.commons:commons-exec:jar:1.1:compile
    |  \- org.ini4j:ini4j:jar:0.5.2:test

Of course that is weird how maven decided to downgrade the version from 18.0 to 14.0 – perhaps that makes sense. We see that there is a collision of `test` scope with `compile` scope and basically it is impossible to say what version to use in `test` scope.

What I want to underline here: if Selenide depends on particular version of Guava, it should better explicitly declare it. Excluding transitive dependency coming from `com.opera:operadriver` is also an option but nobody knows where Guava will again pop up.

**Comment by asolntsev** [comment]
You are right.
I will add explicit dependency on guava 18+. And probably remove opera dependency - opera does not work anyway 

Sent from my HTC

----- Reply message -----
