### ISSUE TITLE
Remove cookies from all domains

### ISSUE THREAD

**Issue by dengayevskiy** [codeborne/selenide#163]
HI! It would be usefull to add method that removes cookies from all domains and not just current as Selenium's `.deleteAllCookies()` do.

**Comment by asolntsev** [comment]
Well, how to do that?

**Comment by dengayevskiy** [comment]
Here's an example in python, but same idea in java:

```
wd = self.webdriver
cookies = wd.get_cookies()
    for cookie in cookies:
       if cookie["domain"] == [domains i've worked]:
              wd.delete_cookie(cookie["name"])
```
Saw this text in Selenide sources: *If browser window was already opened before, it will be reused*. Does this mean that once opened current browser session will be reused for every @Test in my class?

**Comment by dengayevskiy** [comment]
Sorry, I thought Selenide was reopening browser every new test but it was not. Resolved my issue by adding this code to test class:
```
@AfterClass
    public static void endSession() {
        closeWebDriver();
    } 
```

**Comment by asolntsev** [comment]
So, can we close the issue?

**Comment by asolntsev** [comment]
Closing the issue
