### ISSUE TITLE
Method download() throws javax.net.ssl.SSLHandshakeException in case of ssl connection.

### ISSUE THREAD

**Issue by LizaLeo** [codeborne/selenide#164]
java.lang.reflect.UndeclaredThrowableException
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by shimkiv** [comment]
Seems that it is not a Selenide's problem but an cert/env issue.
You can try:
1. to manually add cert into java keystore;
2. to set "jsse.enableSNIExtension" to "false";
3. http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html

**Comment by LizaLeo** [comment]
As long as FF driver by default ignores SSL certificates (web pages loaded fine from the same domain) - seems logical that download() has to work in the same way.
You way of course can be used as workaround, but unfortunately my certificate have wrong CN - so I got the error "Hostname in certificate didn't match" - so unfortunately I can't use it in this project.

**Comment by asolntsev** [comment]
I agree, method $.download() should behave exactly as webdriver. If
webdriver ignores invalid SSL certificates, $.download should also ignore.

Andrei Solntsev

2015-02-20 11:45 GMT+02:00 LizaLeo <notifications@github.com>:

**Comment by asolntsev** [comment]
@LizaLeo Can you provide an example if public site with invalid SSL cert? Ideally with file download link.

**Comment by LizaLeo** [comment]
@asolntsev Unfortunately I can't provide any <b>public</b> site with invalid certificate. I tried to untrust some already trusted certificates like described here http://stackoverflow.com/questions/26630691/example-websites-that-have-invalid-certificates, but  it didn't work for me. 
But seems, that it wouldn't be big problem for developer to create small web application with your own certificate and with download link on it's web page?

**Comment by asolntsev** [comment]
Fixed in Selenide 2.19 (will be released in June 2015)
