### ISSUE TITLE
When fastSetValue=true, the value set to textarea does not trigger "input" event

### ISSUE THREAD

**Issue by dmak** [codeborne/selenide#165]
When running Selenide v2.16 with `-Dselenide.fastSetValue=true`, the value set to `<textarea>` does not trigger `input` event. Web page contains JQuery.

JavaScript code of the page:
```js
$('#panel textarea').on('input', changeListener); // this listener is never triggered
```
Java code:
```java
$("#panel textarea").val("Some value"); // value is visible, but event is not triggered
```
Looking at `AbstractSelenideElement#setValue()` I see that if jQuery is present, events are triggered explicitly. How then the case when no jQuery is present works (lines 364-365) as it does not trigger any events except `onchange`?

**Comment by asolntsev** [comment]
If your application depends on javascript events (like `keyup`, `keydown`, `keypress`, `input` etc), it's recommended to use method `$.sendKeys()` instead of `$.val()`. Otherwise it's hard to guarantee that all the required events are triggered exactly as in real browser. 

It seems that the mentioned code in `AbstractSelenideElement#setValue() ` for triggering events doesn't work pretty well. I thought about removing this code in the next Selenide version.

**Comment by dmak** [comment]
Thanks for reply. I wonder, why browser does not fire events itself when `arguments[0].value = arguments[1];` JavaScript snippet is executed?

**Comment by asolntsev** [comment]
I don't know. Probably it's the goal of JavaScript - to modify contents silently, like it was not a human client.

**Comment by asolntsev** [comment]
So, no actions required? Closing the issue...

**Comment by dmak** [comment]
Perhaps no actions are required. I see that the code calls `fireChangeEvent(element)` but you say that `sendKeys()` should fire the appropriate events (lines [416-417](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/impl/AbstractSelenideElement.java#L417)). Why is that needed?

**Comment by asolntsev** [comment]
Few years ago `fireChangeEvent` was needed because change even was not always properly triggered in IE browser. In other browsers it's not needed. Probably it's not needed for IE too - i didn't check IE for a long time. Probably `fireChangeEvent` should be removed.

**Comment by asolntsev** [comment]
@dmak By the way, I have added triggering `input` event to the `$.setValue()` method in Selenide 2.18 (will be released tonight).
