### ISSUE TITLE
selectOption() doesn't set value

### ISSUE THREAD

**Issue by IZaiarnyi** [codeborne/selenide#167]
Infromation: Selenide 2.17, Chrome Version 38.0.2125.122, Firefox 33.0, Ubuntu 12.10 i386

Precondition: We have two related dropdowns (when we choose some value from the first dropdown, values from the second dropdown updated)

Dropdowns before: 
`<select class="2h" title="All">`
	`<option selected="" value="0" title="All">All</option>`
	`<option value="1" title="firstValue">firstValue</option>`
	`<option value="2" title="otherValue">otherValue</option>`
`</select>`

`<select class="2h" title="All">`
	`<option selected="" value="0" title="All">All</option>`
`</select>`

Dropdowns After  firstValue selection:
`<select class="2h" title="firstValue">`
	`<option selected="" value="0" title="All">All</option>`
	`<option value="1" title="firstValue">firstValue</option>`
	`<option value="2" title="otherValue">otherValue</option>`
`</select>`

`<select class="2h" title="All">`
	`<option selected="" value="0" title="All">All</option>`
	`<option value="1" title="secondValue">secondValue</option>`
`</select>`

STR: 
1.  $(By.xpath("//label[text()='firstDropdown']/../..//select")).selectOption(firstValue)
2.  $(By.xpath("//label[text()='secondDropdown']/../..//select")).selectOption(secondValue)

Actual result: 
Element not found {StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up}
Expected: visible

Expected result:
secondValue is selected in the secondDropdown

Seems like selectOption() doesn't wait until secondDropdown would be refreshed.

**Comment by asolntsev** [comment]
Thank for reporting! I will investigate this.

**Comment by asolntsev** [comment]
Hi!
I tried to experiment with dynamic selects, but I could not reproduce your issue.
Can you provide some github project or ZIP file that would let me reproduce the issue?

**Comment by IZaiarnyi** [comment]
I'm not allowed to provide zip file due security rules and I didn't have success to find this behaviour on other sites or projects. 
I try to describe with more details maybe it'll help:
- Configuration.timeout = 20000; 
- I have bug, only when I have a lot of data in my second dropdown (so for getting information in my second dropdown I run post request and get response from server in ~5 s)

AdditionaL information: As I see, Selenide try to set value in dropdown before response of server, and after failure it waits until Configuration.timeout is ended, but don't try again to set value after response.

**Comment by IZaiarnyi** [comment]
Fixed and verified in 2.18.
