### ISSUE TITLE
waituntil function makes IE to flicker in Selenide 2.18

### ISSUE THREAD

**Issue by leslyarun** [codeborne/selenide#180]
I was previously using selenide 2.17 and didnt face any issue. I upgraded to selenide 2.18 and ran the same code and found that whenever waituntil is encountered , IE 11 starts flickering. Request you to fix this issue.

Sample Code : 

$(By.className("preloaderWrapper")).waitUntil(disappears,20000);

Browser is flickering till the wait gets over.

Browser - IE 11
Selenide - 2.18

**Comment by leslyarun** [comment]
I guess it's taking a screenshot for every second it waits (I don't really know what is happening in the code).

I ran a few test cases and found all testcases are passed, but still selenide took 65 screenshots for no reason (I have set to take screenshots only on failure). 

I don't want selenide to take screenshots unneccessarily and I don't want the browser to flicker during the wait time

**Comment by asolntsev** [comment]
Thank you for reporting, I will investigate the problem.

Sent from my HTC

----- Reply message -----

**Comment by asolntsev** [comment]
@leslyarun wow. You are right. Selenide 2.18 does take a lot of screenshots while waiting. :)
Will fix it asap.

**Comment by asolntsev** [comment]
Released selenide 2.18.1 with a fix.

Sent from my HTC

----- Reply message -----

**Comment by leslyarun** [comment]
@asolntsev Thank u
