### ISSUE TITLE
Too many screenshot made in 2.18

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#183]
I am experiencing a lot of screenshots, in the tests that are passed. Probably each time, when the element is not shown immediately (implicit 4s timeout), maybe in waitUntil as well.

It's probably not the desired behavior. :-)

**Comment by asolntsev** [comment]
It's a know issue (https://github.com/codeborne/selenide/issues/180), fixed in Selenide 2.18.2

**Comment by vinogradoff** [comment]
Thanx, it wasn't obvious that a patch is already there :)

**Comment by asolntsev** [comment]
I can fix bugs even before it's reported! :)
