### ISSUE TITLE
Getting error after every run in Selenide 2.19

### ISSUE THREAD

**Issue by leslyarun** [codeborne/selenide#187]
After updgrading to Selenium 2.46.0 and Selenide 2.19 , I'm getting a error message displayed after every run:

org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder
INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@318c29

Note: I'm using IE11

i think it's a Selenium issue, but still any help is appreciated

**Comment by asolntsev** [comment]
Yes, this log comes from Selenium webdriver.
But actually it's not a problem. Look, this is just an INFO message.

Andrei Solntsev

2015-06-24 13:59 GMT+03:00 leslyarun <notifications@github.com>:
