### ISSUE TITLE
[Information] How to get reports by using selenide?

### ISSUE THREAD

**Issue by anilreddy** [codeborne/selenide#189]
Hi,

I know this is only for issues. But I want to know is there any built-in reporting in selenide? If so, could you please provide me an example of the same would be very useful.

Thanks,
Anil

**Comment by asolntsev** [comment]
No, Selenide does not generate reports.
But good news is that you don't actually need any special reporting.

Any tool you are using to run tests can create reports. Let it be Ant,
Maven, Gradle, JUnit, TestNG, Jenkins - they can create test reports.
Additionally, Selenide prints out links to screenshots in error messages.
This is particularly useful when debugging flaky tests.

For advanced reporting, you can use Selenide with Allure (here
<https://github.com/selenide-examples/selenide-allure-junit> is an example
project). But I personally believe that it's not actually needed.

Andrei Solntsev

2015-06-25 11:32 GMT+03:00 Anil Kumar Reddy Gaddam <notifications@github.com
