### ISSUE TITLE
File downloading mechanism for different browsers

### ISSUE THREAD

**Issue by dimand58** [codeborne/selenide#192]
How about to add logic for file downloading in different browsers? 
(not for downloading via href of course)

Example:
- user click on some button
- file generation starts on server side and user wait
- after file generation user see pop-up system window with buttons Save, Save as... , Cancel, as example
- file is downloaded to predefined temporary folder
- checking of ending of downloading performed (file is exist in predefined folder and available for modification)

I can provide code for IE8, IE11 browsers under Windows 7 (ru/eng) (based on java.awt.Robot, working with clipboard and com.sun.jna.* for windows detection by title)

CONS:
- a lot of work for other browsers/windows versions
- for non-russian/english OS Windows adding of windows titles are necessary

**Comment by asolntsev** [comment]
This mechanism seems to be unreliable. I would prefer to use server-side mechanism that would work independently of browser. I would try catching file content using proxy server (for example MobBrowserProxy or something similar).

**Comment by dimand58** [comment]
Sound like true, OK

**Comment by asolntsev** [comment]
I have added another issue for download function: https://github.com/codeborne/selenide/issues/196
