### ISSUE TITLE
It would be great to have AndroidDriver and IOSDriver in Selenide

### ISSUE THREAD

**Issue by IZaiarnyi** [codeborne/selenide#193]

**Comment by asolntsev** [comment]
We must implement it!

Look for more comments at selenide.org:
http://selenide.org/documentation.html#comment-2126758749

**Comment by asolntsev** [comment]
@IZaiarnyi We have to implement a dedicated support for Appium webdrivers.

But you can use Appium with Selenide right now. 

You can create such class:

```java
public class CreateIOSDriver implements WebDriverProvider {
public WebDriver createDriver(DesiredCapabilities capabilities) {
  URL appiumUrl = null;
  try {
    appiumUrl = new URL("http://127.0.0.1:4723/wd/hub");
  } catch (MalformedURLException e) {
    fail(e);
  }
  return new IOSDriver(appiumUrl, capabilities);
  }
}
```

And use it: 

```java
setWebDriver((WebDriver) new CreateIOSDriver(capabilities));
Configuration.timeout = 35000;
```

See these examples: https://github.com/selenide-examples/selenide-appium

**Comment by asolntsev** [comment]
@IZaiarnyi
Actually we created a special project for Appium support in Selenide: https://github.com/codeborne/selenide-appium
