### ISSUE TITLE
replace System.out and System.err to slf4 logger

### ISSUE THREAD

**Issue by admizh** [codeborne/selenide#195]
For convenient logging we need to use sl4j instead System.out/System.err
System.err
![serr](https://cloud.githubusercontent.com/assets/6014483/8632903/6938355a-27c0-11e5-8bb1-49d763efe58d.jpg)
System.out
![sout](https://cloud.githubusercontent.com/assets/6014483/8632904/6938c1a0-27c0-11e5-9ae4-1c817fe18dd9.jpg)

**Comment by asolntsev** [comment]
Good idea! Let's do it.

**Comment by asolntsev** [comment]
@admizh Why slf4j? I see that Selenium uses java.util.logging.Logger - probably it's good idea to use it in Selenide too?

**Comment by admizh** [comment]
@asolntsev you're right, using similar mechanism (like Selenium) for logging is good. Hopefully Java Util Log will be improved in future (Java 9..10)
http://stackoverflow.com/questions/11359187/why-not-use-java-util-logging

**Comment by asolntsev** [comment]
Uhh, java.util.logging is unbelievably inconvenient! 
I have migrated System.out to java.util.logging, but logging is now just worther. :(

Every Selenide user needs to configure jul properly in order to get more or less readable logs. :(
