### ISSUE TITLE
Close/quit webDriver in future thread

### ISSUE THREAD

**Issue by admizh** [codeborne/selenide#199]
Hi Andrey,
Sometimes i have problems with calling driver.close () or driver.quit () method, and test always is suspended too long timeout. I think we should close the driver in hockable thread (in com.codeborne.selenide.impl.WebDriverThreadLocalContainer#closeWebDriver(java.lang.Thread))

```java
private synchronized static void closeWithTimer(WebDriver driver) {
        THREAD_DRIVER_STATE_STORAGE.markDriverIsClose();
        Future<?> future = Executors.newSingleThreadExecutor().submit((Runnable) driver::close);
        try {
            future.get(100, SECONDS);
        } catch (InterruptedException | java.util.concurrent.TimeoutException e) {
            throw new SkipException("Long wait for killing browser", e);
        } catch (ExecutionException e) {
            throw new SkipException("Error on browser kill " + e.getMessage(), e);
        }
    }
```

**Comment by asolntsev** [comment]
Nice! Let's do it.
Actually we also experience problems with closing webdrivers, so it will help us too.

**Comment by asolntsev** [comment]
Done in Selenide 2.20
Timeout is 5 seconds by default. Can be configured via system property `selenide.closeBrowserTimeout` (default value is 5000).
