### ISSUE TITLE
Implement WebDriverRunner through interface.

### ISSUE THREAD

**Issue by admizh** [codeborne/selenide#202]
Hi Andrey, is possible implement all methods from WebDriverRunner.class through Interface?
It should be provide ability to set custom interface for manipulation with driver...

**Comment by asolntsev** [comment]
@admizh It's already possible. You can override all methods of WebDriverRunner without having interface. 

By the way, isn't your implementation useful enough to include it to standard WebDriverRunner?

**Comment by admizh** [comment]
@asolntsev Yes, we should simple override WebDriverThreadLocalContainer.class
```java 
public class WebDriverRunner {
  public static WebDriverThreadLocalContainer webdriverContainer = new WebDriverThreadLocalContainer();
```
And set my WebDriverThreadLocalContainer implementation. But i talk about method for detection browser.
```java
 /**
   * Is Selenide configured to use Chrome browser
*/
  public static boolean isChrome() {
    return CHROME.equalsIgnoreCase(browser);
  }
```
For example we use (firefo,chrome,ie) browsers during one test-session (in paralel thread) and we should set Configuration.browser = blblabla for each created driver and we get not thread safe configuration -  because isChrome() method will be return last saved value
Interface should resolve this problem.

**Comment by asolntsev** [comment]
@admizh Yes, right now it's not possible to have different `isChrome()` implementation for different threads.

But there is easier way. You can create your own `WebDriverProvider`. Just set `selenide.browser` property to `com.my.MyWebDriverProvider`. This class can create any instance of webdriver depending on thread.

P.S. Do you have a lot of tests? If yes, I recommend to parallelize tests in different way. I recommend creating different jobs in Jenkins:
* tests-firefox
* tests-chrome
* tests-ie
* ie

Then you can run these jobs either in parallel or sequentially. I think this way it's easier to manage parallel runs.
