### ISSUE TITLE
DragAndDrop File from Classpath?

### ISSUE THREAD

**Issue by zolrath** [codeborne/selenide#203]
Currently there's a well defined method of dragging one element to another and another method of uploading a file to an input, but I'd like to be able to simulate dragging a file from my computer onto an element of the page to test drag and drop file uploading.

While doing some Selenium research on the topic it seemed to indicate that you would send keys the file to the element you'd 'drop' the image onto but as the only visible area with drop events on it is a div this doesn't work with uploadFromClasspath.

**Comment by asolntsev** [comment]
Hi @zolrath ! 
Can you provide a publicly available application (like twitter) that uses such a function? It would allow me easier testing.

**Comment by zolrath** [comment]
Twitter actually uses it for adding a header image to a profile. Gmail also
allows dragging and dropping a file into an email.



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.0.35&pv=5.1.1] On Sun, Jul 26, 2015 at 2:30 PM, Andrei Solntsev < notifications@github.com [notifications@github.com] > wrote:
Hi @zolrath [https://github.com/zolrath] !
Can you provide a publicly available application (like twitter) that uses such a
function? It would allow me easier testing.

—
Reply to this email directly or view it on GitHub
[https://github.com/codeborne/selenide/issues/203#issuecomment-125042077] .[https://github.com/notifications/beacon/AAbvo9xrNoDhZ7P4A_6PO4F1fgCVM60tks5ohUjcgaJpZM4FgAOH.gif]

**Comment by asolntsev** [comment]
I could upload image to twitter just by using `sendKeys`:

```java
    $(".tweet-form .tweet-content .rich-editor").click();
    $(".tweet-form .toolbar .image-selector").find(By.name("media_empty")).sendKeys("/Users/andrei/Pictures/web.jpg");
```

Isn't it good enough? I believe Drag&Drop technically does the same thing.

**Comment by zolrath** [comment]
For the example case I'm looking at the drag and drop functionality provided to the Header div when in Edit Profile mode when at your twitter profile.
If you click Edit Profile the Header should gain an overlay saying 'Change your header photo'. This can have an image dropped onto it which feeds the image into a hidden input field.

I can manually get at the input field by running JS on the page to make the input field visible but I can't see how to test that actual interaction.

**Comment by asolntsev** [comment]
Look at this code snippet: https://github.com/selenide-examples/twitter/blob/master/test/org/selenide/examples/twitter/UploadImageToPostTest.java

Works for me.

**Comment by zolrath** [comment]
That tests drag and dropping into the tweet field, but the interaction I was interested in is:

Login to your account.
Go to https://twitter.com/asolntsev
Click Edit Profile
Drag and Drop an image into the Change your header photo div.

I can expose the hidden input with something like:
```
executeJavaScript("$('.dropdown-menu').css('display','block')");
$("#header-choose-existing input.file-input").uploadFromClasspath("headerTest.jpg");
```

but that doesn't really test the drag and drop interaction with the header element.

**Comment by asolntsev** [comment]
@zolrath Ok, clear. I am not sure that Selenium allows such operation (drag-and-drop) file from local filesystem to browser. I guess Selenium just doesn't have access to the file system.

After googling for a while, I found solution that uses JavaScript to emulate DnD events with jQuery. But it takes the same effect as "sendKeys" in the end. I am not sure if it's worth it.

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
