### ISSUE TITLE
Create alternative screenshots implementation with awt.Robot

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#208]
Sometimes it's better to take screenshots with `awt.Robot` instead of built-in Selenium screenshots.
1. `awt.Robot`'s screenshot includes system aspects, browser's native menus etc.
2. Sometimes Selenium fails to take screenshots, for example if there is unexpected alert.

**Comment by dimand58** [comment]
@asolntsev few days ago I found stable/repeatable issue with OOM exception in Robot framework during screenshot making. But I have no time to investigate of this =(

**Comment by asolntsev** [comment]
Closing the feature request. It seems that nobody is interested.
