### ISSUE TITLE
shouldBe(text(xxx)) failed, despite of xxx was present 

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#211]
Strangely this test fails, while the text is present in System output:

	 open("http://www.datev.de");
	 SelenideElement menu=$("#nav1 > li:nth-child(7) > a ");
	 System.out.println(menu.innerHtml());
	 menu.shouldHave(text("MyDATEV"));

System.out:
      ` <span class="nurscreenreader">MyDATEV</span><img alt="" src="/nav1images/dpi/307.png">`

Error:
`Element should have text 'MyDATEV' {#nav1 > li:nth-child(7) > a }
Element: '<a href="http://www.datev.de/portal/ShowPage.do?pid=dpi&nid=307" target="_top"></a>'`

selenide 2.2.21, selenium 2.1.47,1
P.S. Strangely enough, the test passes, if I use open(saved_html), with html file, that was saved for the error in build/tests directory.

**Comment by vinogradoff** [comment]
Got it. The class "nurscreenreader" puts the text off-screen (position: -1500,-1500), so that only the image is showing. Then, if just html is saved and tested - CSS is not shown, so that the span is on-screen.
No bug.

**Comment by asolntsev** [comment]
Wow, it's non-trivial!
Bravo, @vinogradoff !
