### ISSUE TITLE
Method `switchTo(frame())` should wait until frame appears

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#212]
Travis <travis.fricke@gmail.com>, 7.08.2015:

I'm running into the same problem in some situations.  For example, when switching frames, I first tried this:

```java
try {
   switchTo().frame($(By.xpath("//frame[@name='theFrame']")));
}
catch (NoSuchFrameException ex) {
   System.out.println("Frame doesn't exist.  Continuing anyways.");
}
```

This is at a point in the test where theFrame might not exist on the page yet.  The test is checking to see if the element exists, but first it has to switch to the right frame.  When the frame doesn't exist, an error like the one from santoshsarma jayanthi is displayed, and java exits completely.  It never reaches the catch block.

However, if instead I use this:

```java
try {
   switchTo().frame("theFrame");
}
catch (NoSuchFrameException ex) {
   System.out.println("Frame doesn't exist.  Continuing anyways.");
}
```

the NoSuchFrameException is caught, and program execution continues.

**Comment by phystem** [comment]
There is an `ExpectedCondition` available in Selenium called [frameToBeAvailableAndSwitchToIt](https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html#frameToBeAvailableAndSwitchToIt-org.openqa.selenium.By-). Either you can use this or Selenide has to come up with a method `waitAndSwitchTo()` or something

**Comment by asolntsev** [comment]
@phystem Thank you for the suggestion, I will try this way.

**Comment by dimand58** [comment]
@asolntsev @phystem See PR https://github.com/codeborne/selenide/pull/265

**Comment by dimand58** [comment]
@asolntsev I guess this issue can be closed

**Comment by asolntsev** [comment]
@dimand58 Yes, we close the issue. Thank you very much!

P.S. I have also added tests that verify that Selenide actually waits until alert/confirm/frame appears.
See my commit: https://github.com/codeborne/selenide/commit/f39666b9cbae93e2c937142aee19e635c09f5d1c
