### ISSUE TITLE
Method WebDriverRunner.isFirefox() (and same) is not work correct when you implement WebDriverProvider

### ISSUE THREAD

**Issue by apanashchenko** [codeborne/selenide#213]
Hi, 
We have an interesting situation. We create `FirefoxBambooDriver` with specific setting and implement `WebDriverProvider` for use this driver.
Run our tests with property :

``` java
-Dbrowser=webdrivers.FirefoxBambooDriver
```

In case we need check is this Firefox or Chrome browser and do corresponding actions. Call `WebDriverRunner.isFirefox()`, but this method return  false. 

Maybe it because selenide check value from property:

``` java
FIREFOX.equalsIgnoreCase(System.getProperty("selenide.browser", System.getProperty("browser", FIREFOX)););
```

If I'm right, I think selenide should check instance of current WebDriver:

``` java
 public static boolean isFirefox() {
    return webdriverContainer.getWebDriver() instanceof FirefoxDriver;
  }
```

**Comment by asolntsev** [comment]
@apanashchenko Why do you need method `isFirefox()`? Initially it was created inside Selenide to use in its own purposes: to create a webdriver instance. That's why it cannot use webdriver instance :)

**Comment by apanashchenko** [comment]
@asolntsev I need `isFirefox()` for run FF on our CI with specific settings. I think this is non good if you don't know which browser run, if you us WebDriverProvider.

**Comment by asolntsev** [comment]
@apanashchenko I still don't understand why you need to use method `isFirefox()`. Control is in your hands. When use set property `-Dbrowser=webdrivers.FirefoxBambooDriver`, you already know that you are going to use Firefox. You don't need method `isFirefox()` to know it.

**Comment by apanashchenko** [comment]
@asolntsev for example:
mvn test -Dbrowser=webdrivers.FirefoxBambooDriver

```java
@Step
    public void importDashboard(String pathToFile) {
        if (WebDriverRunner.isFirefox()) {
            FileSelectingHandler.setStyleDisplay($(Locators.IMPORT_DASHBOARD));
        } else {
            FileSelectingHandler.unHide($(Locators.IMPORT_DASHBOARD));
        }
        
        FileSelectingHandler.attachFile($(Locators.IMPORT_DASHBOARD), pathToFile);
    }
```
This method doesn't work, because `WebDriverRunner.isFirefox() == false`. This work only if you use selenide browsers firefox, chrome and etc.
I can read property `browser`, but i think it's not very useful if you have several custom browser.

**Comment by asolntsev** [comment]
@apanashchenko ok, now I understand why you need this. 
But your suggested algorithm also will not always work because class `webdrivers.FirefoxBambooDriver` probably will not extend `FirefoxDriver`. User can create any `Provider` or `Webdriver` class that does not extend `FirefoxDriver`, but uses firefox under the neath.

Briefly, Selenide cannot guess which driver you are using. You are the only who knows. :)

**Comment by asolntsev** [comment]
expired. Closing the issue.
