### ISSUE TITLE
There is no shouldBe(empty)/shouldNotBe(empty) methods for ElementsCollection

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#214]
The case is, I should have n>0 elements of the same kind on the screen, and then iterate through them checking their children properties. The number of elements is dynamic.

```
 $$(".element") - doesn't search for it for the moment
 $$(".element").size() - is always 0, which is logical consequence of that, and it is okay
```

I see only $$(".element").shouldHave(texts,exactTexts, size) - nothing of that can help me to see if the number > 0, as texts and sizes are not static.

Please add the shouldBe(empty), shouldNotBe(empty) functionality to collections 

or shouldNotHaveSize(int), as shouldBe(empty)==shouldHaveSize(0).

**Comment by asolntsev** [comment]
@vinogradoff There is method `$$.shouldBe(empty);`.
What about `$$.shouldNot*` methods, I suggest not doing it. It makes code complicate, but I am almost sure that it's not needed. 

Why one should need methods like:
* `$$("h1").shouldNotHave(texts("a", "b", "c"));`
* `$$("h1").shouldNotHave(exactTexts("aA", "bB", "cC"));`
* `$$("h1").shouldNotHave(size(3));` ?

**Comment by vinogradoff** [comment]
There are cases for ui-testing like - see that the page has news, address book has contacts. In many cases the count and the content of the data is not important (Smoke-Tests).

We agreed upon shouldNotBe(empty).

**Comment by asolntsev** [comment]
It seems that it was implemented some time ago.
Now we have the following methods in Selenide:
* `$$().shouldHave(sizeGreaterThan(0));`
* `$$().shouldHave(sizeLessThan(3));`
