### ISSUE TITLE
Please enable performance logs for chrome by default.

### ISSUE THREAD

**Issue by Patzifist** [codeborne/selenide#220]
Please enable performance logs for chrome by default.

**Comment by asolntsev** [comment]
@Patzifist Does it make chrome tests longer? How much longer?

**Comment by asolntsev** [comment]
@Patzifist How will you use performance logs? What tool will you use for analyzing logs? Couldn't we incorporate this analysis into Selenide?

**Comment by vinogradoff** [comment]
Why? Only for chrome? What is the reason?

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
