### ISSUE TITLE
add Screenshots.getLastScreenShotAsFile()

### ISSUE THREAD

**Issue by yashaka** [codeborne/selenide#226]
It would be great to have a method returning last screenshot, taken by Selenide.
Currently we have Screenshots.getScreenShotAsFile() which actually not only "gets" but "takes" screenshot, which is IMHO a bit confusing, taking into account that there is separate method: Screenshots.takeScreenShot().

Here is the use case where this feature (Screenshots.getLastScreenShotAsFile()) will help.

When working with Allure, the following code will attach screenshots to the allure report after each test:
```java
    @After
    public void tearDown() throws IOException {
        screenshot();
    }

    @Attachment(type = "image/png")
    public byte[] screenshot() throws IOException {
        File screenshot = Screenshots.getScreenShotAsFile();
        return Files.toByteArray(screenshot);
    }
```
But such implementation is not very useful sometimes:
- user may have other @After method, that e.g. will clear something after the test. And this "second @After" may run before "sreenshooting after" and so screenshot may be not relevant. This may be worked-around by putting everything into one @After. But IMHO the latter is a bit not "agile" and puts the screenshooting logic to the place it is not usefull much. Would be great to hide it somewhere in BaseTest, and forget... And while having BaseTest with "base" @After you may have other Tests with own @Afters.
- Actually attached screenshots are really useful only when test Fails... So there is no need to create it after test passes. 

Seems like it may be useful if Selenide allows to write code like:

```java
    @After
    public void tearDown() throws IOException {
        screenshot();
    }

    @Attachment(type = "image/png")
    public byte[] screenshot() throws IOException {
        if (Screenshots.isScreenShotTakenForContext(Screenshots.getLastContext())
            File screenshot = Screenshots.getLastScreenShotAsFile();
            return Files.toByteArray(screenshot);
        }
        return null; // :) i am not sure Allure will handle this OK :)
    }
```
This is code may make sense, if the https://github.com/codeborne/selenide/issues/225 will be implemented based on other Selenide feature - "contexts". I.e. when "TestClass" and "testMethod" folders for screenshots will be implemented via "automatic usage of Sceenshots.startContext()/finishContext()" feature. Meaning - "testMethod" - may be just a "screenshot context" so we can check if "last context had screenshots"...

P.S.
All this looks a bit complicated... Maybe there are other ways to implement what is needed...

**Comment by asolntsev** [comment]
@yashaka I have added method `Screenshots.getLastScreenshot()` that returns a File with screenshot. Does it solve your problem?

**Comment by asolntsev** [comment]
@yashaka I also renamed method `Screenshots.getScreenShotAsFile()` to `takeScreenShotAsFile()`. I agree, it's more appropriate name.

**Comment by yashaka** [comment]
@asolntsev, seems that your changes may solve the problem. @juliaviluhina and I will test this and give final feedback.

**Comment by juliaviluhina** [comment]
Thank you for this feature )
It works
