### ISSUE TITLE
CSS Selector Issue

### ISSUE THREAD

**Issue by leslyarun** [codeborne/selenide#229]
Hi, 

I have the below code:
````
<span class="icons_sprite dialogCloseIcon toolTipCloseIcon"></span>
````

If I write code like ```` $$(By.cssSelector(".toolTipCloseIcon")).filter(visible).get(0).click(); ```` , its working, but ````$$(By.cssSelector("icons_sprite.dialogCloseIcon.toolTipCloseIcon")).filter(visible).get(0).click(); ```` doesn't find the element.

Any effecient way of finding the above span element ?

**Comment by asolntsev** [comment]
@leslyarun You forgot to add "." before `icons_sprite`. The right code would be:

`$$(By.cssSelector(".icons_sprite.dialogCloseIcon.toolTipCloseIcon")).filter(visible).get(0).click();`

**Comment by leslyarun** [comment]
@asolntsev Thanks a lot buddy :)
