### ISSUE TITLE
Add At check and Url to PageObjects

### ISSUE THREAD

**Issue by lazytesting** [codeborne/selenide#233]
Some other test frameworks have the possibility to have an url and a "at" check in the PageObjects.
It would be nice if those could be added to Selenide as well.

<b>Url</b>
When I want to navigate to Google using page object I currently need to do:
GoogleSearchPage searchPage = open("http://www.google.com", GoogleSearchPage.class);
This way I need to manage the urls within my tests and not in my page object.

It would be easier if I could add an url to the GoogleSearchPage class and just call open without the url:
GoogleSearchPage searchPage = open(GoogleSearchPage.class);

<b>At check</b>
When I open a page I would like to ensure that I'm actually on that specific page.
A common pattern is to specify an At check in the pageObject.
In that check you can specify an condition, by example an element which should be present.

When open() is called with an pageobject class the At is executed, if the check fails a specific error is thrown which indicate that you're not on the expected page. It might also be useful to be able to call the At independent.

**Comment by asolntsev** [comment]
@lazytesting 

**Url**
Seems to be reasonable. Probably page objects could have method `getUrl()`?

**At check**
I am not sure it's really needed. If test occasionally opens a wrong page, the next check will just fail. You will see the problem cause from screenshot. I don't see what benefit would the additional "at" check bring (but it will take more time, thus making your tests slower).

**Comment by lazytesting** [comment]
for Url: 
Would it be possible to do open(GoogleSearchPage.class) or would you need to do 
open(GoogleSearchPage.getUrl(), GoogleSearchPage.class);
the first one would be easier to use of course.

For the At check:
I think it can be useful in two ways:
- By trowing a specific exception it's easier to troubleshoot a failing test.
- When you're testing a wizard with page which are very similar. Example: a wizard with 5 steps and every step has a button to navigate to the next page. If the first click on the next button fails you don't want to wait for an assertion on page 5 to fail. 

In the selenium documentation they are performing the At check in the constructor of the PageObject which might be a nice way of handling it in Selenide as well. But I didn't got that working yet.

**Comment by asolntsev** [comment]
Can you drop me a link to the selenium documentation about At?

**Comment by lazytesting** [comment]
see: http://www.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern

**Comment by lazytesting** [comment]
just had another look, seems that this will work for that At check:
	public HomePage()
	{
		$("Idontexistselector").shouldBe(Condition.present);
	}
	
so for that we don't need any code changes in Selenide. It might be worth it to add it to the documentation/examples.

**Comment by lazytesting** [comment]
For to url, this will work:

Page:
GooglePage {
   public static String url = "http://www.google.com";
}

In Test:
googlePage GooglePage = open(GooglePage.class);

Add this method: 
	 /**
	   * Open a web page and create PageObject for it.
	   * @return PageObject of given class
	   */
	  public static <PageObjectClass> PageObjectClass Open(
	                                                       Class<PageObjectClass> pageObjectClassClass) {	  
		  String url = null;
		  try {
			  Field urlField = pageObjectClassClass.getField("url");
			  url = (String) urlField.get(pageObjectClassClass);
		  }
		  catch (Exception e)
		  {
			  throw new RuntimeException("Failed to get field url in pageobject " + pageObjectClassClass + " field should be public and static.", e);
		  }
		  return  open(url,pageObjectClassClass);						 
	  }

Would it be possible to add this to Selenide?

**Comment by vinogradoff** [comment]
Hi Maarten,

I see some problems in this case. In the modern application world you don’t often have URLs that bring you to any page (bookmarkable urls). Even if, you very often don’t want to have your URL hardcoded to the page, as you may have different servers where you app should be installed.

So this method would be conditionally useful for the starting page only.

Can you use it like this: 

open(google_page_url);
GooglePage page=new GooglePage(); 

?

**Comment by lazytesting** [comment]
Indeed for single page applications it's not really useful but for testing websites it makes things easier.

I forgot about the environments, I'm running my tests often against multiple environments (local dev /Ci/Test/acc). 

What we do in our .Net based framework might be useful:
1. If the defined url starts with http or https we consider it as a complete url and use it as is.
2. If the url doesn't start with http or https we consider it as a url part.

In the second scenario we read the base url from the config. For Java I think it makes more sense to read a VM argument for this. So as user I can just pass -DbaseUrl = "http://test.mysite.com" to the VM arguments.

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
