### ISSUE TITLE
Would like overloaded methods of SelenideElement.shouldBe(...) to specify timeout for one command

### ISSUE THREAD

**Issue by charlescapps** [codeborne/selenide#235]
For example, with our automation we often have some particular steps that could take a long time, e.g. when we are uploading a file and waiting for an element on the page to be visible, or waiting for a video to encode. 

Currently, the best we can do in Selenide is either (1) wait before the command:
<pre>Selenide.sleep(5000)
$("div.success-message").shouldBe(visible);
</pre>

...or (2) we can change the configuration before hand which is a bit clunky: 

<pre>
Configuration.timeout = 10000;
try {
    $("div.success-message").shouldBe(visible);
} finally {
    Configuration.timeout = DEFAULT_SELENIDE_TIMEOUT;
}
</pre>

It would be <strong>better</strong> if we could have an overloaded method for "shouldBe()" or set the timeout that is active for the current selenide element, like this:

<strong>Option 1: overloaded shouldBe() method</strong>
<pre>
final long VIDEO_ENCODE_TIMEOUT  = 10000;
$("div.success-message").shouldBe(VIDEO_ENCODE_TIMEOUT, visible);
</pre>

<strong>Option 2: set the timeout used for current SelenideElement.</strong>
<pre>
final long VIDEO_ENCODE_TIMEOUT  = 10000;
$("div.success-message").withTimeout(VIDEO_ENCODE_TIMEOUT)
        .shouldBe(visible);
</pre>

I appreciate your consideration of making this improvement. If I have time I could create a pull request myself, but might not have the time to do so.

Thanks!

**Comment by davidmerrick** [comment]
Agreed!

**Comment by asolntsev** [comment]
@charlescapps @davidmerrick
Selenide has such a method. Instead of `$().shouldBe(visible)`, use method `$().waitUntil(visible, VIDEO_ENCODE_TIMEOUT)`.

Feel free to suggest better API if you think `waitUntil` name is not clear enough.

**Comment by asolntsev** [comment]
@charlescapps @davidmerrick Can I close the issue?

**Comment by davidmerrick** [comment]
Please do! Thanks for your response
