### ISSUE TITLE
Can someone provide me an example of configuring Selenide in Jenkins CI

### ISSUE THREAD

**Issue by leslyarun** [codeborne/selenide#237]
I want to configure jenkins to run Selenide tests. Someone please provide me an example for configuring Selenide on Jenkins

**Comment by asolntsev** [comment]
Sure, this is jenkins configuration for Selenide itself.
Probably the most important settings is the "Start Xvfb before the build, and shut it down after.
<img width="1019" alt="selenide jenkins 1" src="https://cloud.githubusercontent.com/assets/279773/10923035/56029c1a-8287-11e5-83a8-8881df402472.png">
<img width="826" alt="selenide jenkins 2" src="https://cloud.githubusercontent.com/assets/279773/10923036/56041ee6-8287-11e5-89c2-9b182473403a.png">
<img width="855" alt="selenide jenkins 3" src="https://cloud.githubusercontent.com/assets/279773/10923037/56049060-8287-11e5-89c1-068f3db3c157.png">
<img width="849" alt="selenide jenkins 4" src="https://cloud.githubusercontent.com/assets/279773/10923039/56063136-8287-11e5-95ec-22558314bdef.png">
<img width="839" alt="selenide jenkins 5" src="https://cloud.githubusercontent.com/assets/279773/10923038/56058e20-8287-11e5-95a1-0e54487765cd.png">




" checkbox.
