### ISSUE TITLE
Can raw HTML be used as input?

### ISSUE THREAD

**Issue by ipolevoy** [codeborne/selenide#241]
This is more of a question and not an issue. 
I'm a developer of http://javalite.io. 

I'd like to know how easy it would be to use Selenide selectors in ActiveWeb tests (http://javalite.io/testing). 

A typical web controller test looks like this: 

```java 
public class HelloControllerSpec extends ControllerSpec {
    @Test
    public void shouldSendParamsToIndex() {
        request().param("first_name", "John").param("last_name", "Deere").get("index");
        String response = responseContent();
       a(response).shouldContain("Hello, John"); // simple string search
    }
}
```

As you can see, the `response` is a string containing a full HTML. In my framework, controllers are tested outside of container, so there is no real HTTP involved. All I need is to find specific elements in HTML. 

This would be perfect: 

```java
String html = "<hmtl><div id='message'>Hello</div></html>"
open(html);
$("#message").shouldHave(text("Hello"));
```

Is there some code in Selenide I can adopt for this, or if not is there another solution? 

tx

**Comment by asolntsev** [comment]
@ipolevoy Wow, cool question! No, right now there is no something similar in Selenide. Selenide forwards all selectors to the selenium webdriver, and webdriver forwards all selectors to a browser. 
But I will think how to make it possible.

**Comment by philipp-kolesnikov** [comment]
@ipolevoy You can try http://jsoup.org/.

**Comment by ipolevoy** [comment]
@asolntsev this makes sense, thanks for the suggestion!

**Comment by ipolevoy** [comment]
@philipp-kolesnikov thanks, will look into it.
