### ISSUE TITLE
Getting last screenshot made by Selenide in simple way

### ISSUE THREAD

**Issue by juliaviluhina** [codeborne/selenide#242]
Might be this issue is similar to #226

If in test it is used allure reports, it will be helpful to get screenshot, which is made by Selenide.
In class ScreenShotLaboratory there is protected field allScreenshots, which contains all screenshots of test.
It would be helpful to get last screenshot from this list in simple way.
Moreover, it would be helpful to get whole this list (allScreenshots).

**Comment by asolntsev** [comment]
@juliaviluhina I have added method Screenshots.getLastScreenshot() that returns a File with screenshot. Does it solve your problem?

**Comment by juliaviluhina** [comment]
Thank you so much )
Yes, my problem is solved by you.
