### ISSUE TITLE
Improve $$.find performance

### ISSUE THREAD

**Issue by juliaviluhina** [codeborne/selenide#243]
Currently find(condition) = filter(condition).get(0)
​
if we have 100 items with 10th that matches condition
the items.find(condition) will do 100 + 1 operations
This often results in very slow tests with selenide in such contexts.
​
Would you make .find() implementation faster and direct, without usage of filter under the hood, please?
So it will be only 10 operations of finding the item from the example above.

**Comment by asolntsev** [comment]
Good point!
I will do it asap.

**Comment by asolntsev** [comment]
@juliaviluhina Well, it was not so simple as I thought in the beginning. :)
But I still plan to do it.

**Comment by juliaviluhina** [comment]
Thank you for feedback. I will expect :)

**Comment by yashaka** [comment]
@asolntsev 

> I will do it asap.

:)

Just encountered one more project, where this feature would help a lot... Unfortunately sometimes there are a lot of "similar" elements, implemented in "a bit" different way ("god bless" those developers), so you can't build proper selector, and have to use "search via conditions". In addition you can't make those developers to refactor implementation... In such cases this feature will save our life... Current implementation of `#find` is too slow to be used in such cases efficiently... 

Please, implement it:)

**Comment by asolntsev** [comment]
@juliaviluhina @yashaka Yes, it's funny. :)
Thanks for the reminder. But it's really not trivial.

I will try to implement it in next release.

**Comment by rosolko** [comment]
Meged.
