### ISSUE TITLE
Ignored click requests (sometimes)

### ISSUE THREAD

**Issue by java-artisan** [codeborne/selenide#247]
I'm having trouble for clicking on links - sometimes it looks like no click event happens.

The use case is that I'm clicking on **#user-settings > i.settings16** to make a popover appear, containing an element satisfying **#current-build-info**. Once in while this works. But usually it doesn't. 

The scenario works when I'm clicking manually on the links. Invoking jQuery click on the element works also.

Is there something I am missing ?

```scala
val $1 = $("#user-settings > i.settings16")
$1.waitWhile(not(exist), 20000)
$1.click()
val $2 = $("#current-build-info") // should appear when clicking on $1
$2.waitWhile(not(exist), 20000) // usually never happens
```

```html
<a id="user-settings" class="optimus btn btn-mini" data-original-title="" title="">
  <i class="settings16"></i>
</a>
```
Scala 2.11.7, Firefox driver, Firefox 42, Linux Mint 17.2 x64

**Comment by asolntsev** [comment]
Do you have the same problem with Chrome?

As I know, Chrome and Firefox do click elements differently.
Chrome calculates center point of element and clicks this point (even if another element actually locates there). But Firefox actually clicks given element. 

So the question is: to what element you bind click handler - to `<a>` or to `<i>`?

**Comment by java-artisan** [comment]
On 11/17/2015 01:21 PM, Andrei Solntsev wrote:
>
> Do you have the same problem with Chrome?
>
I've tried to get it working in Chromium, but it doesn't react to the 
script. It pops up the browser, but just stays there. But it might have 
been a bit ... hacky. How does one chose correctly the Chrome browser ?
>
> As I know, Chrome and Firefox do click elements differently.
> Chrome calculates center point of element and clicks this point (even 
> if another element actually locates there). But Firefox actually 
> clicks given element.
>
> So the question is: to what element you bind click handler - to |<a>| 
> or to |<i>|?
>
It's the <a> element. I've tried <a> and <i> but it's all the same: 
sometimes it works, sometimes it doesn't.

**Comment by asolntsev** [comment]
In order to run chrome browser, you just need to add the following command
line option:
-Dselenide.browser=chrome

See wiki:
https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver

Andrei Solntsev

2015-11-17 15:24 GMT+02:00 java-artisan <notifications@github.com>:

**Comment by vinogradoff** [comment]
Exception is raised on $1.click() ? which one?
Also try:
   
     1$.waitUntil(visible, 20000)

as exists is not the same as visible, it could be in DOM but invisible.

**Comment by vinogradoff** [comment]
And in the most cases you don't need 1$.wait... lines at all. Only if your buttons appear >4 seconds after the page is loaded.

**Comment by java-artisan** [comment]
I've added these to the startup arguments

-Dselenide.browser=chrome 
-Dwebdriver.chrome.driver=/usr/lib/chromium-browser/chromium-browser

And the same happens as before: Opens a window and sits there. The 
addons are loaded too apparently. So maybe there's a conflict somewhere ?

Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed 
out waiting for [http://localhost:31021/status] to be available after 
20001 ms

**Comment by java-artisan** [comment]
For good measure I've installed the real Chrome browser. The browser 
starts but nothing happens. On the console I'm getting:

org.openqa.selenium.remote.UnreachableBrowserException: Could not start 
a new session. Possible causes are invalid address of the remote server 
or browser start-up failure.

The arguments:

-Dselenide.browser=chrome -Dwebdriver.chrome.driver=/usr/bin/google-chrome

**Comment by vinogradoff** [comment]
Driver is not your google-chrome executable, but the chrome-driver from 
https://sites.google.com/a/chromium.org/chromedriver/downloads <https://sites.google.com/a/chromium.org/chromedriver/downloads>

**Comment by java-artisan** [comment]
Okay - sorry for that. You see I'm new to this. :-) Thank you for being 
patient. :-)

It works now. But the result is the same as for FireFox; the click is 
not happening. I even disabled dual screen to make sure the positioning 
wasn't off.

I'll have to dig deeper into the click subscription. Maybe the click 
happens before the popover gets assigned to the link ? Can Selenide log 
on the browser's console ?

**Comment by asolntsev** [comment]
@java-artisan Yes, it's absolutely possible that click happens before the popover gets assigned to the link. No, as I know, neither Selenium nor Selenide cannot know if click handler has been bound to the element.

I typically recommend to build application so that
1. The button is disabled at the beginning
2. JS code binds click handler to the button
3. JS enables the button
4. Test waits until button is enabled:
`$(".btn").shouldBe(enabled).click();`

This is the only valid path. If items 1-3 are not done, it can be considered as bug, because a real user can theoretically click button before it's properly initialized.

**Comment by java-artisan** [comment]
I didn't even thought about that ... :-)

I'll try it first thing next morning. Many thanks ! :-)

**Comment by asolntsev** [comment]
Closing issue for now. Please re-open if you get new information.

**Comment by java-artisan** [comment]
Well... it's with a certain shame I report this was my issue really. A stupid timing issue that could be solved by simple means. My apologies for wasting your time people. :-/

It's working beautifully now. Many thanks for the help !

**Comment by asolntsev** [comment]
No problems, feel free to report other issues if you happen to find some.

Andrei Solntsev

2015-11-25 11:29 GMT+02:00 java-artisan <notifications@github.com>:
