### ISSUE TITLE
Possibility to capture element text/attribute during the condition check

### ISSUE THREAD

**Issue by dmak** [codeborne/selenide#248]
This is not actually an issue, but rather request for support / sharing the ideas.
In my test I have the following code:

``` java
final SelenideElement tableCell = $("table tr:first-child td a").shouldHave(someText());

logger.warn(">> element:" + tableCell);

String elementText = tableCell.text();

logger.warn(">> elementText:" + elementText + " <<");
logger.warn(">> element:" + tableCell);

elementText = createRetryTemplate().execute(new RetryCallback<String, RuntimeException>() {

    @Override
    public String doWithRetry(RetryContext context) throws RuntimeException {
        String text = tableCell.text();

        if (StringUtils.isEmpty(text)) {
            throw new AssertionError("Element " + tableCell + " has no text");
        }

        return text;
    }
});
```

It does some "strange" things, but that is just to demonstrate the problem. The condition `someText()` is the following (it is straightforward with no surprises):

```
static Condition someText() {
    return new Condition("hasSomeText") {
        @Override
        public boolean apply(WebElement element) {
            return element.getText().length() > 0;
        }

        @Override
        public String toString() {
            return "anyText";
        }
    };
}
```

The test waits until the given element has some text, so by return from the `shouldHave()` function we expect that element has some text. Then it displays the contents of the element, retrieves the text again, and then it launches the text retrieving in a loop (using `spring-batch` [`RetryTemplate`](http://docs.spring.io/spring-batch/2.1.x/apidocs/org/springframework/batch/retry/support/RetryTemplate.html)). The test works OK in _most_ runs and produces the output like that (text changes from run to run):

```
11.10 11:58:44.732 WARN  [MyTest] >> element:<a>183502</a>
11.10 11:58:44.762 WARN  [MyTest] >> elementText:183502 <<
11.10 11:58:44.866 WARN  [MyTest] >> element:<a>183502</a>
11.10 11:58:44.866 DEBUG [RetryTemplate] Retry: count=0
11.10 11:58:44.889 WARN  [MyTest] >> elementText:183502 <<
```

However in 2 cases out of 100 sample runs the code above produces the log like that:

```
11.10 09:58:03.221 WARN  [MyTest] >> element:<a>183466</a>
11.10 09:58:03.255 WARN  [MyTest] >> elementText: <<
11.10 09:58:03.362 WARN  [MyTest] >> element:<a>183466</a>
11.10 09:58:03.363 DEBUG [RetryTemplate] Retry: count=0
11.10 09:58:03.394 WARN  [MyTest] >> elementText:183466 <<
```

As one can see, the text "disappears" for 100ms and then appears again. Unreal :)

What could be the solutions in this case? How to retrieve the element text in consistent and reliable manner?

P.S. The "walkaround" with repeating action smells bad, as Selenide already has done this effort (looping until the condition is met).

**Comment by asolntsev** [comment]
@dmak I don't exactly understand what is your suggestion. 
Does the text of the element actually change time-to-time? Or is it a static element? Is the element visible?
If it's static and visible, and method `text()` returns empty string time-to-time, then it's a bug of webdriver.

**Comment by dmak** [comment]
This is not a static element, thus it is unlikely to be a bug of the webdriver. Perhaps it is being removed and then re-added during the table refresh. But I know that once the condition is met, the test has succeeded. Basically, the big block of code above was initially as simple as that:
```
String elementText = $("table tr:first-child td a").shouldHave(someText()).text();
```
but it does not work reliably (as shown above).

What could be the most effective solution?

**Comment by BorisOsipov** [comment]
closed due no reproducable example.
