### ISSUE TITLE
add PrettyReportCreator for TestNG

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#250]
Now it's only available for JUnit: https://selenide.org/2015/05/05/selenide-2.16-and-2.17

**Comment by asolntsev** [comment]
Added TextReport support for TestNG.

Usage (see [example](https://github.com/codeborne/selenide/blob/master/src/test/java/integration/testng/GoogleTestNGTest.java)):
```java
@Listeners(TextReport.class)
public class GoogleTestNGTest {
    ...
}
```

**Comment by djangofan** [comment]
@asolntsev   Would be neat to see integration with ExtentReports in your framework, but thats just a thought.  Do you know of anyone that uses Selenide with ExtentReports?  Just curious if anyone has tried it.    - djangofan@gmail.com .

**Comment by thasherwin** [comment]
I am not using ExtendReport. I am using Allure Framework report together with Selenide. The TextReport of Selenide is attached in my allure report.

**Comment by asolntsev** [comment]
@djangofan I like it. ExtentReports seems to be similar to `TextReport`. 
Feel free to submit a pull request!
