### ISSUE TITLE
Can't get find elements in new window after calling switchTo().window(1)

### ISSUE THREAD

**Issue by JeremyTX** [codeborne/selenide#251]
```java
switchTo().window(1);
$(By.xpath(someXpath)).click()
```

The $ is still looking for elements on original window.  I've tried calling WebDriverRunner again like so:

```java
switchTo().window(1);
WebDriverRunner.setWebDriver(driver);
$(By.xpath(someXpath)).click()
```

Any help would be much appreciated.  Thanks.

**Comment by asolntsev** [comment]
Hi @JeremyTX !
I am pretty sure that `switchTo(window(1))` does switch to the window and looks for element inside the new window. Selenide has special tests for it.

Probably it's some kind of timing issue? Does it help if you put sleep(1000) after `switchTo().window(1);`?

**Comment by JeremyTX** [comment]
Thank you for the quick response!

I tried sleeping before and after the ```switchTo()``` just incase it was switching before it loads, but no luck.  ```driver.getWindowHandles.length``` returns 2, so it is detecting both windows.  Any other suggestions?

**Comment by JeremyTX** [comment]
It was a frame issue.  I solved it by switching to the frame after switching to the window.  Thanks for the quick response though.  Awesome project!  It's made my work much easier.
