### ISSUE TITLE
add byLinkText, byPartialLinkText Locators

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#257]
Constructs $(page).$(byLinkText("google.com")).shouldBe(visible) - are impossible to implement without writing some custom non-selenide code.

**Comment by asolntsev** [comment]
Why?
It is possible:

```java
$(page).$(By.linkText("google.com")).shouldBe(visible);
$(page).$(By.partialLinkText("google.com")).shouldBe(visible);
```

**Comment by vinogradoff** [comment]
By - is a Selenium class. I think there are some advantages for having code which doesn't have selenium imports. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone
