### ISSUE TITLE
add "magic" for $$() selectors waiting on data loading with ajax

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#258]
The difference between $() selector and $$() is, that $() can operate in terms of loaded/not yet loaded easily.

$$ - searching for collection can wait, if none of the elements are loaded yet, but not when some but not all of the elements are loaded.

It is possible to make the locator magically wait until all of elements (with timeout) are loaded.

**Comment by asolntsev** [comment]
@vinogradoff 
I guess it's impossible, because Selenide does not know how many elements should be in collection.
If you know exact number of elements to wait for, you just can use `$$("li").shouldHave(size(4));`.
This command does exactly what you need: waits until all 4 elements get loaded.

**Comment by vinogradoff** [comment]
That's why I called it magic ;) it's non-trivial but possible, I guess. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by rosolko** [comment]
@vinogradoff No need to apply black magic, I think that `$$("li").shouldHave(size(4))` enough for tests. 
Where you control you test env and data. 
So this kind of magic can easily harass performance is you get non trivial large collection or smth else.
Close for now, if such method really needed reopen issue or create a new one with sample.
