### ISSUE TITLE
find/findBy in ElementCollections should return null instead of throwing exception

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#259]
$$().findBy(text("abc") throws exception, if no element is found.

It should better return null.

**Comment by asolntsev** [comment]
No, `$$().findBy(text("abc"))` does not throw exception. It returns a `SelenideElement` that you can use for further checks, like this:

`$$("tr").findBy(text("abc")).shouldBe(visible);`
`$$("tr").findBy(text("abc")).shouldNot(exist);`
