### ISSUE TITLE
add conditions to validate attributes values as substings

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#262]
Many js-frameworks are using class and style attributes (and some data-\* attributes) with multiple values, e.g. class="button-selected button-focused" etc.

So it would be nice to have a should - condition to check if a value is included in attribute. The most natural is not a substring search, but a-whole-word substring search.

Examples:  

```
   <div class="ok pokemon large-ok" id="a1">
   $("#a1").shouldHave(attributeIncludes("class","ok") - pass
   <div class="pokemon large-ok" id="a1">
   $("#a1").shouldHave(attributeIncludes("class","ok") - fail
```

**Comment by vinogradoff** [comment]
even better if syntax

shouldHave(attibute("class"))
shouldHave(attibute("class").withValueEquals("abc");
shouldHave(attibute("class").withValueContaining("abc");

is possible

**Comment by dimand58** [comment]
@vinogradoff , hi, hasClass(String cssClass) is not enough for your purposes ? (it uses "contains" inside)

**Comment by vinogradoff** [comment]
It's enough for the class, but doesn't help with style or custom attributes. 

I think there are cases, not to many, but they exist. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by asolntsev** [comment]
@vinogradoff 
Yes, we can do something like `shouldHave(attibute("class").withValueContaining("abc");`
I am just not sure that it's really needed.
Your provided example is specifically for `class` attribute, and it's resolved by `$.shouldHave(cssClass))`.
Do you have any realistic examples where you need to check **part** of attribute value?

**Comment by rosolko** [comment]
Looks like there are no realistic examples so close it.
Feel fre to reopen if it's really needed.
