### ISSUE TITLE
setValue() doesn't clear input field if fastSetValue=false, in some ajax-heavy cases

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#269]
We have .append() to add something to the field, so setValue() should probably call clear() before setValue();

**Comment by vinogradoff** [comment]
It is indeed called (SetValue.java:41), but probably not always correctly processed in case of ajax-heavy applications.

It's probably because you don't really have "clear" as a User in JS-App which reacts for each keystroke typed. You either "Backspacing" you field, or select all with double click and then type.

Should we implement this "magic" ?

**Comment by dmlemeshko** [comment]
Hi @vinogradoff , can you provide the AUT example where ```setValue``` doesn't work for you and where the "magic" you want can be tested. 
As I see Selenide uses selenium ```clear()``` method that executes [atom action] (https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/action.js#L75) and I'm sure it works pefrect in the vast majority of cases.
If it doesn't work for a specific AUT, then you can implement your own clear methods (via Ctrl+a ```KEYS``` or maybe other tricky solution - the one that will work for your case), but not modify current implementation just for a rare case.

Regards, Dmitry

**Comment by vinogradoff** [comment]
There is a bug in Selenium .clear() *and* in some cases getValue() doesn't work "correctly" for input type=number because of (wrong?) browser implementation of html5.

See the new InputFieldTest :)

**Comment by vinogradoff** [comment]
Fixed for firefox in selenium 2.49.0, should be fixed for chrome with (next) 1.21 ChromeDriver
