### ISSUE TITLE
add nextSibling()/previousSibling() method to SelenideElement

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#270]
I have sometimes cases like this:

<label id="very good id">Amount:</label>
<span>10000</span>

And would like to select the amount value (=10000)
So, it is very easy to locate the label, but no as easy to locate the value directly.

Perhaps we should add .nextSibling()/previousSibling() convinience method to have this covered? 

(similar to parent/closest etc.)

**Comment by rosolko** [comment]
Use bettor css locator for such cases.
https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors
