### ISSUE TITLE
Need some waiter for opening new window

### ISSUE THREAD

**Issue by yarik666** [codeborne/selenide#271]
Case:
Click on button. Open`s new window.

Then I use swichTo().window("window title"), BUT, sometimes new window opened but still loading and it dont have correctly title. So, in this place my test failing. 

Need some waiter to checking page while it will be loaded and then get window title.

**Comment by asolntsev** [comment]
This is similar to #212 - Selenide waits for frame and alert, but not for window. We must fix it.

**Comment by asolntsev** [comment]
Fixed in Selenide 3.1, will be released soon
