### ISSUE TITLE
Method `switchTo().alert()` should throw `NoAlertPresentException`

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#273]
since Selenide 3.1, it throws `TimeoutException`.

Probably the same problem with methods `switchTo().window()` and `switchTo().frame()`

**Comment by MartyBum** [comment]
Also applies to confirm()

**Comment by asolntsev** [comment]
@MartyBum agree. We must fix it in Selenide 3.4

**Comment by MartyBum** [comment]
@asolntsev  any news on this?

**Comment by asolntsev** [comment]
Hi!
Unfortunately I haven't worked on it meanwhile.
Thanks for the reminder, should do it.

By the way, pull requests are welcomed. :)

Andrei Solntsev

2016-11-08 17:27 GMT+02:00 Martyn <notifications@github.com>:

**Comment by symonk** [comment]
will investigate this one this weekend
