### ISSUE TITLE
select element among multi elements with same selector  

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#279]
Hi guys,
I am new user for Selenide, I faced the following problem, I need to check the display and the text for span after doing register action,
My problem occur when I need to select this element `<span class="help-block">`,  but there are many `<div class="A">` in the page!!, so when I select this span element
`$("div.A span.help-block").shouldBe(visible).shouldBe(text("Not matched password"));`
Then it will select the first matched name, so it will select the text: (No value).

I see that I can select the web element by text!?

`WebElement customer = $(byText("Customer profile"));`

but I got syntax error for the function `byText()`, this is for Selenide version 3.2
< div class="A" >
     < input id="input" name="pass" class="form-control" placeholder="password" type="password">
     < span class="help-block"> No value< /span>
< /div >

< div class="A" >
     < input id="inputConfirm" name="confirm" class="form-control" placeholder="confirm" type="password" >
     < span class="help-block" > Not matched password< /span>
< /div>

**Comment by asolntsev** [comment]
@hana9090 
> I got syntax error for the function byText()
I guess have have to add this line in the beginning of your test: 

```java
import static com.codeborne.selenide.Selectors.byText;
```

Look for this example: https://github.com/codeborne/selenide/blob/master/src/test/java/integration/ByTextTest.java

**Comment by vinogradoff** [comment]
@hana9090 you can also have a look at ElementCollections - $$(selector), you can try to filter your elements: $$("div.A").filterBy(text("xxx")) etc.

**Comment by hana9090** [comment]
Thank you Andrei :)
I used the following code and it is working now :+1: 
```
WebElement error1 = $(Selectors.byText("error Message")); 
$(error1).shouldBe(visible);
```

Thanks vinogradoff :)

**Comment by hana9090** [comment]
if we assume we don't find the element by text, can we have another approach to get it?

**Comment by rosolko** [comment]
So looks like this issue is solved.
Feel free to reopen if needed.
