### ISSUE TITLE
Add the possibility to wait for a HTML page title

### ISSUE THREAD

**Issue by peterkeller** [codeborne/selenide#280]
Actually it's possible to query the HTML page title with `title()`. However, this method returns a `String` and not an implementation of `SelenideElement`. Consequently, it is not possible to wait for a HTML page title such as:

    $(title("My Page Title")).shouldBe(present); // NOK

However, there are situations where the page content is not relevant and it is sufficient to test the HTML page title.

Please, add the possibility to wait for a HTML page title.

(I am aware of `byTitle(String)`, but this method returns elements having a title attribute with given value and not the HTML page title.)

**Comment by asolntsev** [comment]
@peterkeller We can do it, but can you explain why it's needed?
I think it's not a good idea to depend on page title. First of all, because typical user doesn't see this title. You should better to check something on the page. Some text or image.

**Comment by vinogradoff** [comment]
I think the question is reasonable, but just wondering…

if straightforward

$(„title“).shouldHave(exactText((„My Page Title“))

does the job?

**Comment by vinogradoff** [comment]
If you just want make sure the page is loaded, you probably do not need any "wait", because ajax normally doesn't change title dynamically. But it can :) Anyway, the example above will wait if needed, and not wait if not needed.

**Comment by peterkeller** [comment]
@vinogradoff: I tried your suggestion, however my little JUnit test fails:

    open("http://www.google.com");
    assertEquals("Google", title());   // OK
    $("title").shouldHave(exactText("Google"));  // NOK

Output:

> Element should have exact text 'Google' {title}
Element: '<title displayed:false></title>'
Screenshot: file:/Development/java/projects/projects-test/selenide/build/reports/tests/1455265141846.0.png
Timeout: 4 s.
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	[...]

Testing the title could serve as a quicktest that a link target is valid without relying on a changing page content.

**Comment by vinogradoff** [comment]
You are right, good or bad - <title> is considered "invisible" by Selenium.
So it's reasonable question for me.

Just curious does
assertEquals("Your Title", title()); 
ever fails in your project, because title is tampered by ajax?

**Comment by RobertKielty** [comment]
Hi @asolntsev HOpe this finds you well. Here's a Selenide use case for checking the content of a title of a page:

Write a _smoketest (or deployment test) _to check that a deployed application has the correct layout: when the app is configured on the server side to target browsers running on laptops it has one title, when it is targeting tablets it has a different title. This is a use of Selenide that is not user focused.

**Comment by asolntsev** [comment]
@RobertKielty Thank you for sharing knowledge. Yes, this is the case for using title.
But, why should you need to wait for title? I believe page title is loaded immediately with page. It cannot be modified dynamically later.

**Comment by asolntsev** [comment]
@RobertKielty Can we close the issue? Or please answer the last question: "why should you need to wait for title? I believe page title is loaded immediately with page. It cannot be modified dynamically later."

**Comment by RobertKielty** [comment]
I think it's OK to close this.

**Comment by asolntsev** [comment]
thank you!

**Comment by rafaelcgs10** [comment]
> @vinogradoff: I tried your suggestion, however my little JUnit test fails:
> 
> ```
> open("http://www.google.com");
> assertEquals("Google", title());   // OK
> $("title").shouldHave(exactText("Google"));  // NOK
> ```
> 
> Output:
> 
> > Element should have exact text 'Google' {title}
> > Element: '<title displayed:false></title>'
> > Screenshot: file:/Development/java/projects/projects-test/selenide/build/reports/tests/1455265141846.0.png
> > Timeout: 4 s.
> > at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
> > at com.codeborne.selenide.commands.Should.should(Should.java:35)
> > [...]
> 
> Testing the title could serve as a quicktest that a link target is valid without relying on a changing page content.

I know that this issue is closed, so let me know if I should open a new one!

I'm getting this exact same problem on a website that I'm working on.
If I try `title()` I get the page's title, but if I try `$("title")` I get Element:` '<title displayed:false></title>'` .
What could cause this?

**Comment by asolntsev** [comment]
@rafaelcgs10 this is a known limitation of Selenium webdriver. It thinks that <title> is invisible (probably because it's located outside of <body>). We cannot fix it.

Still, you don't need to WAIT for title. Plain old `assertEquals("Your Title", title());` should work for you.

**Comment by jf352** [comment]
> @rafaelcgs10 this is a known limitation of Selenium webdriver. It thinks that <title> is invisible (probably because it's located outside of ). We cannot fix it.
> 
> Still, you don't need to WAIT for title. Plain old `assertEquals("Your Title", title());` should work for you.

While we don't have to WAIT for the title, having an implementation of "shouldHave", or "shouldBe", etc for the page title is extremely useful for one simple reason - Selenide's own assert functionality through shouldHave/shouldBe etc automatically takes a screenshot for you.

During automated testing, if we want to test the title, it would be fantastic if we could do this with the title as well. If we rely on Asserts, we don't get a screenshot/HTML capture back, which sucks in terms of debugging what is going wrong.

**Comment by asolntsev** [comment]
@jf352 Thank you for the feedback. We are working on this problem in https://github.com/selenide/selenide/pull/1478. Plan to include it in next Selenide release.

**Comment by asolntsev** [comment]
@peterkeller @jamfor352 @RobertKielty FYI we added this functionality in Selenide 5.23.0

Now it's possible to wait for page URL or title:
```java
webdriver().shouldHave(url("https://auth.google.com"));
webdriver().shouldHave(title("Login page"));
```

See https://selenide.org/2021/07/16/selenide-5.23.0/#checks-for-url
