### ISSUE TITLE
Test E-commerce with Selenide

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#281]
Hello friends,
Please, I am going to make automation test for an ecommerce website, So what do you think to use Selenide for that?
Is it a good choice for ecommerce testing?

**Comment by newromatester** [comment]
Yeap, it's the best tool for automation testing, easy for writing and reading code, a lot of cheсks

use the page component pattern if site have similar elements on the pages. It will be easy for writing with Selenide

Just try it and you fall in love with the Selenide

**Comment by asolntsev** [comment]
+1 :)

**Comment by vinogradoff** [comment]
++ :)

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone
