### ISSUE TITLE
Size() on collection is not working

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#283]
When i try to retrvieve the size of a collection is get 0 as a result using Selenide version 3.2
https://www.google.nl/?gfe_rd=cr&ei=iAu6Vs3bM4jm-gbSlofoBw&gws_rd=ssl#q=samsung

 int index = $$(".rc h3").size();
      System.out.println(index);

**Comment by RomanIsko** [comment]
Try to add
```java
sleep(1000);
```
after open page.

It works for me 
```java
    @Test
    public void testName() throws Exception {
        open("https://www.google.nl/?gfe_rd=cr&ei=iAu6Vs3bM4jm-gbSlofoBw&gws_rd=ssl#q=samsung");
        sleep(1000);
        int index = $$(".rc h3").size();
        System.out.println(index);
    }
```

**Comment by vinogradoff** [comment]
Bad news is - in Ajax-Apps .size() could return less elements, than there are.

Good news is - in Selenide 3.3 (to be released in February) this will be fixed!

**Comment by thasherwin** [comment]
Okay. thanks for the quick reply. Yes. it works with a sleep.I cannot wait for release 3.3 :)

**Comment by asolntsev** [comment]
@thasherwin It's because method `size()` returns number of currently loaded elements. But Selenide uses lazy loading mechanism for everything.

Don't ask size. You are writing test, right? You don't need `System.out.println`, you need to check:
```java
$$(".rc h3").shouldHave(size(3));
```

In this case Selenide will load elements.

**Comment by thasherwin** [comment]
Okay. Clear. I am being lazy also. I did it this way because i would like to loop trought the links and capture the link text of google. The link text needs to be asserted against an internal application that shows the same link texts as google

**Comment by asolntsev** [comment]
Well, then you could assert that there is exactly 10 links on the page
(Google shows 10 results, right?).

$$("li.g").shouldHave(size(10));
// and now check links

**Comment by thasherwin** [comment]
Yes exactly thanks. I do have work-around so that I can get the index by size. I want the flexibility to check links on a page without having to specified exactly how many links I expect. Also i don't want to use sleep. The below solution looks reliable.

@Test
public void testName() {
   open("https://www.google.nl/?gfe_rd=cr&ei=iAu6Vs3bM4jm-gbSlofoBw&gws_rd=ssl#q=samsung");
   $$(".rc h3").get(1);
   int index = $$(".rc h3").size();
   System.out.println(index);
}

**Comment by asolntsev** [comment]
@thasherwin I don't think it's realiable. `$$(".rc h3").get(1);` actually does nothing. It just creates a "wrapper" for element without doing anything with it. It's called _lazy loading_.

I still don't understand what exactly you want to check. Whatever you want to test, do it. Test it! Use one of `should...` methods.

For example, if you want to check text of links:
```java
$(".rc h3", 1).shouldHave(text("aaa"));
$(".rc h3", 4).shouldHave(text("bbb"));
```

**Comment by thasherwin** [comment]
This is my test.

 ```java
@Test
    public void test(){
        ArrayList<String> linkTitleArray = new ArrayList<String>();
        open("https://www.google.nl/?gfe_rd=cr&ei=iAu6Vs3bM4jm-gbSlofoBw&gws_rd=ssl#q=samsung");
        $$(".rc` h3").get(1);
        int index = $$(".rc h3").size();
        for(int i = 0 ; i < index;i++){
            linkTitleArray.add($$(".rc h3").get(i).getText());
        }
        open(_url);
        for(int i = 0; i< index;i++){
            $$(".g.result>h3").get(i).shouldHave(text(linkTitleArray.get(i)));
        }
```
 The reason for adding ```$$(".rc` h3").get(1);``` is to make sure that the next function ```int index = $$(".rc h3").size();``` will give me 6 instead of 0. I could put sleep(1000) instead of ```$$(".rc` h3").get(1);```  but a sleep does not seem to be reliable. It might be that i still get 0 as a result after 1 second sleep.
But after reading your anwser i will use this code ```$$(".rc h3").get(1).getText();``` just to make sure that the Ajax-Apps .size() is initialized

**Comment by asolntsev** [comment]
@thasherwin There is still a potential problem. It can happen that the 1st element is loaded, but not all elements are loaded yet. So, `$$(".rc h3").size();` could return 1, though there is 10 or 100 elements on the page. It depends on speed of elements' loading.

**Comment by thasherwin** [comment]
OK. Thanks for the clear explanation. Then the only reliable option is to retrieve the links using an index number.
