### ISSUE TITLE
Dead link on selenide.org

### ISSUE THREAD

**Issue by admizh** [codeborne/selenide#286]
![image](https://cloud.githubusercontent.com/assets/6014483/12969067/9605735e-d094-11e5-85d3-4960841f65a4.png)

![image](https://cloud.githubusercontent.com/assets/6014483/12969079/b2d90518-d094-11e5-84de-111022604b7c.png)

**Comment by asolntsev** [comment]
Yes, it seems to happen because of Jekyll upgrade on github pages. We are researching it, but still don't understand what's the problem. :(

**Comment by asolntsev** [comment]
@admizh Now it should be fixed. We had to debug Jekyll internals, but now it works.
