### ISSUE TITLE
Use Java 8 (Lambdas) in Selenide

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#289]
This ticket is registered for brainstorming. What could be lambdas useful for?

Some ideas:
1. Use predicate as a condition:
   - `$("div").shouldBe(se -> se.getText().startsWith("Dear client "));`
2. Run tests inside window/tab/frame:
   - `inWindow("my window title", w -> {....});`
   - `inFrame("my frame name", f -> {....});`
3. Your ideas?...

**Comment by JasonTolotta** [comment]
I have not come across a need for Lambdas in Selenide.

`ElementsCollection` already has Stream, so that is all I need.
