### ISSUE TITLE
screenshot() of SelenideElement creates the file in "working dir" and without extension

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#290]
should probably use .png and reportsDir instead...

**Comment by pavelpp** [comment]
I can confirm that this is the case.

**Comment by pavelpp** [comment]
It using this method, which does not seem to be correct

```
protected String generateScreenshotFileName() {
    return currentContext + timestamp() + "." + screenshotCounter.getAndIncrement();
  }
```

It placed dot in the wrong place and forgets to add "png". Moving file into a folder with corresponding test name would also make sense, I suppose.

**Comment by asolntsev** [comment]
Thank you for such a detailed description. It will help to fix the issue.

**Comment by simple-elf** [comment]
Thanks a lot. Faced same issue
