### ISSUE TITLE
Possibiltiy to grab report results of @Listeners(TextReport.class) and add it in Allure

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#293]
Hi Selenide team,

I have a question whether it's possible to grab the listener results and attach that in the Allure report? If so can you please explain how i can grab the results? It would be awesome if this is possible.

This listener @Listeners(TextReport.class) 
Thanks,

Regards,

Sherwin

**Comment by asolntsev** [comment]
Hi @thasherwin !
I don't know exactly what you need to attach, but probably this example helps? https://github.com/selenide-examples/selenide-allure-junit

This is a sample Selenide test that generates Allure report with screenshots.

**Comment by thasherwin** [comment]
Sorry for not being very clear. The example really helps with the screenshots. I do wonder about the Selenide report listener that you see in the console. Is it also possible to grab that so I can attach it?

Below an example of the Selenide listener I see in the console: That is what i mean

+--------------------+----------------------------------------------------------------------+----------+----------+
|Element             |Subject                                                               |Status    |ms.       |
+--------------------+----------------------------------------------------------------------+----------+----------+
|open                |https://www.google.com| PASS      |4401      |
|#sblsbb|click()         |PASS

**Comment by thasherwin** [comment]
Any updates? Or is this something that needs to be developed?

**Comment by asolntsev** [comment]
Hi @thasherwin!
Yes, I guess this feature request needs some development. Probably one method. I haven't investigated it yet. 
P.S. Pull requests are welcome!

**Comment by thasherwin** [comment]
Okay. I will see what i can do. I do wonder what class is doing the printing in the console so i can look into it.

**Comment by asolntsev** [comment]
This is class `com.codeborne.selenide.logevents.SimpleReport`  (called by class `com.codeborne.selenide.junit.TextReport` or `com.codeborne.selenide.testng.TextReport`)

**Comment by thasherwin** [comment]
pull request is created

**Comment by asolntsev** [comment]
Pull request #298 was cancelled, so I am closing the issue too.
