### ISSUE TITLE
Selenide + Linux Server

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#295]
I tried my Selenide test using Maven at windows environment. and run the test using command lines by running batches.

I am wondering if I can run the same test using ssh Linux server. Is ssh able to open a browser? 
Any ideas?

Thanks

**Comment by vinogradoff** [comment]
Of course you can install & start browser on linux, see manuals for your lunix version.

Then, if you don’t have a real monitor attached to you machine, you might have a look into xvfb tool, which create a virtual monitor for you.

**Comment by asolntsev** [comment]
@hana9090 Right. You can run Selenium/Selenide tests on Linux. You probably need to activate "Xvfb" plugin in Jenkins (it starts virtual display for every build).

Look at attached screenshots at Selenide project configuration in Jenkins that runs on Linux. 
<img width="839" alt="selenide jenkins 5" src="https://cloud.githubusercontent.com/assets/279773/13205547/39c7a276-d8f3-11e5-9bf6-480ebaf3e439.png">
<img width="849" alt="selenide jenkins 4" src="https://cloud.githubusercontent.com/assets/279773/13205549/39cb939a-d8f3-11e5-908e-c5bcdb314965.png">
<img width="855" alt="selenide jenkins 3" src="https://cloud.githubusercontent.com/assets/279773/13205545/39c6a9e8-d8f3-11e5-9535-e3fabe65c3aa.png">
<img width="826" alt="selenide jenkins 2" src="https://cloud.githubusercontent.com/assets/279773/13205546/39c6c8ba-d8f3-11e5-858a-3a8431b70677.png">
<img width="1019" alt="selenide jenkins 1" src="https://cloud.githubusercontent.com/assets/279773/13205548/39cabab0-d8f3-11e5-8ad8-cbcaf275f497.png">

**Comment by hana9090** [comment]
@asolntsev 
Hi Andrei, Thanks for your answer.

Please, Are there any other simple ways to run the tests on Linux?  without using Jenkins or any other CI server.

**Comment by asolntsev** [comment]
@hana9090 Short answer: Yes! You can run tests on Linux without Jenkins.

First of all, what Linux do you mean - desktop or server?
* On desktop Linux (like on your laptop) you can run tests without any additional actions.
* On server Linux (without graphical environment) you need to Xvfb ("virtual frame buffer") to emulate graphical environment. It's a simple command-line program.

**Comment by hana9090** [comment]
on Server Linux: using AWS server

I hear about Xvfb for the first time, is it included command at Linux?
how to use it with my Selenide test cases on top of maven. Please, could you help me?

**Comment by asolntsev** [comment]
@hana9090 And why should you want to run test on server, but without CI? You want to SSH to server and run tests there? Why?

Xvfb is not built-in, you need to install it. Just google it. The first search result gives all the answers:
http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/

**Comment by hana9090** [comment]
I heard that Jenkins needs lots of configuration, I need to put my tests on  AWS server and run on daily basis.

then when I run my test cases, I have to enter something like this:
xvfb-run mvn test 

Just this thing to let the browser opening 

Thanks @asolntsev
