### ISSUE TITLE
Add option "chrome.switches"

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#297]
When using Chrome browser, we sometimes want to pass switches to chrome. 
For example,
 * options.addArguments("chrome.switches", "--disable-popup-blocking");
 * options.addArguments("chrome.switches", "--start-maximized");

Add configuration parameter `-Dselenide.chrome.switches`. It can be empty by default.

**Comment by asolntsev** [comment]
Done in Selenide 3.4

**Comment by paul-nelson-baker** [comment]
To those who found this via Googling (like myself), per the javadoc, this is now deprecated in favor of `-Dchromeoptions.args=<comma-separated list of switches>`.
