### ISSUE TITLE
Condition "shouldNot(exist)" throws an exception when it's being checked and the element doesn't exist

### ISSUE THREAD

**Issue by mastepan** [codeborne/selenide#299]
### selenide/src/main/java/com/codeborne/selenide/Condition.java
`public static final Condition exist = new Condition("exist") {`
`    @Override`
`    public boolean apply(WebElement element) {`
`        element.isDisplayed(); // should be removed, this code doesn't matter, apply always return true - that's ok`
`        return true;`
`    }`
 ` };`
 

What about the following solution?

1. catch an exception throwed by getWebElement()
2. 
-if the condition is **inverted exist** (element shouldn't exist)
    - ignore a throwed exception and return null because that's right. We expect the element doesn't exist.

-for other conditions
    - rethrow an exception

### selenide/src/main/java/com/codeborne/selenide/impl/WebElementSource.java:

`public WebElement checkCondition(String prefix, String message, Condition condition, boolean invert) {
    Condition check = invert ? not(condition) : condition;

     RuntimeException lastError = null;
    WebElement element = null;
    try {
      element = getWebElement(); //throws an exception unless the element has been found
      if (element != null && check.apply(element)) {
        return element;
      }
    }
    catch (RuntimeException e) {
      lastError = e;
    }
    //new inserted code follows-------------------------------------------------------------------------------------
    catch(StaleElementReferenceException|NoSuchEementException|IndexOutOfBoundsException ex) {
        if(condition.equals(exist) && invert) {
            //returns null because the element hasn't been found and that's correct (shouldNot(exist))
            return null;  
        } else if condition.equals(exist) && !invert {
            //set last error and do another check cycle if time isn't out yet (until element possibly found eventually - should(exist))
            lastError = ex;
        } else {
            //rethrows an exception for any other condition
            throw ex;
        }
    }
    // end of the new code-------------------------------------------------------------------------------------------
    if (Cleanup.of.isInvalidSelectorError(lastError)) {
      throw Cleanup.of.wrap(lastError);
    }

    if (element == null) {
      if (!check.applyNull()) {
        throw createElementNotFoundError(check, lastError);
      }
    }
    else if (invert) {
      throw new ElementShouldNot(getSearchCriteria(), prefix, message, condition, element, lastError);
    }
    else {
      throw new ElementShould(getSearchCriteria(), prefix, message, condition, element, lastError);
    }
    return null;
  }`

**Comment by asolntsev** [comment]
@mastepan Sorry, I didn't exactly understand your suggestion.
I think that `element.isDisplayed();` is still needed in `exist` condition. Otherwise `exist` is just nonsense - it would always return true. 

Currently, when `element.isDisplayed();` is called on non-existing element, an exception is throwed, and the `$.should(exist)` check fails.

**Comment by mastepan** [comment]
Hi Andrei,
thanks for reply. I still think I'm not totally wrong...well, supposed I do understand what happens in the code.

What `$.should(exist)` does:

1. `SelenideElementProxy` invokes `should(...)` method
2. there it is `dispatchAndRetry(...)` called and it tries to execute the command until time expires or the condition's `apply(...)` returns true
3. should/shouldNot command executes `locator.checkCondition(prefix, message, condition, false/true);` where `locator` is `WebElementSource`. We have the `checkCondition(...) ` method in my first post
4. in this method:

for `should(exist)`: `element = getWebElement();` throws an exception if the element hasn't been found
- otherwise: `check.apply(element)` is called. It always return true or perhaps(unlikely) throws an exception. But the result of `element.isDisplayed()` is meaningless because `check.apply(element)` returns true then. If the element  hadn't existed, an exception would have already been thrown in `element = getWebElement();` as I had said above.
- my conclusion to `should(exist) `: it doesn't matter on the result of `element.isDisplayed()` in condition's `apply(...)` method.

I guess it's merely cosmetic matter (as long as I'm right of course). But now the important thing comes.

for shouldNot(exist): `element = getWebElement();` throws an exception if the element hasn't been found
- that means that WebElementSource's `checkCondition(...) ` never returns a value. It always throws an exception in each run until timeout expires.
- my point is to catch those exceptions and return `null` if the element cannot be found because I want to escape do-while in SelenideElementProxy's `dispatchAndRetry(...)`. I don't want to reach timeout and let the test fail.


If there is something unclear or I'm wrong in something, I'm willing to discus it further.

Thanks a lot. Selenide is awesome :)

Martin

**Comment by asolntsev** [comment]
@mastepan Hi Martin!
Sorry for the long response. :(

What Selenide version you are talking about? 
I just have tried to execute `$("#unexisting").shouldNot(exist);`, and it runs with 40ms. It doesn't wait for timeout.

Method `WebElementSource.checkCondition()` returns immediately due to these lines:

```java
    if (element == null) {   // element was not found
      if (!check.applyNull()) {   // this condition (exist) accepts missing elements
        throw createElementNotFoundError(check, lastError);
      }
    }
    ...
   return null; // here we exit 
```

It understands that element doesn't exist, but it's ok for condition `exist`. 
Are you sure you still have the problem?

**Comment by mastepan** [comment]
@asolntsev Hi Andrei, 
I'm using 3.3 version. But the problem is solved. The code is allright.
That was all my bad I hadn't noticed a coincidence. I have checked one element that was supposed not to exist. The test loaded following page then. There was unexpectedly one element that was found using exactly the same xpath... uf.. Those 2 elements were absolutely unrelated.

Thank you for cooperation and keep going! I look forward to the future Selenide releases :)

Martin

**Comment by abondarev-sel** [comment]
@asolntsev Hi Andrei,
I have reproduced the same issue on version 4.0 in a different way. I am using Selenide with testNG. The following code is failing:

```
...
@FindBy(xpath = ".//button[@data-btname='close']")
private WebElement closeButton;
@FindBy(xpath = ".//button[@data-btname='form_help']")
private WebElement helpButton;
...
$(helpButton).shouldBe(visible);
$(closeButton).click();
$(helpButton).shouldNot(exist);
...
```
However if I just replace it with new By.xpath it's working correctly
```
$(helpButton).shouldBe(visible);
$(closeButton).click();
$(By.xpath(".//button[@data-btname='form_help']")).shouldNot(exist);
```
Is it some bug or I am just doing it wrong.

**Comment by asolntsev** [comment]
@abondarev-sel Sorry for the long delay.
It's not a bug. You are doing it wrong. :)

With Selenide you don't need to to declare `WebElement` and then wrap it with `$`. 
Because the original `WebElement` disappears at the moment of check. Selenide does solve `StaleElementException`, but you should you Selenide APIs.

Just simplify your code. For example, like this:

```java
private By closeButton = By.xpath(".//button[@data-btname='close']");
private By helpButton = By.xpath(".//button[@data-btname='form_help']");
..
$(helpButton).shouldBe(visible);
$(closeButton).click();
$(helpButton).shouldNot(exist);
```

**Comment by abondarev-sel** [comment]
@asolntsev Hi Andrei,
Thank you for your answer. I will use this approach.

**Comment by natesun1** [comment]
I just have tried to execute $("#unexisting").shouldNot(exist);, and it runs with 40ms. It doesn't wait for timeout. -- is there any method we can use to validate an element not exist but not get exception? For instance, if a table returns 0 row then there is no table structure on the page, if we use shouldNot(exist) it directly goes to exception because the table does not exist anymore, what is the best method to use here?

**Comment by asolntsev** [comment]
@natesun1 Sorry, I am not sure I understand your question correctly. It's always a good idea to given some html and Java code sample. You can use https://gist.github.com/ for sharing code snippets.

If you have a table with 0 rows, you can use something like this:

```java
  $("table").should(exist);
  $("table tr").shouldNot(exist);
```

**Comment by natesun1** [comment]
@asolntsev sorry wasn't very clear. So yes but in some application, if there is 0 row there will not be table//tr//td etc at all, it's just gone. And only when there is at least one row there is table structure on the page. In case there is no row returned if we use 

  $("table").shouldNot(exist);
it would immediately throw an NoSuchElementException, as I assumed earlier shouldNot(exit) should handle exception?

**Comment by asolntsev** [comment]
@natesun1 No. 
If 
* there is no any `<table>` elements on a page
then
* command `$("table tr").shouldNot(exist)` will NOT throw any exceptions.
