### ISSUE TITLE
How to take screenshot only for failling tests

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#301]
I capture screenshot after my test condition.
either the test is failed or successful the screenshot is captured, but it saved with the pre-specified name for the successful test, however, the failed test with other names.

Please, how can I capture and save this shot for only the failed test?

**Comment by RomanIsko** [comment]
```java
    @Rule
    public ScreenShooter makeScreenshotOnFailure = ScreenShooter.failedTests();
```
[More info here](https://github.com/codeborne/selenide/wiki/Selenide-vs-Selenium#selenide-13)

**Comment by asolntsev** [comment]
@hana9090 @RomanIsko it's default behavior of Selenide. Selenide does take screenshots only on failing tests by default. You even don't need to use any annotations for this.

**Comment by hana9090** [comment]
Thanks RomanIsko, and Andrei.
but how to customize the folder and name of the screenshots?
And how to know in the code side if the test is falling? then we can make some actions.

**Comment by hana9090** [comment]
I meant for screenshots that generated by default falling tests

**Comment by hana9090** [comment]
Hi,
I used this from Selenide like the following:
```
@Rule
    public ScreenShooter makeScreenshotOnFailure = ScreenShooter.failedTests();
```

it worked well for capturing failing test, but still I can't change the name of the generated image.

However, I used the following to customize snapshot name:

```
@Rule
public TestRule testWatcher = new TestWatcher() {
  @Override
  public void failed(Throwable e, Description test){
      File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
      String currentDir = System.getProperty("user.dir");
      String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
      try {
          FileUtils.copyFile(scrFile, new File(currentDir + "\\screenshots\\" + test.getMethodName() + timeStamp + ".png"));
      } catch (IOException e1) {
          e1.printStackTrace();
      }
  }
};
```

But in this case, I have two snapshots generated form both this method and the default Selenide configuration.

So how to use the selenide option OR how to turn screenshot of Selenide off.

Thanks in advance

**Comment by JasonTolotta** [comment]
@hana9090
Selenide Report is handling screenshots on failure.

**Reference:** `com.codeborne.selenide.Configuration`

Set `Configuration.screenshots = false;` in the TestWatcher `starting()` method.

**Comment by asolntsev** [comment]
@hana9090 Is the question still valid? Can we close the issue?

**Comment by hana9090** [comment]
@asolntsev 
You can close it.
