### ISSUE TITLE
Selenide must throw error if soft assert is used without annotation

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#302]
For example, this test doesn't fail:

```java
@test(description = "test")
public void test() throws Exception{
    System.out.println("Test started");
    try {
        Configuration.assertionMode = Configuration.AssertionMode.SOFT;
        $"#record_text_area").shouldHave(Condition.value("texts is changed!"));
        $"#record_text_area").shouldHave(Condition.value("users is changed!"));
    } catch (Exception e) {
        throw e;
    } finally {
        Configuration.assertionMode = Configuration.AssertionMode.STRICT;
        System.out.println("Test finished");
    }
}
```

But it should. See Selenide report:
```
Test started
+--------------------+----------------------------------------------------------------------+----------+----------+
|Element             |Subject                                                               |Status    |ms.       |
+--------------------+----------------------------------------------------------------------+----------+----------+
|#record_text_area   |should have(value 'texts is changed!')                                |FAIL      |4092      |
|#record_text_area   |should have(value 'users is changed!')                                |PASS      |28        |
+--------------------+----------------------------------------------------------------------+----------+----------+
Test finished
```

The problem is that annotation/listener is not added to the test (SoftAssert listener).

**Comment by asolntsev** [comment]
Now Selenide throws an exception in this case:

```java
java.lang.IllegalStateException: Using soft asserts, but without @SoftAsserts annotation
	at com.codeborne.selenide.logevents.ErrorsCollector.validateAssertionMode(ErrorsCollector.java:45)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:55)
	at com.sun.proxy.$Proxy10.shouldHave(Unknown Source)
```

or, for collections:

```java
java.lang.IllegalStateException: Using soft asserts, but without @SoftAsserts annotation

	at com.codeborne.selenide.logevents.ErrorsCollector.validateAssertionMode(ErrorsCollector.java:45)
	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:54)
	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:50)
```

**Comment by jasw** [comment]
Seen this exact error in 4.0 when upgrading from 3.5.1.  Is it a known issue? Will try 3.8.

**Comment by asolntsev** [comment]
@jasw What error did you see? Do you mean `IllegalStateException: Using soft asserts, but without @SoftAsserts annotation`?

If yes, this is expected behaviour. Selenide should throw this error. You need to add `@SoftAsserts` (for JUnit) or `SoftAsserts` listener (for TestNG).

**Comment by jasw** [comment]
Thanks Andrei. Do I need any other dependencies to get such annotation? The
only SoftAsserts I can see in selenide is a class not a annotation.

Regards

**Comment by asolntsev** [comment]
@jasw Sorry for the long delay. 

See http://selenide.org/2015/05/05/selenide-2.16-and-2.17/

1. To enable Soft asserts in JUnit (see example):

```java
public class SoftAssertJUnitTest {
  @Rule public SoftAsserts softAsserts = new SoftAsserts();
```

2. To enable Soft asserts in TestNG (see. example):

```java
@Listeners(SoftAsserts.class)
public class SoftAssertTestNGTest {
```

**Comment by karol1204** [comment]
> To enable Soft asserts in JUnit (see example):
> public class SoftAssertJUnitTest {
>   @Rule public SoftAsserts softAsserts = new SoftAsserts();

It works for jUnit4, how to use it for jUnit5?

**Comment by rosolko** [comment]
https://github.com/codeborne/selenide/wiki/SoftAssertions

**Comment by LukasBola** [comment]
Is possible to run SoftAssert with cucumber-testng in BDD testing?

**Comment by asolntsev** [comment]
@LukasBola It's definitely possible with TestNG. Not sure about Cucumber. 
Have you tried it by yourself?

**Comment by LukasBola** [comment]
@asolntsev Thank's for your message.  
Yes, I have tried it by myself with cucumber and unfortunately I get  java.lang.IllegalStateException: Using soft asserts, but without @SoftAsserts annotation. 
I have tried it with TestNG (clean TestNG without cucumber ) and it works perfectly.
I will try again with cucumber-testng, and I'll see, maybe I'll figure out something.
