### ISSUE TITLE
Check checkboxes that are display false

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#305]
Selenide checks by default if an element is displayed and than he flags it. 

i have a situation that i want to flag a checkbox but it does not get flagged because display class is false.

Below a code snipped
 ```Html 
<div class="checkbox">
<input id="wmformfragment_checkbox_vertical_item1" class="form-control" type="checkbox" value="item1" name="checkbox_vertical"/>
<label id="wmcheckboxlabel_checkbox_vertical_item1" class="" for="wmformfragment_checkbox_vertical_item1">                 Waarde 1              </label>
</div>
<div class="checkbox">
<input id="wmformfragment_checkbox_vertical_item2" class="form-control" type="checkbox" value="item2" name="checkbox_vertical"/>
<label id="wmcheckboxlabel_checkbox_vertical_item2" class="" for="wmformfragment_checkbox_vertical_item2">                 Waarde 2              </label>
</div>
 ```
If i do this:
 ```Java 
`$$(".checkbox").get(1).setSelected(true);`
```
It works. But i don't want to use index because it's only unieke per page

If i do this :
   ```Java 
$(".checkbox` input[id$=\"checkbox_vertical_item1\"]").setSelected(true);
```
It does not work. Selenide gives this error message:
 ```Java 
Element should be visible {.checkbox input[id$="checkbox_vertical_item1"]}
Element: '<input class="form-control" id="wmformfragment_checkbox_vertical_item1" name="checkbox_vertical" type="checkbox" value="item1" displayed:false></input>'
```

Is there a way to flag an element with dislay class on false using Selenide?

**Comment by asolntsev** [comment]
@thasherwin Do I correctly understand that you want to check invisible checkbox?
I think it's a wrong idea. Test should emulate real user's behaviour. User cannot check hidden checkbox, so test should not too.

**Comment by thasherwin** [comment]
For the user that does not look at the code  it is visable. I can manually flag the checkbox with no problem. Using Selenide i can do this with the class checkbox but to make it unieke i need the other html part which has display false. So not  visable. Selenide  fails because the other part has display false property. Also i think that the developers created bad html. If there is no way i need to use a workaround to click on the element using an id.

**Comment by vinogradoff** [comment]
You probably has some issues with layers or looking at different element. If displayed=false the n element cannot be visible. Browser-bug if it is. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by thasherwin** [comment]
Okay. I will create a work-around solution for this. So i am closing this issue.
