### ISSUE TITLE
Selenide closes alert automatically in IE 11

### ISSUE THREAD

**Issue by leslyarun** [codeborne/selenide#307]
Whenever I run tests in IE11, Selenide automatically closes all alerts in IE11 without any explicit configuration. I used to run test scripts with NativeEvents = false for IE11. 
Any idea, why it behaves like this ?

**Comment by asolntsev** [comment]
Selenide suppresses all `alert` and `confirm` dialogs **if** you configured `selenide.dismissModalDialogs` system property. Otherwise, alerts should work as usual.

**Comment by leslyarun** [comment]
I didn't set any configuration. I'm using the default setting.
I tried to explicitly set dismissModalDialogs to false, but still it's
behaving the same. Alerts are dismissed automatically

Regards,
Lesly Arun Franco

**Comment by asolntsev** [comment]
@leslyarun sorry for the long delay.
I havn't experimented with this issue - partly because I don't like Windows. :)

Is the problem still actual?

**Comment by simple-elf** [comment]
@leslyarun do you mean alert for BasicAuth?

**Comment by asolntsev** [comment]
It seems no feedback here. Closing the issue.
