### ISSUE TITLE
Selenide seems to not wait until some head elements are ready

### ISSUE THREAD

**Issue by jammie27** [codeborne/selenide#311]
I tried to write a simple test to check some elements (Firefox Driver, Windows 7).

```
    public void testSize(){

        open("https://www.point-rouge.de");
        //SelenideElement description = $$("meta").findBy(name("description")); //if i comment these lines, i can't find any alternates

        //String descriptionContent = description.getAttribute("content"); //if i uncomment these lines, i can see link alternate


        ElementsCollection alternates = $$("head link").filterBy(attribute("rel", "alternate"));


        int k = 0;
        for(SelenideElement alternate : alternates){
            System.out.println(k);
           // System.out.println(alternate.getAttribute("hreflang"));
           // System.out.println(alternate.getAttribute("href"));

            k++;
        }
        System.out.println("alternates size - counter");
        System.out.println(k);

        int alternatesCount = alternates.size();
        System.out.println("alternates size");
        System.out.println(alternatesCount);




        alternates.shouldHaveSize(0);

        System.out.println("size 0?");

    }

```

If i comment two lines above, that have nothing to do with search for alternates (in these lines i search for meta description and fill the variable with the value of attribute content), i can't find any alternates although one alternate definitely exists (and the test passes). If i uncomment these lines, i can find one alternate (and the test fails).
Do you have any possible explanations for this behaviour?

Best regards,
Elena Geller,
Shopboost GmbH

**Comment by asolntsev** [comment]
@jammie27 Thank you for such a detailed explanation and code sample!

Is the problem still actual?
For me, it works a bit differently compared to your explanation.

Anyway, when you iterate a collection, Selenide doesn't know if it should wait for something or not.
If the collection is not loaded yet, Selenide doesn't wait for anything and reports that collection is empty.

You probably need to write some expectations for the collection. For example, you could check the collection size:

```java
alternates.shouldHave(sizeGreaterThan(0));
```

In this case Selenide will wait until the collection is loaded.

**Comment by asolntsev** [comment]
@jammie27 Can we close the issue?

**Comment by asolntsev** [comment]
It seems no feedback here. Closing the issue.
