### ISSUE TITLE
Customize selection for collection of elements - Selenide

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#312]
How can I select the on of element, and this element contains a collection of elements, How can I select or pass through this element's collection? 

- the default search method `WebDriverRunner.getWebDriver().findElements(By.tagName("*")); `
is `$$("*")`
they consider that default space to search is the whole document, how can I specify the region to search? Assume that I need the **a** tags from the region or from specific element.

I have the following schema for my page:

      <div class="class1"> 
         <a href=""  />
         <a href=""  />
         <img src="img.png" /> 
      </div>
      <a href=""  />
      <a href=""  />
      <div class="class2"> 
         <a href=""  />
         <div class="class4"> <div>
       </div>
      

How can I pass all elements of **div class="class1"**, ex: after select **div.class1** element, I need to see all elements inside this **div**.

**Comment by vinogradoff** [comment]
$("div.class1").$$("*");

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by hana9090** [comment]
Thanks @vinogradoff , please could you see the following issue?
But I tried the following and I feel that it is something going wrong.
I have this html:
![image](https://cloud.githubusercontent.com/assets/2920520/14311986/d82f3d12-fbf2-11e5-920f-82e1e2fa5e80.png)


I write this code, but it is not able to find the element inside the base element.

[List<SelenideElement> collection = new ArrayList<>();
			
			for (SelenideElement div_categ : $$("div.btn-group")) {
				collection.add(div_categ);			
			}
			
			
			for (SelenideElement div_c : collection) {
				
			    SelenideElement el= div_c.$("a.btn.dropdown-toggle");
				out.println("> "+java.net.URLDecoder.decode(el.attr("href"), "UTF-8") );
				
				for (SelenideElement div_cx : div_c.$$("*")) {
					out.println("> "+div_cx.getTagName());
				}
		
			}

**Comment by asolntsev** [comment]
Thanks @vinogradoff !
So, closing the issue?
