### ISSUE TITLE
How to tell Selenide to create a substitute link once a test fails

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#316]
This is more like a question and not an issue:
How to make Selenide create a substitute link to the screenshot when a test fail?

For example if my test fail in Jenkins i don't see a substitute link. I only a see path location where the screenshot is saved. 

Screenshot: file:/var/lib/jenkins/jobs/....../build/reports/tests/1460730661171.1.png

**Comment by vinogradoff** [comment]
You can try setting -Dselenide.reportsUrl=http://jenkinshost/path

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by thasherwin** [comment]
thanks for the quick reply. I will look into this tomorrow.

**Comment by thasherwin** [comment]
i will close this question. I did not had time to check yet. I will try to do this later this week.

**Comment by anyone-can-test** [comment]
It works. 
-Dselenide.reportsUrl=${JOB_URL}${BUILD_NUMBER}/artifact/

**Comment by anyone-can-test** [comment]
My build.gradle

if(project.hasProperty("jenkins") == true) {
    systemProperty "parallel", "yes"
    systemProperty "selenide.timeout", 10000
    systemProperty "selenide.browser", "xxxx"

    // It does not work.
    //systemProperty "selenide.reportsUrl", "${JOB_URL}${BUILD_NUMBER}/artifact/"

    def job_url = System.getenv("JOB_URL") as String ?: ""
    println "job url: " + job_url
    def build_number = System.getenv("BUILD_NUMBER") as String ?: ""
    systemProperty "selenide.reportsUrl", job_url + build_number + "/artifact/"
  }
