### ISSUE TITLE
[Question] How can I set the property in java code?

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#323]
Great tool !
Two questions:
1.As title, How can I get and set the property in java code below ?
timeout - (String) can be changed in runtime
browser (e.g. chrome, ie, firefox)
baseUrl
reportsFolder

2. How can I set the $ method(find element method) timeout in java code?

**Comment by thasherwin** [comment]
For example: Configuration.timeout = 8000;

**Comment by vinogradoff** [comment]
2. $(...).waitUntil(visible, 12000)

12000 - custom timout just for that $

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by yisake** [comment]
Many thanks for the quick answer, have a good day~~

**Comment by yisake** [comment]
@vinogradoff Can I set the timeout in the Configuration or somewhere?

**Comment by vinogradoff** [comment]
Configuration.timeout is a global one for all your tests in the suite. You can reset it any time but the most appropriate is in setup Methods or even as system property from test runner - -Dselenide.timeout=...

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by yisake** [comment]
@vinogradoff How can I set the system property? Could you give me an example? 

As I see description the in the selenide website.
**You can also pass the configuration parameters in as system properties to make use of CI Jobs (e.g. -Dselenide.baseUrl=http://staging-server.com/start)**

How can I set or get the system properties in CI job as Jenkins? 
I can not find the property in System.getenv(); or System.getProperties();

**Comment by vinogradoff** [comment]
Jenkins just manages the jobs, how do you run your tests? Maven? Gradle? Pure Java?

Put -D... there

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by yisake** [comment]
@vinogrado  I use maven test to trigger the test. So I should enter the command with "mvn test -Dselenide.timeout=8000" ?

**Comment by asolntsev** [comment]
@yisake Yes, one option is to write "mvn test -Dselenide.timeout=8000".
Another option is to set system property in `pom.xml`:

```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.19.1</version>
        <configuration>
          <systemProperties>
            <property>
              <name>selenide.timeout</name>
              <value>8000</value>
            </property>
          </systemProperties>
        </configuration>
      </plugin>
```
