### ISSUE TITLE
Perform some action when transitioning to a new page (e.g., calling page(...))

### ISSUE THREAD

**Issue by kenston** [codeborne/selenide#325]
Is it possible for us to perform some actions like taking screenshot or writing to logs when we transition from one page to another by calling Selenide.page(...) or when a new URL is detected?

I'm thinking of allowing us to specify some strategy implementation that can be configured using the Configuration class.

**Comment by vinogradoff** [comment]
I don't know if it is a good idea. Nowadays you dont really have pages or url in your app most of the time. 
I mean "one page apps" and changing pages staying with same url or changing a bit of a page. 
Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by asolntsev** [comment]
@kenston I am not sure it's technically possible. I am afraid that Selenium webdriver protocol doesn't have feature of detecting a new URL.

But nowdays applications can change the entire page content without changing URL (like @vinogradoff  mentioned). This is Ajax. 
You never know if ajax has modified just a little pixel or the entire page. 

What do you actualt want to achieve?

**Comment by kenston** [comment]
@vinogradoff @asolntsev, thanks for the response. I think targeting the page(...) method should be enough for me instead of looking at changes in URL.

I'm thinking if we can log some statement or take some screenshot whenever we switch from one page to another. This is to give us some records of the transitions/executions made (e.g., successful flow). We use the page object model, so we usually call Selenide.page(...) method.

**Comment by asolntsev** [comment]
Yes, Selenide actually does log every time when it navigates to a new page using method `open` or `page`. But it's not enough: any click, or any other operation potentially can navigate to a new page. Or re-render part of page, or even the entire page. We just cannot detect it generally.

**Comment by kenston** [comment]
Is it possible for us to add some interceptor or strategy impl for those methods?

**Comment by kenston** [comment]
I am able to implement a solution on this one without having to ask for modifications in the core Selenide code. Thanks for the initial answers.
