### ISSUE TITLE
[Question] Could selenide retry the test case in testng?

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#326]
As known, selenide can screenshot after test case failed in Testng. Could selenide run the failed test case again automatic? ^_^

**Comment by dimand58** [comment]
@yisake you can use TestNG retry listener (I think JUnit have same feature too)

**Comment by asolntsev** [comment]
@yisake We could create something like that, but it seems that it's not a purpose of Selenide.
So I suggest not doing that in Selenide.

**Comment by yisake** [comment]
@dimand58 @asolntsev Many thanks. Have a good day!

**Comment by asolntsev** [comment]
@yisake can we close the issue?

**Comment by asolntsev** [comment]
No reaction. Closing the issue.
