### ISSUE TITLE
[Question] How can selenide switch to the new window or new tab in browser?

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#328]
As title, if a new window appear after click a web element ? How can I switch to the new window or new tab in browser?

**Comment by anilreddy** [comment]
You can do it multiple ways:

```java
import static com.codeborne.selenide.Selenide.*;

// by index
switchTo().window(1);

// by name or title or handle
switchTo().window("Title of the window");

// for switching to default window
switchTo().defaultContent();
```

**Comment by asolntsev** [comment]
@anilreddy Thank for the answer!
@yisake exactly, use switchTo() method.

**Comment by yisake** [comment]
@anilreddy Many thanks.
@asolntsev I think many people like me are new to selenide need **more example** with  many detail for selenide. ~~

**Comment by asolntsev** [comment]
@yisake Absolutely agree! Good point!
Don't you want to help us? 
Source of selenide.org is also in github.com/codeborne/selenide, but in branch "gh-pages".
Feel free to send pull requests there!

**Comment by thasherwin** [comment]
just wanted to say that when I started to use Selenide i had the same problem. When I found out that there are lots of examples at https://github.com/codeborne/selenide/tree/master/src/test/java/integration testing, everything  became much easier. Please look at those examples if you are not doing it already

**Comment by asolntsev** [comment]
@thasherwin Good point, thank you!

**Comment by Cotola** [comment]
Hi, Andrei (@asolntsev)!
    I have just start to use this very helpful library and really love it, Thank you very much for sharing it. 
    I have seen your videos in youtube about using the library and read most of main pages at project website too. I read and try to use eclipse IDE "code proposals" to start creating tests and realise that to use them they ALL should to be to imported to the test (java) file. Being a newbie I should to ask a question. Is there a selenide libraries FULL list to be imported in the tests or there is another better way to get code (suggestions) proposals? 
List should look like this:
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.CollectionCondition.size;
import static com.codeborne.selenide.Condition.appear;
import static com.codeborne.selenide.Condition.appears;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Condition.attribute;
import static com.codeborne.selenide.Condition.cssClass;
import static com.codeborne.selenide.Condition.hidden;
import static com.codeborne.selenide.Condition.disappear;
import static com.codeborne.selenide.Condition.disappears;
import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Condition.value;
import static com.codeborne.selenide.Condition.exist;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$$;
import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.screenshot;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.WebDriverRunner.*;
import com.codeborne.selenide.WebDriverRunner;
import com.codeborne.selenide.*;

Thank you for an answer in advance.
P.S. I saw the selenium 3.2 was published out there. Selenide maven repository uses the lower version 3.0.1 right now.

**Comment by anilreddy** [comment]
@Cotola you can use like above or can use like this:
```java
// here '*' imports all static methods in that class
import static com.codeborne.selenide.Selenide.*;

import static com.codeborne.selenide.Condition.*;
```

**Comment by Cotola** [comment]
Thank you @anilreddy!
Sorry in my comments asterisk was not shown properly.

These two lines you mention don't cover com.codeborne.selenide.CollectionCondition.size method.

**Comment by anilreddy** [comment]
@Cotola I have just gave you 2 examples.

**Comment by Cotola** [comment]
Thank you! 
I see that I need more Java core and eclipse knowledge. :)

**Comment by NickMeert-dev** [comment]
i can't seem to switch to an angular MatDialog, does someone know how?

**Comment by anilreddy** [comment]
@NickMeert-dev can you share the example so that I can help you with that.
