### ISSUE TITLE
I would like to be able to write $$(".smth").shouldBe(visible)

### ISSUE THREAD

**Issue by iNikem** [codeborne/selenide#33]
To check that all returned elements are visible

**Comment by yashaka** [comment]
I believe the 
```
shouldEach
shouldEachBe
shouldEachHave
```
option will be better because 
the ```.each().``` option will destroy the logic in chaining, i.e. we expect that each SelenideElement#method will return SelenideElement
and each ElementCollection#method will return ElementCollection.
But here the chain will be broken without any understandable logic IMHO...

**Comment by dmak** [comment]
I vote for this issue. My comment to above: what about `$$(..).allShouldBe(condition)` (meaning "any element should confirm the condition") and `$$(..).anyShouldBe(condition)` (there is some element that confirms the condition) ?

**Comment by asolntsev** [comment]
@dmak Yes, it's possible. I was thinking about `$$().each().shouldBe(condition)` and `$$().any().shouldBe(empty)`. 

But
is it good idea? What if you write `$$("tr"). allShouldBe(visible)`, and today your test works. But after some months designer or developers will add one more **invisible** row? This row will break your tests, but it will not break the application.

**Comment by dmak** [comment]
I understand your concern. On the other hand there is already `CollectionCondition.exactTexts()` which will suffer from the same problem: once element is hidden it will not have any visible text, hence the condition will fail.

I have also looked up all occurrences of `$$` in my project and I would say that the given extension will not help me much, as in almost all cases the check to be applied on each element is so exotic that it cannot be expressed as `each().shouldBe(condition)`. But the community could be very interested in the given feature, just to make the code shorter (without loops) and easier for understanding.

**Comment by yashaka** [comment]
Guys, what about just creating "each" condition?
So you can write e.g.:

$$.shouldHave(each(cssClass("active"));
$$.shouldBe(each(visible));

So far this is just an idea, but seems like there is should not be any problem in implementing it, shouldn't it?

**Comment by asolntsev** [comment]
Cool idea!
Yes, I believe it really would be easier to implement condition "each". I
will try it.

Andrei Solntsev

2015-10-14 15:06 GMT+03:00 yashaka <notifications@github.com>:

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
