### ISSUE TITLE
[Question] How can I open firefox with config profile with selenide

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#330]
As selenium could open with private config profile with code below, How does selenide deal with this？

 1     public static void StartLocalFirefox(){
 2         System.out.println("start firefox browser...");
 3         System.setProperty("webdriver.firefox.bin", 
 4                 "D:/Program Files/Mozilla Firefox/firefox.exe");
 5         ProfilesIni pi = new ProfilesIni();
 6         FirefoxProfile profile = pi.getProfile("default");
 7         WebDriver driver = new FirefoxDriver(profile);
 8         driver.get("http://www.baidu.com/");
 9         System.out.println("start firefox browser succeed...");    
10     }

**Comment by anilreddy** [comment]
@yisake as you wrote in selenium the same way it was used in selenide as well check it.

```java
import static com.codeborne.selenide.Configuration.baseUrl;
import static com.codeborne.selenide.Selenide.*;

public class SampleTest {
	
	WebDriver driver;
	
	public void browserConfig() {
		baseUrl = "http://www.baidu.com/";
		System.setProperty("webdriver.firefox.bin", "path to the custom profile for firefox browser");
		ProfilesIni profilesIni = new ProfilesIni();
		FirefoxProfile firefoxProfile = profilesIni.getProfile("default");
		driver = new FirefoxDriver(firefoxProfile);
		WebDriverRunner.setWebDriver(driver);
		open(baseUrl);
		System.out.println("Launching Firefox..!!");
	}
}
```

**Comment by yisake** [comment]
@anilreddy  Many thanks for your kindly answer. Have a good day.

**Comment by asolntsev** [comment]
anilreddy Thank you for the answer!

@yisake closing the issue...
