### ISSUE TITLE
Can we wait safely without throwing exceptions/creating screenshots?

### ISSUE THREAD

**Issue by kenston** [codeborne/selenide#331]
I have this code block that waits for an element to appear and returns true if does exist; otherwise, it will just return false.

```java
private boolean isDisplayed(SelenideElement e) {
    try { 
        e.waitUntil(appear, 7000); //Cannot use e.exists() as I need some waiting?
        return true;
    } catch (Throwable ignore) {
       return false;
    }
}
```

The above code works except that it throws `UIAssertionErrors` which I can just catch; however, it also implicitly creates a screenshot. Can we wait for some conditions safely without having to catch exceptions and/or generating screenshots?

**Comment by admizh** [comment]
@kenston try it (Java 8):
```java
private boolean isDisplayed(SelenideElement e) {
        try {
            Predicate<WebDriver> isAppear = condition -> e.is(appear);
            Selenide.Wait()
                    .withTimeout(7, TimeUnit.SECONDS)
                    .until(isAppear);
            return true;
        } catch (TimeoutException th) {
            return false;
        }
    }
```

**Comment by asolntsev** [comment]
@kenston Yes, you can use code provided by admizh.
But it's probably a bad idea because this method can be very slow. If the element does not exist, your method `isDisplayed()` will always work 7 seconds. It incredibly slow, isn't it?

Moreovery, using any IFs or loops in tests is bad practice. That's why you should not need method that returns boolean.

I recommend checking another condition that you know must be true. Something like `$().shouldBe(visible)` or `$().shouldHave(text(..))`.

**Comment by kenston** [comment]
Thanks, @admizh, the snippet works for me.

@asolntsev, I agree that the approach is not recommended in general.

Is it correct to say that $().exists and $().isDisplayed() does almost the same thing except that it does not do waiting?

**Comment by asolntsev** [comment]
@kenston no. Both $().exists() and $().isDisplayed() do NOT wait. "Exists" means that element can be visible or invisible. "Displays" means that element exists and is visible.

**Comment by kenston** [comment]
Thanks @asolntsev for the answer and for your team's development of Selenide!

**Comment by kenston** [comment]
Just a follow-up question, is $().isDisplayed() similar to $().is(visible) except that the latter offers waiting?

**Comment by asolntsev** [comment]
Hi @kenston!
No, I guess `$().isDisplayed()` and `$().is(visible)` have exactly the same effect.
