### ISSUE TITLE
[Question] How can I separate the locate element method and test case in different java files?

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#334]
As title, I wrote the static locate element method in a java file(as $(By.cssSelector("[class=\"city-selected\"]")).

Now I use the **static locate element method** as $ in another java file( Define test case in this file). But the static method can not locate the element as normally. How can I solve this?

**a.java**
public class SellHousePage {
	
	public static SelenideElement getCitySelectedElement ( ) {
		return $(By.cssSelector("\"city-selected\""));
	}
	
}

**testcase.java**
import static a.java.*;
@Test 
public void test () {
    Assert.assertEqual(getCitySelectedElement().text(),"test");
}

**Comment by thasherwin** [comment]
Uhm. You need to use page objects., See below example
http://selenide.org/documentation/page-objects.html

**Comment by asolntsev** [comment]
@yisake It's very easy. Instead of 

```java
Assert.assertEqual(getCitySelectedElement().text(),"test");
```

you just need to write:

```java
getCitySelectedElement().shouldHave(text("test"));
```
