### ISSUE TITLE
Regression in collection iterator

### ISSUE THREAD

**Issue by auke-** [codeborne/selenide#337]
We are using Selenide for a couple of months now to write tests for our GWT Bootstrap web application, which works very well! Unfortunately, we ran into a regression after upgrading Selenide from version 3.2 to 3.5.1. The behavior of the ElementsCollection, or at least its Iterator, has changed in version 3.3. This makes it impossible to get a list of elements, iterate over the list and invoke an action on the elements which makes them disappear one by one.

The following tests demonstrates the behavior. It succeeds in Selenide 3.2 and fails in 3.3 (or 3.5.1):
```java
import static com.codeborne.selenide.CollectionCondition.*;
import static com.codeborne.selenide.Selenide.*;
import static org.junit.Assert.*;
import org.junit.Test;
import com.codeborne.selenide.SelenideElement;

public class CollectionIteratorTest {


    @Test
    public void removeAlerts() {
        open("http://getbootstrap.com/javascript/#alerts");

        String alerts = "div.bs-example.bs-example-standalone > div.alert";

        // We expect 2 alerts
        $$(alerts).shouldHaveSize(2);

        int count = 0;
        for (SelenideElement alert : $$(alerts)) {
            count++;

            // Click the close button, which removes the alert from the html
            alert.$("button.close").click();

            // Here we normally do something to check if the alert is closed,
            // but just wait 1 second for the sake of the example.
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {}
        }

        // We should have removed 2 alerts
        assertEquals(2, count);

        // All alerts should have been gone...
        $$(alerts).shouldBe(empty);
    }

}
```

There is a simple workaround for this example, we could get the full lists of alerts every time we remove an alert. But imagine iterating over a table with a lot of rows and removing rows one by one based on some condition.

**Comment by asolntsev** [comment]
@auke- Wow, thank you for the code snippet. It always helps a lot.
I will take a lot at the problem.

**Comment by asolntsev** [comment]
@auke- It was change within issue #277 :
```
* #277 Ajax support for collections:
  Collection methods (operator $$) wait if collection elements get loaded asynchronously
```

This change has its own reason. The previous behaviour could cause `StaleElementException` in some cases. That's why the `$$` iterator now re-reads the collection elements on every call to `next`. This works well with collections that are loaded dynamically, so that new elements are added (or removed) to the end of collection.

But your case is different: elements are disappearing from the beginning of the collection. 
Hmm... It's not trivial... :(

Are you sure you want that test?
It actually can be simplified:

```java
while ($(alerts).isDisplayed()) {
  $(alerts).$("button.close").click();
  sleep(1000);
}
```

**Comment by auke-** [comment]
Thanks for the (compact and readable) alternative. I thought that would create a timeout (default 4 seconds) when the last alert is closed, but it doesn't.

The documentation for ElementsCollection indeed states that most selection and filtering methods don't trigger DOM searches and i understand why, but it still feels a bit strange from a java perspective to have a collection, an iterator and individual elements but the element can change as other elements in the collection disappear.

**Comment by asolntsev** [comment]
Yes, I agree: this iterator is a very strange. It's logically incorrect. It
was designed for case when new elements can arrive, but no elements can
disappear. I would like to refactor it. Do you have any ideas how to
implement it?
