### ISSUE TITLE
[Question] How can I switch to the new tab in script?

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#338]
I met a problem, I can not switch to the new tab with switchTo().window(1); method. 
I can not print all of the window-handle with code below. 

import static com.codeborne.selenide.WebDriverRunner.*;
		WebDriver driver = getWebDriver();
		System.out.println(driver.getWindowHandles());
		for (String win:driver.getWindowHandles()) {
			System.out.println(win.toString());
		}

1.How can I get the webdriver instance and print all of the window handle?
2.How can I switch to the new tab ?

**Comment by anilreddy** [comment]
@yisake 

Before answering your questions I want to tell you some thing i.e, this is a repo and here we log only defects and discussions on them. You can use [StackOverFlow](http://stackoverflow.com/questions/tagged/selenide) for asking questions and you can refer this [Selenide Cheat Sheet](https://gist.github.com/mkpythonanywhereblog/947633ba1bf0bc239639) for most of the methods.

**Your answers:**

1. 
```java
import static com.codeborne.selenide.WebDriverRunner.*
// for current window handle
String handle = getWebDriver().getWindowHandle();
// for all window handles
Set<String> handles = getWebDriver().getWindowHandles();
```
2. You mean to say browser tab or application tab for switching browser tab you can use
// for browser tabs
```java
Set<String> handles = getWebDriver().getWindowHandles();
List<String> tabs = new ArrayList<String>(handles);
switchTo().window(tabs.get(0));
getWebDriver().close();
switchTo().window(tabs.get(1));

// for application tab you can use xpath, css or any other tag attributes to click and switch.
```

**Comment by asolntsev** [comment]
@anilreddy Thank you for the answer! Good point, stackoverflow is a better place for questions/discussions.

@yisake did it help? Can you switch to tab now?

**Comment by asolntsev** [comment]
@yisake Can we close the issue now?

**Comment by yisake** [comment]
Of couse,thanks a lot.
