### ISSUE TITLE
ClassCastException - IE edge and javascript?

### ISSUE THREAD

**Issue by ken-p** [codeborne/selenide#339]
Hello - I'm getting our test suite working with IE Edge, and while a simple test completes (it does the actions in the UI), it fails at the end with:

java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List

	at com.codeborne.selenide.Selenide.getJavascriptErrors(Selenide.java:573)
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:66)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:59)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:67)
		
I did find one person on stackoverflow complaining about executing javascript on edge, but otherwise I couldn't find anything. Any ideas?

EDIT: This is on windows 10 build 10240. I'll try it on the latest preview release.

**Comment by asolntsev** [comment]
Ups. It seems that in Edge, this variable is Map, not List:

```java
window._selenide_jsErrors = [];
```

Hmm... We need to fix it somehow. 
I will try to download Edge browser and fix the issue.

**Comment by asolntsev** [comment]
@ken-p I hope I have fixed it. Thought, I didn't have a change to test it with real Edge browser. Can you try it with latest Selenide 3.8-SNAPSHOT?

**Comment by ken-p** [comment]
Finally got a chance to look into this. Yep, looks great. Thanks!!

**Comment by asolntsev** [comment]
@ken-p Good, thank you!
