### ISSUE TITLE
Searching with $() returns different element if the initial one has changed

### ISSUE THREAD

**Issue by grinderX19** [codeborne/selenide#34]
For example, clicking the button will change it's class from 'btn btn-primary btn-save' to 'btn btn-save'. 

I'm storing the button as SelenideElement to make checks later:

```
    SelenideElement bSave = $(".btn-primary.btn-save");
```

Now, following code

```
    SelenideElement bSave = $(".btn-primary.btn-save");
    System.out.println(bSave.getLocation());

    bSave.click();
    System.out.println(bSave.getLocation());

    Thread.sleep(5000);

    System.out.println(bSave.getLocation());
```

will return

```
    (1373, 365)
    (1373, 365)
    (1373, 549)
```

So "bSave" appears to be another button now. And the final check will fail:

```
    bSave.should(hasNotClass("btn-primary"));
```

PS: I was able to write the same without using $() in pure Selenium and WebElement and it worked.

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
