### ISSUE TITLE
selenide can not open a setting URL with open(firefox)

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#340]
As I want to set the firefox settings in browser. I need to enter the setting page with URL "about:preferences#general". But selenide add the http header to the URL. How can I resolve this?

*Error message:
org.openqa.selenium.WebDriverException: Target URL http://localhost:8080about:preferences#general is not well-formed.

**Comment by yisake** [comment]
I want to change the firefox setting and open with a page object.

**Comment by asolntsev** [comment]
@yisake Hm... Currently Selenide doesn't support it directly.
But you can do it using webdriver: 

```java
WebDriverRunner.getAndCheckWebDriver().navigate().to("about:preferences#general");
```
