### ISSUE TITLE
Disable image loading as configuration parameter

### ISSUE THREAD

**Issue by vasilevichra** [codeborne/selenide#342]
Hi!

It would be great if we could disable image loading by passing a parameter. For example:
com.codeborne.selenide.Configuration.disableImages = true

**Comment by asolntsev** [comment]
@vasilevichra hi!
1. Why this is good?
2. Doesn't it break functionality? (Probably some hidden elements get visible or visa versa)
3. How to implement it?

**Comment by vasilevichra** [comment]
1. If you need to increase test performance (knowing that disable of image loading will not affect the functionality)
2. I think that user should know it.
3. Example on JS for chrome
https://github.com/webdriverio/webdriverio/issues/1056

**Comment by JasonTolotta** [comment]
This sounds interesting.
Almost an edge case though, but I can see the benefit of testing sites on Chrome or other browsers that use plugins to prevent the loading of images to save bandwidth.

**Comment by asolntsev** [comment]
@vasilevichra Don't you want to create a pull request?

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
