### ISSUE TITLE
matchAttribute, matchClass and shouldMatch ?

### ISSUE THREAD

**Issue by vasilevichra** [codeborne/selenide#344]
Hi there!

Instead of writing huge css selectors like this:

`$$("[onclick*=submit]:not([name*=search]):not([class*=search]),[onclick*=subscribe]:not([name*=search]):not([class*=search]),[name*=submit]:not([name*=search]):not([class*=search])")`

I wanna write:

`$$("[onclick*=submit],[onclick*=subscribe],[name*=submit]")`
`.exclude(matchName("search"))`
`.exclude(matchClass("search"))`
`.exclude(matchAttribute("search")) // any attribute with matched substring`
`.exclude(matchAttribute("bla-attr", "search")) // the attribute with matched substring`

I have started to code this but I realized that I need an architect vision...

There are a lot of methods to work with text but the same can't be said about the classes or other attributes.

What methods should I extend?

Have a nice day!

**Comment by asolntsev** [comment]
@vasilevichra We have a performance problem with this approach.
1. When you write huge CSS selector, selenium webdriver executes ONE request to the browser. It's fast.
2. When you write `$$("css").exclude(C1).exclude(C2)` etc., webdriver will need to execute many requests:
   * load all elements matching `"css"`
   * iterate all elements, and check every one of them, probably executing a separate request for each element. 
As a result, we get the famous "N+1 select" problem.

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
