### ISSUE TITLE
Prevent Javascript in non-browser WD

### ISSUE THREAD

**Issue by dimand58** [codeborne/selenide#345]
*Problem*:
- Selenide have some methods which contains Javascript calls. If we use WebDriver API for non-browser application JS execution brokes target application (because it can't execute JS code)

*Example of Selenide method*:
- appendAllAttributes in Describe class

*Example of WD for non-browser app*:
- Marathon JavaDriver for Swing/JavaFX apps which can exec only custom Java code, not JS

**Comment by asolntsev** [comment]
Done in Selenide 3.7, will be released in few hours.
