### ISSUE TITLE
Difference between $("css selector") and $(By.linkText("text"))?

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#347]
I need to locate a element, I used the following two ways:

    $("body.c1 div.c1.c2.c3  div.c4   div.c.c7 ul.cc.c6.c8  li.LoginUrl a")
    		.click()

But I have problem with this way, because some CSS styles will change from time to time. So I switched to the following:

    $(By.linkText("login")).click()

Since login text is always will be appeared even changing in css style.

Problem: Some tests failed when using the second way, although it would have to do the same work as the first way. All tests worked well using first way.

***What is the difference between them?***

**htmL**

    <body class="c1">

    <div class="c1 c2 c3" id="f">
        <div class="c4">
     		<div class="c c7">
          		<ul class="cc c6 c8" id="x">
                	<li class="LoginUrl"><a href="url" onclick="$('#login').modal('show'); return false;">login</a></li>
             	</ul> 
         	</div>
        </div>
    </div>
</body>

**Comment by JasonTolotta** [comment]
You best bet is probably an XPath using the `onclick` attribute.

`$(By.xpath("//a[starts-with(@onclick, \"$('#login')\")]")).click();`

This has been tested.

**Java**
```java
public class TestDemo {
	@Test
	public void findLoginLink() {
		File file = new File("src/test/resources/test.html");
		Selenide.open("file:///" + file.getAbsolutePath());
		
		$(By.xpath("//a[starts-with(@onclick, \"$('#login')\")]")).should(Condition.exist);
		$(By.xpath("//a[starts-with(@onclick, \"$('#login')\")]")).click();
	}
}
```

**HTML**
```html
<html>
<body class="c1">

<div class="c1 c2 c3" id="f">
    <div class="c4">
        <div class="c c7">
            <ul class="cc c6 c8" id="x">
                <li class="LoginUrl"><a href="url" onclick="$('#login').modal('show'); return false;">login</a></li>
            </ul> 
        </div>
    </div>
</div>
</html>
```

**Comment by asolntsev** [comment]
@hana9090  `$("css selector")` searches by CSS selector, and `$(By.linkText("text"))` search by text. If link text never changes then the second way `$(By.linkText("login")).click()` is definitely better. 

If some tests fail, you need to analyze why they fail. Probably you have multiple links with the same text?

**Comment by hana9090** [comment]
@JasonTolotta 
Thanks
but  I got this error:

`Element should be visible {By.xpath: //a[starts-with(@onclick, "$('#loginModal')")]}`

**Comment by hana9090** [comment]
@asolntsev 
I checked if I have another same text, but I couldn't  see the same text.
but they are a combination from same text, such like: login new account, login special account and finally the login which we are searching for.

**Comment by JasonTolotta** [comment]
@hana9090 
The tag `a` has the attribute `onclick`

`onclick="$('#login').modal('show'); return false;"`

I noticed in the error that the XPath value it is trying to locate does not match, unless this element is in a different DOM structure.

**Error Message:** `Element should be visible {By.xpath: //a[starts-with(@onclick, "$('#loginModal')")]}`

**Note:** `$('#loginModal')` should be `$('#login').modal`

**Comment by asolntsev** [comment]
Hi Jason!
What is the final status? Is the issue resolved, or you still have the
problem?

**Comment by JasonTolotta** [comment]
@asolntsev 

I haven't got anything new from @hana9090 on this issue, so I would say this can be closed.

**Comment by asolntsev** [comment]
ok, closing the issue...
