### ISSUE TITLE
[Question] SetValue#execute() Should Do Nothing If Text is NULL

### ISSUE THREAD

**Issue by JasonTolotta** [codeborne/selenide#348]
I noticed with a lot of my test code that I was putting in a lot of boilerplate around the logic.

So if I had a method to complete a form with fields that were pre-populated, I had to prevent the entering of an empty string by enclosing the statement in an if-statement to check for NULL.

```
public void enterContactDetails(String firstName, String middleName, String lastName, String mobileNo, String email, String phoneNo) {
    if (firstName != null) {
        page.firstNameText.setValue(firstName);
    }
    ...
}
```
So why not create overloaded methods? It can be overkill when you have forms with mixed required and optional fields.

So if I did not need a middle name or phone number I would write.

`enterContactDetails("Adam", null, "Smith", "0412345678", "adam.smith@example.com", null);`

There is already a check for Empty String which should be enough.
When reading from a CSV file it is already known that a data state is NULL or Empty String.
I know Excel is a mixed bag when it comes to Java libraries.

Since the tests should be precise in theory (probably in practice dependent on environment and other third-party vendors) that state of the data between Empty String and NULL should be known prior.

Preferably, the `SetValue#execute()` with a text of NULL should do nothing to prevent stopping the chain.

Would like to hear some thoughts and opinions about this? Maybe I'm doing it wrong.

**Comment by asolntsev** [comment]
@JasonTolotta It doesn't seem to be good idea for me.
If I call `$().setValue("")` I expect that value must be set to "".
Otherwise it would be totally unexpected behaviour.

It seems that this request is your framework specific.
So the solution should also be in your framework. Probably you could have a special method `setValueIfNonEmpty()` in your framework.
