### ISSUE TITLE
[Question] HttpClient- Read all resources headers for all resources for entire page

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#351]
I need to check ETag from the header response of requesting URL.
I know that when request URL, then response will be html, css, js and images.

My issue: How to read header for all these resources including the html when requesting URL?

For `HttpClient` if you enter URL then it will give header and response only for html!! it didn't return the header for all loading resources which are involved with this URL and will be loaded associated with this URL.

if I request only **css**, then it will give me a right header response for this style.

```
HttpClient client = HttpClientBuilder.create().build();
            HttpGet request = new HttpGet("http://www.mkyong.com/wp-content/themes/mkyong/css/prism.css");

            HttpResponse response = client.execute(request);
            for (Header header : response.getHeaders("ETag")) 
                System.out.println(header.getName()+" == "+header.getValue());
```

**but if I tried to but the main URL:http://www.mkyong.com, then it will give me only response for the main html**

How to fetch them?

**Comment by asolntsev** [comment]
@hana9090 As I know, it's not possible with Selenium webdriver.
The only way to do that is use proxy server. For example, https://github.com/lightbody/browsermob-proxy

**Comment by hana9090** [comment]
@asolntsev 
what do you think with this way by using firebug extension?
https://eveningsamurai.wordpress.com/2013/06/29/capturing-network-traffic-using-selenium-webdriverfirebug/

**Comment by asolntsev** [comment]
Yes, technically it's possible. Why not.

But I would prefer using proxy, because
1. It's not hard at all. just few lines of code.
2. It doesn't depend on browser. you can use it with firefox, chrome, phantomjs or whatever else.

Actually we are going to embed proxy server in Selenide. We need it to download files, but it also can be used for testing ETags and many more other things.

**Comment by JasonTolotta** [comment]
@hana9090 

I agree with @asolntsev proxy works best because of the browser compatibility feature.

I wrote up an article incorporating [Selenide with BrowserMob Proxy](http://www.jitblog.net/selenide-with-browsermob-proxy/), but you need to create a custom WebDriver for each browser type.

**Comment by hana9090** [comment]
Thanks @asolntsev  :)

**Comment by hana9090** [comment]
Thanks @JasonTolotta 
I have some questions regarding your blog, I write them as comments on your blog

**Comment by asolntsev** [comment]
I hope the original question is answered. Closing the issue.

**Comment by neharmalviya** [comment]
@hana9090 Can you please share your article of how to capture network calls using selenide.
http://www.jitblog.net/selenide-with-browsermob-proxy/ is not accessible.

**Comment by asolntsev** [comment]
@neharmalviya Just google it :)   Here is the link: https://jitblog.net/selenide-with-browsermob-proxy/

But not that this article is outdated. I mean, nowadays BrowserMobProxy is built in Selenide. You can just set `Configuration.proxyEnabled = true;` before opening a browser, and then use method `WebDriverRunner.getSelenideProxy().getProxy()` for accessing BrowserMobProxy.
