### ISSUE TITLE
has(attribute("title")) matches even there is not a title

### ISSUE THREAD

**Issue by crocodilechris** [codeborne/selenide#352]
**Problem**:
I address the following image: `<img border="0" src="../images/status_false.gif">`.
When I check if it has a title attribute via `img.has(attribute("title"))` it always returns true.

**Expectation**:
The request returns false if the attribute is non-existent

**Comment by JasonTolotta** [comment]
I can confirm that this is an issue.

```java
import static com.codeborne.selenide.Selenide.$;

import org.junit.Test;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.Selenide;

public class AppTest 
{
	@Test
	public void test() {
		Selenide.open("http://www.example.com");
		$("a").shouldHave(Condition.attribute("title"));
		$("a").has(Condition.attribute("title"));
		$("a").has(Condition.attribute("blah"));
	}
}
```

**Comment by asolntsev** [comment]
@crocodilechris @JasonTolotta True, it seems to be a bug. I will fix it.

**Comment by asolntsev** [comment]
@JasonTolotta Your example doesn't show anything. 
You don't check if method `has` returned true or false.
You should write something like this:

```java
  assertFalse($("a").has(Condition.attribute("title")));
  assertFalse($("a").has(Condition.attribute("blah")));
```

**Comment by asolntsev** [comment]
@crocodilechris I have researched the issue.
It appears that this is a Selenium webdriver issue, and this problem happens only for `title` attribute. 
Method `WebElement.getAttribute("title")` always returns empty string, even if element doesn't have "title" attribute. 

BUT
I believe you don't need it at all. Why do you use IFs in your tests? It's a bad practice.
Do not use IFs, but use `should` methods instead:

```java
img.shouldHave(attribute("title", "Userpic"));
```

**Comment by JasonTolotta** [comment]
@asolntsev 

Oh Snap! You are right about the Selenium `WebElement#getAttribute()`.
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebElement.html#getAttribute-java.lang.String-

```java
import static com.codeborne.selenide.Selenide.$;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.WebDriverRunner;

public class AppTest 
{
    @Test
    public void test() {
        Selenide.open("http://www.example.com");
        $("a").shouldHave(Condition.attribute("title"));
        WebDriver driver = WebDriverRunner.getWebDriver();
        
        Assert.assertNotNull(driver.findElement(By.tagName("a")).getAttribute("title"));
        Assert.assertTrue(driver.findElement(By.tagName("a")).getAttribute("title").equals(""));
        System.out.println("title=" + driver.findElement(By.tagName("a")).getAttribute("title"));
    }
}
```
