### ISSUE TITLE
Selenide have no css("","") method to create Condition Class in shouldHave waitUntil.

### ISSUE THREAD

**Issue by yisake** [codeborne/selenide#353]
// Example usage:
$("h1").shouldHave(css("font-size", "16px"));

For selenide 3.5.1, I doesn't find the css static method in com.codeborne.selenide.Condition.

**Comment by yisake** [comment]
How to add the extension css method in project not in selenide???

**Comment by JasonTolotta** [comment]
Should it be `$("h1").shouldHave(Condition.attribute("font-size", "16px"))`

**Comment by yisake** [comment]
@JasonTolotta 

From the source code, it seems that this method just return the element.getAttribute(attributeName).
**But the css property should use element.getCssValue(String) method.**
Are you sure about this?

**source code
  public static Condition attribute(final String attributeName) {
    return new Condition("attribute") {
      @Override
      public boolean apply(WebElement element) {
        return element.getAttribute(attributeName) != null;
      }
      @Override
      public String toString() {
        return name + " " + attributeName;
      }
    };
  }

**Comment by JasonTolotta** [comment]
@yisake 

Not sure about 3.5.1, but 3.6 Condition class definitely has method `attribute(attributeName, expectedAttributeValue)`.

Reference: http://selenide.org/javadoc/3.6/com/codeborne/selenide/Condition.html

**Comment by yisake** [comment]
@JasonTolotta  I've the inherit the Condition class and create an new method for css property as attribute method(defined as hasCssValue). 

**
I' recommend adding the method into selenide. Does anybody can give me feedback of this problem?

**Comment by asolntsev** [comment]
Hi @JasonTolotta  @Huangfu !

This case is described in the Selenide documentation:
http://selenide.org/documentation.html

Look for this part: $("h1").shouldHave(css("font-size", "16px"));

But note this was just an example of custom Condition.
Generally I believe this is a bad idea to test CSS properties.
Such test would be absolutely unstable and unmaintainable.

* CSS properties can be easily modified without real UI changes.
* CSS properties can be inherited

A better idea is to check classes, like:
$(".user", 0).shouldHave(cssClass("*active*"));
$(".user", 1).shouldHave(cssClass("*inactive*"));

These "*active*" and "*inactive*" have logical meaning. You only need to
check that user is logically inactive, and you don't care what CSS actually
implements it.

Andrei Solntsev

2016-06-24 8:26 GMT+03:00 Huangfu chunfeng <notifications@github.com>:

**Comment by yisake** [comment]
@asolntsev 
1.But in some situation ajax request will the change the color of some element. So I need check the css property in seconds for timeout.

2.What's the default timeout for should method?

**Comment by asolntsev** [comment]
Hi Huangfu!

1. It's still bad solution.
Ajax request should add/remove some CSS classes from elements.

2. Default Selenide timeout is 4 seconds. Can be modified with
Configuration.timeout = 8000; // ms

Andrei Solntsev

2016-06-24 11:35 GMT+03:00 Huangfu chunfeng <notifications@github.com>:

**Comment by rosolko** [comment]
@VasaviUppada Using selenide you can only check color with raw, as I know, rgb color value. But if you want to check it as hex - you need to create custom condition.

**Comment by asolntsev** [comment]
I guess it depends on browser. Different browsers can return color in
different format.

Andrei Solntsev


чт, 19 июл. 2018 г. в 9:35, Aliaksandr Rasolka <notifications@github.com>:
