### ISSUE TITLE
Would be nice to have dragAndDropTo(SelenideElement)

### ISSUE THREAD

**Issue by generator87** [codeborne/selenide#355]
Currently dragAndDropTo accepts only String as a parameter. It would be very handy if it would accept Selenide element as well. dragAndDropTo(SelenideElement)

Thanks!

**Comment by thasherwin** [comment]
One question related to dragAndDrop, what is String input parameter is required to make it work.  I couldn't figure it out. Thx

**Comment by tkuzmitskiy-imgstg** [comment]
Example is ele1.dragAndDropTo("#drag_handle");    // here #drag_handle is ID of an element. ele1 is a Selenide element which I want to drag and drop

**Comment by thasherwin** [comment]
Okay thanks.
