### ISSUE TITLE
Unable to use Appium TouchActions with Selenide

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#356]
Currently this code throws ClassCastException:

``` java
import io.appium.java_client.MobileDriver;
import io.appium.java_client.TouchAction;

    TouchAction action = new TouchAction((MobileDriver) getWebDriver());
    action.longPress($(By.name("2")));
```

exception stack trace:

``` java
java.lang.ClassCastException: com.sun.proxy.$Proxy6 cannot be cast to org.openqa.selenium.remote.RemoteWebElement
    at io.appium.java_client.TouchAction.longPress(TouchAction.java:207)
    at com.codeborne.CalculatorTest.testCalculator(CalculatorTest.java:65)
```

full code sample: https://gist.github.com/mkpythonanywhereblog/d1fb3dca2e66146f519f

**Comment by asolntsev** [comment]
Known workaround: use method `SelenideElement.toWebElement()` to get the original `WebElement`:

```java
    action.longPress($(By.name("2")).toWebElement());
```

**Comment by asolntsev** [comment]
I sent a pull request for the Appium java client: https://github.com/appium/java-client/pull/432

**Comment by asolntsev** [comment]
Wow, it has been merged to appium 4.1.0. Pretty fast reaction!

**Comment by BorisOsipov** [comment]
@asolntsev is it actuall?

as I know now we have https://github.com/codeborne/selenide-appium 

Close issue or move to selenide-appium issues?

**Comment by asolntsev** [comment]
@BorisOsipov It seems that the issue can be closed. Thanks.
