### ISSUE TITLE
Disable creating .html file, while creating screenshot

### ISSUE THREAD

**Issue by kirdeleg** [codeborne/selenide#358]
If it possible, it would be nice to create feature, that can turn off creating .html file, while creating screenshot, because sometimes .html files are not needed, but they are takes a lot of place. For our project it is really important, because of lack of memory on VM.

**Comment by JustAlexOne** [comment]
+1
Having the same issue. Would really appreciate to have a possibility to "switch off" html files creation

**Comment by asolntsev** [comment]
@kirdeleg @JustAlexOne We will do it, no problems.
But let me suggest you a workaround for this problem. 

Screenshots and *.html files are saved only for failed tests.
So, just **fix your tests**!

Why should one have a lot of failing tests? Is it normal? 
P.S. We typically have 0 failing tests, in some bad days we have 3-5 of them.

**Comment by JustAlexOne** [comment]
In my case we do take screenshots before each test step and also for passed
tests as well. I understand this is useless (if not to say in other words),
but this is a customer request to have test reports with screenshots for
each step...
That's we have a lot of screenshots even for not failing tests.
Again, I understand, that's a senseless stuff

**Comment by asolntsev** [comment]
Closing the feature request: it has been implemented in #359
