### ISSUE TITLE
CKE Editor

### ISSUE THREAD

**Issue by bigalnz** [codeborne/selenide#361]
Hello,

Is there a way to insert text into a CKE style editor like:

`<body spellcheck="false" class="cke_editable cke_editable_themed cke_contents_ltr cke_show_borders" `contenteditable="true">
`<p>
<br></br>
</p>
</body>`

Ordinarily the text would go between the BR.

Thanks

-Al

**Comment by asolntsev** [comment]
@bigalnz I am not sure it's really possible. Selenium only has "sendKeys()" method which does not allow you to put text in the middle of text field.

But do you really need these br tags? Just try $("body").sendKeys("your text");

**Comment by simple-elf** [comment]
It's not Selenide or Selenium question at all.
Editors like CKE may have hidden input or textarea. Try do sendKeys to iframe, what contains this <body>

**Comment by asolntsev** [comment]
@bigalnz Can we close the issue?

**Comment by asolntsev** [comment]
Well, closing the issue...
