### ISSUE TITLE
No common error description for failed element search by condition inside ElementsCollection when calling action

### ISSUE THREAD

**Issue by yashaka** [codeborne/selenide#365]
The following test with Selenide 3.7 (and actually all other versions):

``` java
public class NotFoundByConditionSelenideElementErrorMessageTest {

    @Test
    public void shouldContainInfoWithAllDetails_WhenCallingAction(){
        open("http://todomvc4tasj.herokuapp.com/");

        // assume that task should have "automatically added dot" in the end
        $("#new-todo").setValue("a").pressEnter();
        $$("#todo-list>li").findBy(exactText("a.")).hover().find(".destroy").click();
        $$("#todo-list>li").shouldBe(empty);
    }
}
```

implicitly waits common 4 seconds, and then fails with non-informative error:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

While the following test:

``` java
public class NotFoundByConditionSelenideElementErrorMessageTest {

    @Test
    public void shouldContainInfoWithAllDetails_WhenCallingAction(){
        open("http://todomvc4tasj.herokuapp.com/");

        // assume that task should have "automatically added dot" in the end
        $("#new-todo").setValue("a").pressEnter();
        $$("#todo-list>li").findBy(exactText("a.")).shouldBe(visible);
    }
}
```

Fails with:

```
Element not found {#todo-list>li.filter(exact text 'a.')}
Expected: visible

Screenshot: file:/Users/ayia/projects/tmp/selenide-tests/build/reports/tests/1470245512550.0.png
Timeout: 4 s.
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

First of all - both errors should contain the same info.

Second - when fixing this bug, I would recommend to improve the message in other aspects.

E.g. It would be much more informative if error message contains the "actual" texts of all elements in collection.

Third - it may have sense to fix this bug along with #243. Because the same code seems to be modified (actually currently there is no much of "such code" to put a fix in, but we could create it in #243, so it will be a good chance to fix this bug too)

Fourth :) - there are many similar edge cases. And I would recommend to test all of them, provide correspondent test coverage, and fix other probable bugs of such type.

**Comment by asolntsev** [comment]
@yashaka This issue describes another problem with collections: http://automated-testing.info/t/pomogite-razobratsya-s-problemoj-czikla-v-selenide/10467

Probably we can fix both.

**Comment by yashaka** [comment]
@asolntsev Actually this issue is already known and was filed here more than a year ago.
Here it is: #181

So just mark it as "Let's do it" and we will fix it :)

**Comment by rosolko** [comment]
Merged.
