### ISSUE TITLE
@Listeners(TextReport.class) does not show any logging on Selenide version 3.8 using testng

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#371]
@Listeners(TextReport.class) does not show any logging with TestNG on Selenide version 3.8

I updated Selenide from version 3.7 to version 3.8 and ran a test and i did not see any logging. Did the way to activate the report logging changed?

Thanks,

regards,

Sherwin

**Comment by asolntsev** [comment]
@thasherwin Yes, it was changed in [Selenide 3.6](http://selenide.org/2016/06/01/selenide-3.6):

> now the report will only be generated for classes annotated with @Report.

Are you sure you started experiencing this problem exactly in 3.8 vs 3.7 version?

**Comment by thasherwin** [comment]
I tried going back to version 3.7 and it worked but when i went to version 3.8 i did not work.. I was using only the listener annotation;
`@Listeners(TextReport.class)`

I was not aware that i should use the report annotation. 

I tried to use only the report annotation but that did not work. 
It is working now for me on version 3.8 when using both annotations;
```
@Report
@Listeners(TextReport.class)
```
Not sure whether this is how it suppose to work

**Comment by thasherwin** [comment]
I dont see this porblem anymore. I am using selenide 3.9.1 and everything is fine.. So i will close this issue

**Comment by asolntsev** [comment]
For the record: in Selenide 6.7.0, annotation `@Report` was deprecated. 

Now text report will be generated for all classes marked with `@Listeners({TextReport.class}` and their subclasses.
