### ISSUE TITLE
how to refresh iframe?

### ISSUE THREAD

**Issue by anyone-can-test** [codeborne/selenide#374]
refresh() refreshes the whole page.
I want to refresh only frame.
How can I do that?

**Comment by joshLV** [comment]
see:
https://github.com/codeborne/selenide/blob/dba416351c98abf616eee09d1273474d5ad84c3f/src/test/java/integration/FramesTest.java

**Comment by anyone-can-test** [comment]
The FramesTest is move between frames.
I could not find any hints about frame refresh.

**Comment by simple-elf** [comment]
Does this code works for you?
```
switchTo().frame("mainFrame");
refresh();
```

**Comment by anyone-can-test** [comment]
No. I already did that.
refresh() refreshes the main page, not the frame.

**Comment by anyone-can-test** [comment]
Why I want to refresh only the frame is because of test execution speed.
Refreshing the main page is a little bit slow.

**Comment by joshLV** [comment]
In  actual, how to refresh the browser iframe?

**Comment by anyone-can-test** [comment]
In the area of the frame, I click the right button of the mouse.
The popup has frame refresh, which refreshes only the frame.

**Comment by anyone-can-test** [comment]
I  did it.

```java
switchTo().defaultContent();
((JavascriptExecutor)WebDriverRunner.getWebDriver()).executeScript(
		"var iframe = document.getElementById('productIframe'); iframe.src = iframe.src;");
switchTo().frame("productIframe");
```

**Comment by joshLV** [comment]
good
