### ISSUE TITLE
last() fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kubikrubikvkube** [codeborne/selenide#376]
SelenideElement leftList = $$(By.tagName("select")).first();
SelenideElement rightList = $$(By.tagName("select")).last();

![screenshot_1](https://cloud.githubusercontent.com/assets/15730260/17664002/919f3078-62f9-11e6-9a31-69774c304a77.png)

When trying to access rightList element - ArrayIndexOutOfBoundsException thrown

**Comment by vinogradoff** [comment]
How did you access it?

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by doncarton** [comment]
rightList.shouldBe...

**Comment by asolntsev** [comment]
@doncarton I cannot reproduce the problem. I did copied your lines, and they work for me.
Please provide exact test and html.

**Comment by simple-elf** [comment]
Maybe you face this problem, because when you trying to access last item, it already disappear in DOM. How much code is between this two operations?

**Comment by BorisOsipov** [comment]
closed due no reproducable example.
