### ISSUE TITLE
Shouldhave for input value

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#381]
I am trying to check an input field if it has a specific or not.
I try this:

`$("input#id").shouldHave(text("hana"));`

`<input class="cl" id="id" type="text" value="hana"></input>
`
But didn't work!! how to check the value !!

**Comment by asolntsev** [comment]
@hana9090 It's pretty easy:

```java
$("input#id").shouldHave(value("hana"));
```

**Comment by hana9090** [comment]
Thank you :)
I guess that I have to use value instead of text but I have error on the value() function.
This is my fault forgot to include it!

**Comment by asolntsev** [comment]
I hope the question is answered. Closing the issue.
