### ISSUE TITLE
Create a consistent link to the latest Java doc

### ISSUE THREAD

**Issue by kenston** [codeborne/selenide#382]
Currently latest Java doc link contains a version number: http://selenide.org/javadoc/3.9/com/codeborne/selenide/SelenideElement.html.

Maybe we can have the latest Java doc link also at some version-less URL which we can link to while retaining the versioned doc links:
http://selenide.org/javadoc/latest/com/codeborne/selenide/SelenideElement.html or http://selenide.org/javadoc/current/com/codeborne/selenide/SelenideElement.html

**Comment by asolntsev** [comment]
@kenston Good idea! We should do it.

**Comment by kenston** [comment]
Thanks @asolntsev !

**Comment by asolntsev** [comment]
@kenston I was thinking about your suggestion. This is good, but I cannot imagine how exactly can we do it. Probably we need some special jekyll configuration. Can you help?

**Comment by kenston** [comment]
@asolntsev I'm not sure if I can be of help on this one. I'm not familiar with Jekyll config or Github pages yet. Off the top of my head, I'm thinking of just deleting `current` and copying the updated files to the `current`.

**Comment by asolntsev** [comment]
@kenston It's not a bad idea at all :)

Yes, this is exactly my problem: I could not figure out how to create a link "current" to version "4.2.1". But just copying javadoc folder is really simple solution. Why not.

**Comment by asolntsev** [comment]
@kenston Done!
This is the new link: http://selenide.org/javadoc/current/
