### ISSUE TITLE
start using selenium 3.0

### ISSUE THREAD

**Issue by anilreddy** [codeborne/selenide#388]
@asolntsev,
start adding support for selenium 3.0 beta to catch early bugs and make selenide stable until stable version of selenium 3.0 is release.

share your thoughts..!!

**Comment by JasonTolotta** [comment]
Yes, but possibly a fork and not part of this project.

**Comment by shimkiv** [comment]
@asolntsev Hey Andrey, can you please release the Selenide 3.9.(4?) with 5cda351af935226edd441ba8311ff46f566be323 to simplify migration to WebDriver 3.X ?

**Comment by asolntsev** [comment]
Sure, I will do it soon.

**Comment by shimkiv** [comment]
Cheers !

**Comment by asolntsev** [comment]
@anilreddy @JasonTolotta @shimkiv I have tried Selenium 3.0.0-beta3
All Selenide tests are green (except [InputFieldTest](https://github.com/codeborne/selenide/blob/master/src/test/java/integration/InputFieldTest.java) that is known webdriver issue). 

One more problem is that class `org.openqa.grid.selenium.GridLauncher` disappeared in Selenium 3.0.0-beta3. I guess it was renamed. So we need to find out what is the new name of this class (or how grid is run in selenium 3.0).

**Comment by shimkiv** [comment]
@asolntsev I believe this one 
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/selenium/GridLauncherV3.java
can be used instead

**Comment by asolntsev** [comment]
@shimkiv Thank you, it's what I looked for!

**Comment by anilreddy** [comment]
@asolntsev super..! then you can release a beta version of selenide so that we can test it against our suites.

**Comment by anilreddy** [comment]
@asolntsev selenium 3.0 stable was released. Any plan releasing major selenide version soon?

**Comment by asolntsev** [comment]
Hi Anil!
Yes, sure, we can upgrade to selenium 3.0.0 today. Thank you for the
information!

Do you think we really need to release major version of Selenide? Probably
not, because nothing changes for Selenide users.

**Comment by anilreddy** [comment]
@asolntsev OK..!!

**Comment by asolntsev** [comment]
@anilreddy @JasonTolotta @shimkiv We released Selenide 4.0 with depending on selenium-java 3.0.0

Thank you all for your participation!

**Comment by shimkiv** [comment]
Awesome, thank you.

**Comment by anilreddy** [comment]
Thank you all..!!
