### ISSUE TITLE
open() doesn't open https sites (worked before)

### ISSUE THREAD

**Issue by FullContactCoding** [codeborne/selenide#390]
One of my tests stopped working. 

I try:

`open("https://mail.google.com/");
`
But the url won't fill. After some experimentation I found out that it's https sites that show this behaviour.

I have no problem with for instance `open("http://edition.cnn.com/");` But `open("https://www.facebook.com/";` won't open either.

**Comment by asolntsev** [comment]
@FullContactCoding Thank you, I will research it!

**Comment by FullContactCoding** [comment]
I'm using Selenium version 2.53.1 and Selenide 3.9.2 

Thanks!

**Comment by asolntsev** [comment]
@FullContactCoding Please specify browser and its version.
I have tried to `open("https://mail.google.com/"); ` with chrome - it works for me.

**Comment by FullContactCoding** [comment]
Firefox 45.0.2 on Ubuntu

**Comment by JasonTolotta** [comment]
@FullContactCoding 
I had a similar issue working at a site that had a proxy specifically targeting HTTPS connections.
Does the browser or system use a network proxy?

**Comment by FullContactCoding** [comment]
@JasonTolotta Yes we need to connect over a VPN. This is new behavior though so it did work before over the same connection.

**Comment by asolntsev** [comment]
@FullContactCoding Sorry, I cannot reproduce the issue.
Please feel free to reopen the issue if you can provide more details. Ideally, a working project that I can run on my machine to reproduce the problem.
