### ISSUE TITLE
Select option containing text

### ISSUE THREAD

**Issue by kenston** [codeborne/selenide#391]
The method `SelenideElement.selectOption(String text)` selects the option that matches the given text. Can we have `selectionOptionContaining(String text)` to select the option that contains the given text?

**Comment by asolntsev** [comment]
@kenston Sure, why not.
Don't you want to prepare a pull request?

**Comment by kenston** [comment]
Will see if I can develop one. Thanks @asolntsev !

**Comment by asolntsev** [comment]
@kenston Sorry for the long delay.
I implemented this feature in Selenide 4.2 (will be released soon).
