### ISSUE TITLE
NoClassDefFoundError since 3.9.2

### ISSUE THREAD

**Issue by simple-elf** [codeborne/selenide#395]
Since 3.9.2 where is NoClassDefFoundError exception:
`$("body").waitUntil(exist, 5000);`
```
com.codeborne.selenide.ex.UIAssertionError: NoClassDefFoundError: Could not initialize class com.codeborne.selenide.commands.Commands
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:85)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:61)
	at com.sun.proxy.$Proxy19.waitUntil(Unknown Source)
```

On 3.9.1 and earlier there is no exception

I'm using JDK 1.7, Firefox 45.3.0 esr, Windows 7

**Comment by JasonTolotta** [comment]
I could run the following with no errors with Firefox v47.0.1

```
navigator.open("http://www.google.com.au");
$("body").waitUntil(Condition.exist, 5000);
```

Selenide: v3.9.2
JDK: 1.8 update 101

I would try a different browser or Java 1.8

**Comment by simple-elf** [comment]
`$("body").getText()`
This code also throws exception

**Comment by RealistExperimenter** [comment]
I have the same issue with 3.9.2. JDK 1.8 u101

**Comment by simple-elf** [comment]
```
1:     SelenideElement body = $("body");
2:      try {
3:          String str = body.getText();
4:      } catch (Exception e) {
5:          e.printStackTrace();
6:      }
```

Exception on line 3, not 5. And same stacktrace

**Comment by RealistExperimenter** [comment]
@asolntsev I found reason of this issue.
When I am using standard chrome driver  `Configuration.browser = "chrome";` all works fine, but when I am using custom driver Configuration.browser = ChromeDriverProvider.class.getName(); this issue appears.

**Comment by simple-elf** [comment]
I'm using `Configuration.browser = "firefox"`

**Comment by simple-elf** [comment]
With `Configuration.browser = "chrome"` I have same Exception

Selenium version is 2.53.1

**Comment by asolntsev** [comment]
@simple-elf @RealistExperimenter Guys, I am in trouble.
I still don't see a full stack trace. I still don't know **which** class is not found. I just cannot reproduce the issue. :(

**Comment by RealistExperimenter** [comment]
@simple-elf do you using an allure-maven-plugin dependency in your project? I had conflict with it, after removing this dependency from dependencies this issue disappeared.

**Comment by simple-elf** [comment]
Yep. I'm trying to reproduce it with new sample project, and it works fine without allure-maven-plugin

**Comment by asolntsev** [comment]
Hi @simple-elf and @RealistExperimenter!
Thanks for the idea of allure-maven-plugin. 

As a result of hardcore debugging session, I have found that the real exception is this one:

```java
java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy
	at com.codeborne.selenide.commands.DownloadFile.<init>(DownloadFile.java:21)
	at com.codeborne.selenide.commands.Commands.addFileCommands(Commands.java:106)
	at com.codeborne.selenide.commands.Commands.resetDefaults(Commands.java:32)
	at com.codeborne.selenide.commands.Commands.<init>(Commands.java:17)
	at com.codeborne.selenide.commands.Commands.<clinit>(Commands.java:12)
       ...
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.TrustStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

It happens because Selenide 3.9.* need class `org.apache.http.ssl.TrustStrategy` which comes in library `httpcore-4.4.4.jar`. But Allure depends on old version of this library: `httpcore-4.3.2.jar` which doesn't contain this class.

**Comment by asolntsev** [comment]
@simple-elf  @RealistExperimenter

I registered a pull request to allure-maven-plugin to upgrade httpcore.jar version:
https://github.com/allure-framework/allure-maven-plugin/pull/26

**Comment by RealistExperimenter** [comment]
@asolntsev Thank you!

**Comment by JasonTolotta** [comment]
http://xkcd.com/1172/

**Comment by asolntsev** [comment]
Still, I registered another issue in Selenide for better reporting: https://github.com/codeborne/selenide/issues/401
