### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by kenshir007** [codeborne/selenide#400]
I think it would be great idea to add selectMultiple(String...) to SelenideElement interface.
It should select all options listed in arguments.
example of usage:
$(String).selectOption("Option 1", "Option 2);

**Comment by asolntsev** [comment]
@kenshir007 Sure, why not. Do you mean "select by text" or "select by value"?

Probably it would be better to just add varargs to existing methods `selectOption` and `selectOptionByValue`? It would mean that you can write simply

```java
  $("select").selectOptionByValue("aa", "bb", "cc");
  $("select").selectOption("Aaa", "Bbb", "Ccc);
```

**Comment by kenshir007** [comment]
Cool, I meant both, text and options, cause both of them may be required

**Comment by asolntsev** [comment]
I have add new method for retrieving all selected options:
```java
select.getSelectedOptions().shouldHave(
        texts("Маргарита", "Theodor Woland"));
```

And these 3 methods now accept multiple arguments:

```java
select.selectOption("Маргарита", "Theodor Woland");
select.selectOption(0, 2, 3);
select.selectOptionByValue("cat", "woland");
```

See https://github.com/codeborne/selenide/blob/master/src/test/java/integration/MultipleSelectTest.java
