### ISSUE TITLE
New Style Select

### ISSUE THREAD

**Issue by kenshir007** [codeborne/selenide#403]
Nowadays common select is used not so often, because most developers switch to JSFrameworks like Angular 1/2, React, etc... thats why we deal much more with selects like:
```
<div class='select'>
   <span>Option 2</span>
   <div>
        <h?>Label of list</h?>
        <ul>
            <li>Option 1</li>
            <li>Option 2</li>
            <li>Option...</li>
        </ul>
    </div>
</div>
```

So the new select should be able to deal with it.
To do it with Selenide is usually like:
```
$(".select").click();
$$(".select li").findBy(matchesText("Option 1")).click(); 
$(".select span").shouldHave(text("Option 1"));
```
So it can be simplified to smth like:
`$(".select").divSelect("Option1"); // By text`
or 
`$(".select").divSelect(1); // By index`

To make this select faster we can do something like:
`String html = $(".select").innerHtml();`
//then we can parse all `<li>` elements in html to get OrderedList<String> with values;
if we know index of `<li>` element, we can interact with it without iterating `<li>` list with webdriver.

**Comment by asolntsev** [comment]
@kenshir007 Similarly to #404, it seems to be too bootstrap-specific. Every js framework has its own hierarchy of divs/spans/whatever for implementing select. I cannot imagine how it can be solved generally.
