### ISSUE TITLE
Unify getText() method

### ISSUE THREAD

**Issue by kenshir007** [codeborne/selenide#405]
Currently to get text from element we have 2 methods: getTest() and getValue();
I think that we can unify those 2 methods in one, because there is no point to get value from spans, h, p, label etc... also there is no point to get text  from inputs, because inputs have no text, only values.

**Comment by asolntsev** [comment]
@kenshir007 Reasonable. But probably there are elements that have both text and value?

**Comment by bravoaqa** [comment]
Yees.. Of course it can be.. And moreover - when element has both 'text' and 'value' but different value. And in this case, often appears bugs - when from 'value' sends data reqests
