### ISSUE TITLE
Simplifying tests for Selenide

### ISSUE THREAD

**Issue by kenshir007** [codeborne/selenide#406]
I found some html files in tests resources package and I think that we can get rid of them by using [J2HTML](https://github.com/tipsy/j2html ) to write tests for Selenide faster and make them more readable.

**Comment by asolntsev** [comment]
@kenshir007 Thank you for the suggestion, J2HMTL seems to be a useful library.
But Selenide does not generate any html by itself. Selenide just saves page source (both html and screenshot) in case of errors.

**Comment by kenshir007** [comment]
Well, I meant Using j2html in test scope to test Selenide, not target project

**Comment by asolntsev** [comment]
ok, cool, that's probably a good idea. Need to try it.
