### ISSUE TITLE
[Feature Request] add an condition to check staleness of an element

### ISSUE THREAD

**Issue by anilreddy** [codeborne/selenide#409]
Hi @asolntsev,

Similarly like existing conditions like `$("element").shouldBe(visible)` can you add a condition which checks staleness of an element.
Like this:
`$(element).shouldBe(stale)` or better. Let me know your opinion on it. 

Thanks,
Anil

**Comment by asolntsev** [comment]
@anilreddy Can you comment why it's useful? What is the use case?

(Currently I don't imagine why I could need it. It seems that real end-user also don't see "stolen" elements, so test also should not.)

**Comment by anilreddy** [comment]
sorry its my test issue closing it.

**Comment by asolntsev** [comment]
@anilreddy Still waiting for your answer...

**Comment by anilreddy** [comment]
@asolntsev I was on vacation. Currently I didn't find good example that we have in our application. I will open it again when I find one. Am closing it for now.
