### ISSUE TITLE
Selenide Proxy stopped working

### ISSUE THREAD

**Issue by andrey-ryoo** [codeborne/selenide#410]
With the new Chrome update selenide stopped working.
when I try using open("url") method, selenide opens browser but then it cannot reach url. It say no internat connection, check proxy...
Selenide version 3.9.3
Chrome Version 53.0.2785.116 (64-bit)
Platform MacOS X Sierra 
Only rollback to selenide 3.8.1 helps

**Comment by asolntsev** [comment]
@kenshir007 Strange... I am using MacOS X El Captain, and last Chrome 53.0.2785.1 still works.

**Comment by kenshir007** [comment]
Need more feedback from Sierra users. I've tried 
`Configuration.fileDownload = Configuration.FileDownloadMode.HTTPGET;`
and it helped.

**Comment by asolntsev** [comment]
@kenshir007 Please upgrade to Selenide 3.10.
It has `fileDownload = HTTPGET` by default.

**Comment by kenshir007** [comment]
Do you have it on Maven central? The latest I could find was 3.9.3

**Comment by asolntsev** [comment]
@kenshir007 Yes, sure, it's on maven central repo: http://search.maven.org/#search%7Cga%7C1%7Cselenide

**Comment by kenshir007** [comment]
Oh, I see, thanks) I'll test it tomorrow

**Comment by kenshir007** [comment]
Sorry for long delay, the framework works fine. The only point is MacOS Sierra is now blocking all proxies by default. I've tested it with other apps using proxies.

**Comment by BorisOsipov** [comment]
Hi @andrey-ryoo 

Am I right that there are no selenide issues now? let's close issue :)

**Comment by andrey-ryoo** [comment]
Sure, now it works as charm
