### ISSUE TITLE
phantomjs.exe stay in memory if i set capability

### ISSUE THREAD

**Issue by BabyRoot** [codeborne/selenide#411]
Simple test:
```
        Configuration.reportsFolder = "target/report";
        Configuration.savePageSource = false;
        Configuration.browser = "phantomjs";                

        DesiredCapabilities dc = new DesiredCapabilities();
        dc.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, 
                new String[] {"--webdriver-logfile="+System.getProperty("user.dir")+"/target/phantomjsdriver.log"});
        WebDriverRunner.setWebDriver(new PhantomJSDriver(dc));   
       
        Selenide.open("www.ya.ru");
```
after play - in memory stay phantomjs.exe.
if i not make setWebDriver - phantomjs.exe close correctly.

**Comment by asolntsev** [comment]
@BabyRoot It's expected behaviour. Read javadoc for method `WebDriverRunner.setWebDriver`.
If you created `PhantomJSDriver` by yourself, you need to close it by yourself. 
So, just use `close()` in the end of your test.

**Comment by BabyRoot** [comment]
Тупанул, спасибо. Как всегда читать о том что использую рука не поднялась...
