### ISSUE TITLE
Browser hangs on invoke refresh() after invoke updateHash()

### ISSUE THREAD

**Issue by RomanIsko** [codeborne/selenide#412]
**Environment**:
Ubuntu 16.04.1 LTS
Oracle Java 8
Selenide 3.10
Geckodriver 1.10
Firefox 49
Selenium 3.0.0-beta4

**Firefox does not refresh page after hash navigation**

steps:
* install Firefox 49
* download Geckodriver and set up system property `webdriver.gecko.driver` equals to path to geckodriver executable
* open page without hash navigation
* do hash navigation (invoke *updateHash("hashHere");* method)
* refresh page by invoke *refresh();* method

Actual: browser does NOT refresh page. Testing is stopped. Any exception is not thrown
Expected: browser refreshes page with hash navigation

Code example:
```java
@Test
    public void name() throws Exception {
        System.setProperty("webdriver.gecko.driver", "build/geckodriver");
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability("marionette", true);
        WebDriver driver = new FirefoxDriver(capabilities);
        WebDriverRunner.setWebDriver(driver);

        open("https://en.wikipedia.org/wiki/Selenide");
        refresh();
        System.out.println("refresh BEFORE hash navigation");
        updateHash("Examples");
        System.out.println("refresh AFTER hash navigation");
        System.out.println("Trying refresh again");
        refresh();
        System.out.println("Done!");
    }
```

Note:  
```java
WebDriverRunner.getWebDriver().navigate().refresh();
```
works as expected.
This issue may be related to issue #304

**Comment by RomanIsko** [comment]
DEBUG log output attached

[refresh.log.zip](https://github.com/codeborne/selenide/files/513454/refresh.log.zip)

**Comment by asolntsev** [comment]
@RomanIsko I confirm, I can also reproduce the issue.
But this is bug issue of Marionette Driver, not Selenide. Please report issue to them.

**Comment by RomanIsko** [comment]
@asolntsev I cannot reproduce this bug with Selenium 3.0 and Gecko Driver 0.10.0 using this code

```java
    @Test
    public void seleniumUpdateHash() throws Exception {
        System.setProperty("webdriver.gecko.driver", "build/geckodriver");

        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability("marionette", true);
        WebDriver driver = new FirefoxDriver(capabilities);

        driver.get("https://en.wikipedia.org/wiki/Selenide");
        driver.navigate().refresh();
        System.out.println("refresh BEFORE hash navigation");
        String examplesHash = "#Examples";
        ((JavascriptExecutor) driver).executeScript("window.location.hash='" + examplesHash + "';");
        System.out.println("refresh AFTER hash navigation");
        System.out.println("Trying refresh again");
        driver.navigate().refresh();
        System.out.println("Done!");
    }
```
but with Selenide 4.0 it's reproducible.
So I still think that this bug is in Selenide.
