### ISSUE TITLE
chrome browser window cant be maximized

### ISSUE THREAD

**Issue by patrickdargel** [codeborne/selenide#413]
chrome version: 53.0.2785.143 m
selenide version: 3.10

i am unable to set the chrome window to maximized on our selenium grid.
i tried:
Configuration.startMaximized = true;
Configuration.browserSize="1024x768";
Configuration.chromeSwitches = "--start-maximized";
and 
-Dselenide.chrome.switches=--start-maximized

any clues ? do i do something wrong ? i cant remember that this was necessary in the past.

**Comment by asolntsev** [comment]
Hi @patrickdargel !
All of these ways should work. It was not changed in last versions of selenide.

**Comment by asolntsev** [comment]
Hi @patrickdargel !
Have you some progress with this issue?

**Comment by patrickdargel** [comment]
Hi @asolntsev 
no, sadly not. but currently, out Grid is in an upgrade/reconstruction phase. as soon as it is back, it will continue my search.

**Comment by asolntsev** [comment]
@patrickdargel Feel free to reopen the issue when you have more information.

**Comment by junejan143** [comment]
`警告: Cannot maximize ChromeDriver: org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html`

i can't maximized  chrome browser window too ,and this is the logs
