### ISSUE TITLE
shouldNotBe() method works in wrong way

### ISSUE THREAD

**Issue by kenshir007** [codeborne/selenide#414]
What I've done:
set Configuration timeouts to 30 sec (30000)
used method $(selector).shouldNotBe(Condition.visible);

Expected:
if element not present or visible, Selenide should switch to the next action

Actual:
Selenide looks for element and then waits for element not to appear in 30 sec
Then follows next action

**Comment by vinogradoff** [comment]
Could you please check, if your code works differently, if you use 
 $(selector).shouldBe(Condition.invisible);

instead?

**Comment by kenshir007** [comment]
I'm sorry, but there is no invisible option in Condition class, maybe you meant Condition.hidden ?

**Comment by vinogradoff** [comment]
Yes

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by kenshir007** [comment]
Well, I've tried with Condition.hidden, but result was the same. Selenide waits for timeout and then proceeds if there is no element or hidden
![2016-10-12_13-57-07](https://cloud.githubusercontent.com/assets/8489734/19311106/9a3e5f0a-9095-11e6-9e19-50ea8cdb2bd9.png)

**Comment by simple-elf** [comment]
Make sure that your selector is right. I think it's $(".likes .negative") throws NoSuchElementException, not the Should... statement.

**Comment by kenshir007** [comment]
Even if selector is not right it should proceed because condition is met, Element not present on page.

**Comment by simple-elf** [comment]
If you try to check that Element is not present on page
`$$(".likes").shouldHaveSize(0)` or `if ($$(".likes").size() == 0)`
But if Element shoud DISAPPEAR (it was visible a while, and then hidden) you must use `$(".likes").shouldBe(Condition.hidden)`

**Comment by kenshir007** [comment]
Ok, When we use $(selector).shouldBe(visible/exist) Selenide waits until element appears and gets visible, why should $(selector).shouldNotBe(visible/exist) behave in different way?

**Comment by asolntsev** [comment]
@kenshir007 It's not true. Selenide goes immediately to the next action.
I guess you have configured **implicit wait** to 30 seconds.

It's strongly recommended to avoid using implicit waits with Selenide.

**Comment by kenshir007** [comment]
Lets check, what I've done

`
        DriverProvider.initializeChromeDriver(); // Automatically downloads driver binary and puts path into System
        Configuration.timeout = 30000;
        Configuration.closeBrowserTimeoutMs = 30000;
        Configuration.collectionsTimeout = 30000;
        Configuration.startMaximized = true;
        Configuration.browser = loadProperty("browser.name");
        Configuration.baseUrl = loadProperty("site.url");
        Configuration.reportsFolder = "screenshots";
        open("");
        if (Optional.ofNullable(user).isPresent() && user.getRoles().get(0) != Role.GUEST) {
            if (!Optional.ofNullable(user.getCookies()).isPresent()) {
                new RequestCalls(user)
                        .authorize()
                        .getCookies()
                        .forEach(cookie -> WebDriverRunner
                                .getWebDriver()
                                .manage()
                                .addCookie(convertCookie(cookie))); //Cookie is provided from Jersey Client
            } else {
                user.getCookies()
                        .forEach(cookie ->
                                WebDriverRunner
                                        .getWebDriver()
                                        .manage()
                                        .addCookie(convertCookie(cookie))
                        );
            }
        }
        open(pageUrl)

        $(css).shouldNot(present);
`

I do not set implicit waits because I do understand that Selenide is capable for managing waits

**Comment by asolntsev** [comment]
@kenshir007 Could you share code, not the image?
So I could try it by myself.

**Comment by asolntsev** [comment]
@kenshir007 I still cannot reproduce the issue.
What is inside of `DriverProvider.initializeChromeDriver`?

**Comment by kenshir007** [comment]
`public final class DriverProvider {

    public static void initializeChromeDriver() {
        try {
            File driver = findFile("driver", "chromedriver");
            System.setProperty("webdriver.chrome.driver", driver.getAbsolutePath());
        } catch (Exception ex) {
            try {
                downloadChromeDriver();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private static void downloadChromeDriver() throws Exception {

        final String domain = "http://chromedriver.storage.googleapis.com/";
        final String folderName = "driver";
        final String chromeDriver = "chromedriver";

        createDirectoryIfNotExist(folderName);

        URL versionInfo = new URL("http://chromedriver.storage.googleapis.com/LATEST_RELEASE");
        BufferedReader in = new BufferedReader(new InputStreamReader(versionInfo.openStream()));

        final String version = in.readLine();
        final String downloadLink = domain + version;
        File zip;
        File driver;

        switch (determineOs()) {
            case MAC:
                zip = downloadFile(downloadLink + "/chromedriver_mac64.zip", folderName);
                unzipFile(zip);
                driver = findFile(folderName, chromeDriver);
                makeFileExecutable(driver);
                System.setProperty("webdriver.chrome.driver", driver.getAbsolutePath());
                break;

            case LINUX:
                zip = downloadFile(downloadLink + "/chromedriver_linux64.zip", folderName);
                unzipFile(zip);
                driver = findFile(folderName, chromeDriver);
                makeFileExecutable(driver);
                System.setProperty("webdriver.chrome.driver", driver.getAbsolutePath());
                break;

            case WINDOWS:
                zip = downloadFile(downloadLink + "/chromedriver_win32.zip", folderName);
                unzipFile(zip);
                driver = findFile(folderName, chromeDriver + ".exe");
                System.setProperty("webdriver.chrome.driver", driver.getAbsolutePath());
        }
    }
}`

**Comment by asolntsev** [comment]
@kenshir007 Thanks.

Still, could you share a code sample that I could run to reproduce the problem?

**Comment by kenshir007** [comment]
Try to run it
[polygon.zip](https://github.com/codeborne/selenide/files/535564/polygon.zip)

**Comment by kenshir007** [comment]
Did this work?

**Comment by asolntsev** [comment]
@kenshir007 Thank you for the code sample!
Yes, it worked. But it doesn't reproduce the problem. Method `shouldNotBe` works quickly without pauses.

I slightly modified your code to log execution time:

```java
        long start = System.currentTimeMillis();
        System.out.println("Method started");
        $(".auth-menu").shouldNot(Condition.exist);
        long end = System.currentTimeMillis();
        System.out.println("Method Worked in " + (end - start) + " ms.");
        $(".auth").shouldBe(Condition.visible).click();
```

And it reports 61 ms, not 30 seconds:

```
Method started
Method Worked in 61 ms.
```

**Comment by kenshir007** [comment]
Ok thanks Andrey, I'll dig deeper. I'll try to run the code with your modification in the morning.

**Comment by kenshir007** [comment]
I have investigated this case and there are 2 things:
1st. https://yadi.sk/d/vFIabCoBx96BU bug exists, the screencast proves it.
2ed. The problem looks to be local. I've tried to run the same code on my home iMac Late 2015 with the same OS (MacOSX Sierra 10.12) and result was 61ms. JDK is the same (102)
Any suggestion where to look?

**Comment by kenshir007** [comment]
@asolntsev Which Chrome version do you use? I use Version 54.0.2840.59 (64-bit) on Mac where problem reproduces

**Comment by kenshir007** [comment]
https://youtu.be/Oi_79u_sW5U

**Comment by asolntsev** [comment]
@kenshir007 I still cannot reproduce the issue. I typed exactly your code and executed it.
It run with 600 ms.

This is my screencast: https://dl.dropboxusercontent.com/u/2856647/crowdspace-ru.mp4

And this is my code:

```java
import com.codeborne.selenide.Configuration;

import static com.codeborne.selenide.Condition.exist;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;

public class CrowdspaceRu {
  public static void main(String[] args) {
    Configuration.timeout = 30000;
    Configuration.closeBrowserTimeoutMs = 30000;
    Configuration.collectionsTimeout = 30000;
    Configuration.startMaximized = true;
    Configuration.browser = "chrome";
    Configuration.baseUrl = "https://crowdspace.ru/";
    Configuration.reportsFolder = "build";

    open("https://crowdspace.ru/");
    sleep(3000);
    
    long start = System.currentTimeMillis();
    $(".auth-menu").shouldNot(exist);
    long end = System.currentTimeMillis();
    System.out.println((end-start) + " ms.");
    $(".auth").shouldBe(visible).click();
  }
}
```

**Comment by asolntsev** [comment]
@kenshir007 Hi 
Some news on this issue?

Can it be this Selenium bug: https://github.com/SeleniumHQ/selenium/issues/3048 ?
