### ISSUE TITLE
Webdrivermanager integration

### ISSUE THREAD

**Issue by rosolko** [codeborne/selenide#418]
Hi,

Do you think about [webdrivermanager](https://github.com/bonigarcia/webdrivermanager) integration?
It can solve problem with driver binaries.

Thanks.

**Comment by thasherwin** [comment]
Wow. This solution looks nice. I hope it.s platform independent

**Comment by rosolko** [comment]
@thasherwin Yes, it is.

**Comment by asolntsev** [comment]
@rosolko @thasherwin yes, it looks nice.
It would be great to integrate it with Selenide. Let's do it!

**Comment by rosolko** [comment]
@asolntsev It seems that it is all the necessary changes. Please close look at the [commit](https://github.com/rosolko/selenide/commit/a97b8e15bd407b331e9518c42880a8be603cdcc5)

**Comment by BorisOsipov** [comment]
done https://github.com/codeborne/selenide/pull/610
