### ISSUE TITLE
how to get window handles

### ISSUE THREAD

**Issue by antomanjooran** [codeborne/selenide#421]
In selenium we can use driver.getwindowHandles(), which is will return the window handles.
how can we use it in selenide

**Comment by kenston** [comment]
If you know the window title or the index, you can use `Selenide.switchTo().window`. Alternatively, you can get hold of the underlying `WebDriver` by using `WebDriverRunner.getWebDriver()`.

**Comment by asolntsev** [comment]
@kenston Thank you, this is a duplicate.
@antomanjooran You can use this method:

```java
Set<String> handles = getWebDriver().getWindowHandles();
```
