### ISSUE TITLE
shouldBe vs waitUntil

### ISSUE THREAD

**Issue by kemuning** [codeborne/selenide#424]
Is there a recommendation when to use `$(selector).shouldBe(Condition.visible).click()` and when with  `$(selector).waitUntil(visible, 5000).click()` ?

**Comment by asolntsev** [comment]
@kemuning The recommendation is to write even simpler code:
```java
$(selector).click();
```

This is the best. The `click` method automatically waits until element gets visible.

P.S. I recommend to avoid using method `waitUntil` in most cases. You only need it if you want to set specifically special timeout for some operation. You don't need it most of the time.
