### ISSUE TITLE
Consider adding SelenideElement#followingSibling

### ISSUE THREAD

**Issue by yashaka** [codeborne/selenide#429]
Since we have `SelenideElement#parent`
why not to have `.followinSibling()` instead of `.find(byXpath("./following-sibling::*"))`? ;)

and probably other similar methods...

**Comment by asolntsev** [comment]
@yashaka Why not? Let's do it!

**Comment by yashaka** [comment]
Seems like, it will be also a good idea to implement all other corresponding "shortcut methods", like firstChild, etc.
We can take as a refference this document: http://scraping.pro/res/xpath-cheat/xpath_css_dom_recipes.pdf
and implement shortcuts for almost everything (where appropriate) from Parent&Child and Sibling sections
![image](http://picpaste.com/pics/Screen_Shot_2017-01-07_at_1.10.27_AM-bXmEkVib.1483769643.png)
