### ISSUE TITLE
Possibility to set webDriver's capabilities through the Configuration

### ISSUE THREAD

**Issue by juliaviluhina** [codeborne/selenide#431]
It would be convenient if setting webDriver's capabilities(or some capabilities)  was available through the Configuration. And webDriver (created automatically by Selenide) could use this information about capabilities from Configuration.
Could you add this feature, please?

For example

In Selenide 4.x (and in Selenium 3.x) 
It can be possible to use old versions Firefox (v<48) with Firefox webDriver
For this purpose, capability "marionette" should be set as false, and these capabilities should be used in webDriver creation.

According [to Wiki page "How Selenide creates WebDriver"](https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver)
two described options work correctly.

Option 1 - custom creation Firefox webDriver
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("marionette", false);
        setWebDriver(new FirefoxDriver(capabilities));
However, custom webDriver creation requires custom webDriver closing.

Option 2 - usage factory that implements interface WebDriverProvider

Both these methods are not easy to understanding for beginners and a bit bulky.

**Comment by asolntsev** [comment]
Hi @juliaviluhina !
Thank you for the ticket, but isn't it a duplicate of #397 ?

**Comment by juliaviluhina** [comment]
Hello @asolntsev  )
Yes, you are right, it is a duplicate of #397
I close my ticket

**Comment by vinogradoff** [comment]
@juliaviluhina 4.2 has solution for both using firefox without marionette and adding any arbitary capability via command line (SystemProperties)
