### ISSUE TITLE
Is it possible to do steps until condition

### ISSUE THREAD

**Issue by nick318** [codeborne/selenide#437]
Hi there,

Is it possible to do something like that:

$("locator").setValue("text").until(myCustomCondition);
$("locator").click().until(checked);

It means, that if condition.apply returns false, the whole chain will be invoked again.

It's really usefull when you are working with IE driver, because of his implementation some actions don't trigger from first invokation.

Or if you can suggest a better idea for that, I am looking forward your reply.

**Comment by anyone-can-test** [comment]
I like this functionality.
In my case, it needs to click again and again until text in other element is equal to a expected text.
For example, $("button").click().until(other element condition);

**Comment by anyone-can-test** [comment]
This is my code for clicking again until a condition is met.

```java
clickAgainUntil($("#srch-btn"), $("#logsCount"), text("10 logs"), 10);

void clickAgainUntil(SelenideElement clickElement, SelenideElement conditionElement, Condition condition, int timeoutSeconds) throws Exception {
	
	for(int i = 0; i < timeoutSeconds; i++) {
		System.out.println("try " + i);
		try {
			clickElement.click();
			System.out.println(conditionElement.getText());
			conditionElement.waitUntil(condition, 1000);
		}catch(ElementShould | ElementNotFound e) {
			//e.printStackTrace();
			continue;
		}
		return;
	}
	throw new Exception("condition not met");
}
```

**Comment by iCok** [comment]
@anyone-can-test Of course I have my own a solution for that. But I suggest a new feature to selenide. Because many people who use IE driver, have their custom solution for one problem. In order to avoid it, I want to see it in selenide :)

My custom solution looks like:


Action
.withTimeout(timeout)
.call(driver -> {
$(locator).setValue("text")
return hasValue("text")
});

It's just an example.

**Comment by asolntsev** [comment]
@iCok You solution looks good actually. 

Probably it could look like this in Selenide:
```java
$(locator)
  .retry(se -> se.setValue("text"))
  .until(se -> se.hasValue("text"));
```

What do you think?

**Comment by iCok** [comment]
It looks nice, but we need at least 2 methods for condition: 
First one will be throw an exception when time is exceeded, another one will return boolean value because sometimes we need write one condition inside another one, so to avoid try catch hell boolean value will good solution
