### ISSUE TITLE
setValue() method does not work with iFrame

### ISSUE THREAD

**Issue by vkondin** [codeborne/selenide#438]
Hello, 

We discovered, that setValue method does not work for iFrame body element, however it works with selenium original method (sendKeys()).

**HTML:**
```
<iframe id="mce_0_ifr" frameborder="0" allowtransparency="true" title="Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help" src='javascript:""' style="width: 100%; height: 150px; display: block;">
<html>
<head>
....
</head>
<body id="tinymce" class="mce-content-body " data-id="mce_0" contenteditable="true"><br data-mce-bogus="1"> TEXT HERE</body>
</html>
</iframe>
```
**Code:**
```
switchTo().frame("mce_0_ifr");
$("#tinymce").setValue(projectDesciption);
switchTo().defaultContent();
```

**Debug results:**
Selenide switched to iFrame and found choosen selector (#tinymce).
Problem occured in SelenideElementProxy.class (Else condition was triggered ...)
```
public Object invoke(Object proxy, Method method, Object... args) throws Throwable {
        if (methodsToSkipLogging.contains(method.getName())) {
            return Commands.getInstance().execute(proxy, this.webElementSource, method.getName(), args);
        } else {
            ErrorsCollector.validateAssertionMode();
            long timeoutMs = this.getTimeoutMs(method, args);
            long pollingIntervalMs = this.getPollingIntervalMs(method, args);
            SelenideLog log = SelenideLogger.beginStep(this.webElementSource.getSearchCriteria(), method.getName(), args);
            try {
                Object error = this.dispatchAndRetry(timeoutMs, pollingIntervalMs, proxy, method, args);
                SelenideLogger.commitStep(log, EventStatus.PASS);
                return error;```

**Comment by iCok** [comment]
Hi,

I did not catch the idea of setting value to body element. It's neither input nor text area, why do you need to set value to this element?

Actually selenium sendKeys() method also does not work, but without any exceptions, because selenium just sends keydown events. Selenium does not modify html code in that case.

But therefore I have a work around if you really need to do so:

Selenide.switchTo().defaultContent();
Selenide.switchTo().frame("mce_0_ifr");
SelenideElement body = $(By.tagName("body"));
Selenide.executeJavaScript("arguments[0].innerHTML=arguments[1]", body, "testValue");

**Comment by vkondin** [comment]
Hi Nikita,

Thank you for answer. 
>  why do you need to set value to this element?
Because it was done so and I doubt, that developers will "improve" it.

Screenshot from the product.
![image](https://cloud.githubusercontent.com/assets/13762206/21131753/0a1207f6-c119-11e6-9cca-3a5afee575cd.png)

> Actually selenium sendKeys() method also does not work. 
It works for us as a workaround. (Selenide version 4.0/4.1, selenium-api 3.0.1)

**Comment by vinogradoff** [comment]
Cool, I think I've just seen that framework somewhere in my other project. It is totally crazy, but works 😀
Thank you for the interesting example. 
We will think it over!


Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by rosolko** [comment]
@vkondin `setValue` method changes a lot, if you still affect by this issue try to update and retests and if it reproduce feel free to reopen issue.
