### ISSUE TITLE
Adding descriptive message to CollectionCondition

### ISSUE THREAD

**Issue by jaagupkymmel** [codeborne/selenide#440]
I couldn't find a way to add descriptive messages to `CollectionCondition` objects, while `Condition` objects have the `because(String message)` method, which does exactly that. This means, when I write `$("#foo").should(Condition.exist.because("REASONS"));`, which when fails, outputs 
```
Element not found {#foo}
Expected: exist (because REASONS)
```
I would also like the ability to write `$$(".foo").shouldHave(CollectionCondition.size(1).because("REASONS"));`, which should output something like 
```
ListSizeMismatch : expected: = 1, actual: 0, collection: .foo
Elements: [] (because REASONS)
```
Right now, the best I can do, is `$$(".foo").shouldHave(CollectionCondition.size(1));`, which outputs 
```
ListSizeMismatch : expected: = 1, actual: 0, collection: .foo
Elements: []
```
which in turn isn't descriptive enough.

**Comment by asolntsev** [comment]
Will be released in Selenide 4.12.2
