### ISSUE TITLE
Angular integration - need a hook to call javascript before any action

### ISSUE THREAD

**Issue by rcomblen** [codeborne/selenide#441]
I'd like to implement with Selenide features that are provided by Protractor for testing Angular apps.

Protractor runs a piece of javascript in the browser to tell whether Angular is done with its logic.

That ensures you the tests won't interact with the browser while an AJAX request is running, or when the change detection cycle is running.

That is easy to do (in this case for Angular2, logic is similar for Angular 1), with something like

    public void waitForAngular() {
        getWebDriver().manage().timeouts().setScriptTimeout(5, TimeUnit.SECONDS);
        ((JavascriptExecutor) getWebDriver()).executeAsyncScript(waitForAngularScript);
    }

And the content of `waitForAngularScript` being:

    var callback = arguments[arguments.length - 1];
    if(!window.hasOwnProperty('getAllAngularTestabilities')){
        callback(true);
    }
    else{
        window.getAllAngularTestabilities()[0].whenStable(function() {
            callback(true);
        });
    }

Now, what I would like is to be able to have my `waitForAngular` method called before any interaction with the browser. Is there any chance to have such a feature ? It would be great if I could register a hook to be called before each interaction with the browser.

**Comment by iCok** [comment]
In order to solve your problem, have a look to: http://toolsqa.com/selenium-webdriver/event-listener/

**Comment by asolntsev** [comment]
@rcomblen You can use the following method:

```java
  WebDriverListener.addListener(new AbstractWebDriverEventListener() {
    @Override
    public void beforeClickOn(WebElement element, WebDriver driver) {
        waitForAngular();
    }
  });
```

**Comment by rcomblen** [comment]
Thanks. There is a typo in your code snippet, I guess you meant:

    WebDriverRunner.addListener(new AbstractWebDriverEventListener() {
        @Override
        public void beforeClickOn(WebElement element, WebDriver driver) {
            waitForAngular();
        }
    });

**Comment by asolntsev** [comment]
@rcomblen Yes, I had a typo. Thank you.
