### ISSUE TITLE
Consider adding alias Selenide.assertThat instead of Selenide.Wait().until

### ISSUE THREAD

**Issue by yashaka** [codeborne/selenide#450]
Selenide states it is an abstraction over low-level technical details. 

But code like:
```
        Selenide.Wait().until(titleIs("Selenide: concise UI tests in Java"));
```
still contains some "non-user-friendly-language-of-waits"

Why not create an alias for Wait().until(...) like this:

```
        Selenide.assertThat(titleIs("Selenide: concise UI tests in Java"));
```

?

:)

**Comment by asolntsev** [comment]
I am not sure it's a good idea because people are used to use `assertThat` as a typical "JUnit" or "TestNG" method that doesn't wait for anything. It would be surprising behaviour of `assertThat ` method for people.

**Comment by yashaka** [comment]
It's the same way "suprising" that SelenideElement#find will wait, and
"should" will also wait... ;-)

**Comment by rosolko** [comment]
`assertThat` can confuse user if it will be static imported.
For example if can be messed up with `AssertJ`, that isn't assume wait until assert.
