### ISSUE TITLE
Selenide 3.11 git tag doesn't exist

### ISSUE THREAD

**Issue by BorisOsipov** [codeborne/selenide#451]
Hi @asolntsev,

It looks like there is no git tag for 3.11 release.
Could you please fix it? :)

Thanks in advance!

**Comment by asolntsev** [comment]
Hi!
Yes, sure. I will add tag for selenide 3.11

P.S. why do you need it? Why not upgrade to the latest version?

**Comment by BorisOsipov** [comment]
Thank you@asolntsev!
It needs because it isn't possible to use java 8 :) It's an open source project and they haven't moved on java 8 yet. 

I think to backport some bug-fixes\features from master to 3.11. I haven't tried it yet, but I will try.
Can we release 3.11.X or 3.12 with bugfixes still on java 7?  What do you think? Did somebody already ask to do so?

**Comment by asolntsev** [comment]
Sorry for the long delay.
I have created tag *selenide-3.11*

Andrei Solntsev

2017-01-08 23:01 GMT+02:00 Boris Osipov <notifications@github.com>:
