### ISSUE TITLE
need help about screenshot

### ISSUE THREAD

**Issue by anyone-can-test** [codeborne/selenide#452]
This may not be related to Selenide.
Screenshot is saved on every test fail.
In the screenshot, Korean text in some elements is empty. English, number text are visible.
In more details, all elements within iframe have empty text, but all elements in parent window have proper text (Korean).

What should I do for finding the cause?

**Comment by vinogradoff** [comment]
That’s kindda strange. Which browser? Which webdriver? It must be a problem with browser/driver or it’s combination I’m afraid, not even Selenium problem (probably).

**Comment by anyone-can-test** [comment]
I use Selenium server (Linux) + chrome driver (almost the latest version) + xvfb.
In my local (Windows + chrome driver), Korean text is visible in screenshot.

**Comment by vinogradoff** [comment]
From my point of view - https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidscreenshot <https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidscreenshot> implementation in chromedriver on linux with combination of your chrome browser works wrong.
So it’s a ticket for them. I don’t think you can do something about it yourself (update to latest chromedriver though, it never hurts to try)

**Comment by anyone-can-test** [comment]
I found out finally the problem.
Simply, it was that Korean font in Linux was missing.
