### ISSUE TITLE
Will selenide wait for the next action until no api requests are active ?

### ISSUE THREAD

**Issue by rahulr892** [codeborne/selenide#453]
Will selenide wait for the next action until no api requests are active like in protractor for angular web apps to handle synchronisation issues.
I am just curious. Selenide looks great and I am thinking of using it in my next automation project.
Thanks

**Comment by vinogradoff** [comment]
Selenide doesn't depend on any specific JavaScript implementation like protractor/angular. The "magic" is - Selenide just waits if element not there or re-search if element is stale, no matter why. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by asolntsev** [comment]
So, yes, feel free to try Selenide in your next project.
Selenide should work with any JS library.

Andrei Solntsev

2017-01-14 3:02 GMT+02:00 Alexei Vinogradov <notifications@github.com>:
