### ISSUE TITLE
Implicite wait

### ISSUE THREAD

**Issue by apreg** [codeborne/selenide#460]
Does` $("")` method wait implicite for the element to appear? I guess it does but wanna be sure.
I think `should` is overengineering in this case right?
`$("select[name='swimlanes']").should(Condition.exist).exists();`
Sorry for the noob questions.

**Comment by vinogradoff** [comment]
$(„“) does not do any search at all! It just *defines* locator of element.

but .should* all wait Configuration.timeout ms (it is not the same technology as in implicity Selenium-Waits, though.It is better one! But in general it works like implicit wait, yes.

$(„…“).should(Condition.exist); // no .exists() at the end

Better to static import Condition.*, then you have

$(element).should(exist), $(element).shouldBe(visible), $(element).shouldHave(text(„Ahoi“)) etc.

with nice readability.

**Comment by apreg** [comment]
`  /**
   * Find the first element matching given CSS selector
   * @param seleniumSelector any Selenium selector like By.id(), By.name() etc.
   * @return SelenideElement
   */
  public static SelenideElement $(By seleniumSelector) {
    return getElement(seleniumSelector);
  }`
I'm confused.
The problem for me with your proposed solution is that I need to give back a boolean but should gives back the element itself. So my final goal is to check whether an element is present with a little waiting.

**Comment by vinogradoff** [comment]
Thank you it is indeed inconsistency in the docs! But it doesn’t search, believe me. 
We’ll change this javadocs for better with new version!

Why do you need to get boolean back? Don’t you want to check if element is there?

use element.shouldBe(visible) for the most cases.
If you really want to wait more than standard for your apps (4-5 secs is typical for the most apps), you can do with

element.waitUntil(visible, 30000); // it is the same as shouldBe, but waits up to 30 seconds

**Comment by apreg** [comment]
I believe you ;) 

> Defining SelenideElement doesn’t trigger the search in DOM yet, so you can save the locators in variables for later use at any place. With a SelenideElement instance, you can either do action with it (click, setValue etc.) or check a condition: shouldHave(text("abc")). Both will trigger the search of the elements in DOM.

> Why do you need to get boolean back? Don’t you want to check if element is there?

In my pageobject there are helper methods which give back boolean for what I can assert and give custom error message in the test spec class.

So If I get it correctly if I want to wait for an element I should use `should` or `waitUntil` or maybe action like `click`.
I know I have other options too but these are the most prefered ones. To check whether the title is correct I use this method:
`Wait().until(ExpectedConditions.titleContains("New View"));`
To check page source I use this:
```
Wait().until(new Function<WebDriver, Boolean>() {
            @Nullable
            @Override
            public Boolean apply(@Nullable WebDriver input) {
                return source().contains(textToContain);
            }
        });
```

**Comment by asolntsev** [comment]
@apreg Please don't call `exists()` and return boolean. It's just nonsense.
Look, we have 2 options:
1. The element exists. In this case `$("...").should(exist).exists();` always returns `true`.
2. The element doesn't exist. In this case ``$("...").should(exist)` throws an exception.

So, your method will never return false. And this is good. You test will either work or fail. Green or red. That's enough.

If you want to use custom error message in case of test failure, you can do it like this:
 `$("#lastLogin").should(exist.because("Last login should be shown for security reasons"));`
