### ISSUE TITLE
Working with several web driver instances

### ISSUE THREAD

**Issue by fancywriter** [codeborne/selenide#463]
Is it possible to work with several (more than one) web driver instances?
As far as I see after brief look to the documentation, I have to use static imports
```
import static com.codeborne.selenide.Selenide.*
import static com.codeborne.selenide.Condition.*
```
On the first invocation of any method of Selenide DSL the real instance of web driver is created (together with browser firefox/chrome/???). However, I need to open several browser with different sessions (let's say I want to test interaction between different uses of the same application) with cookies. How to do that? Is is possible?

I **would be** possible if I bind every `open`/`click`/`???` to the context, which refers to the specific web driver.

**Comment by asolntsev** [comment]
Hi @fancywriter !
Currently it's not easy, and I recommend not to use 2+ browsers in test. If you need to test integration between user, I recommend to mock the second user's behaviour. It makes your tests fast and stable. 

Though, there is issue https://github.com/codeborne/selenide/issues/354 that suggests to implement 2+ browsers in Selenide. Probably we will do it soon.
