### ISSUE TITLE
exists() crashing when checking element that came from ElementsCollection.find()

### ISSUE THREAD

**Issue by jaymagpantay** [codeborne/selenide#465]
Recently upgraded from Selenide 3.7 to 4.2.1 and noticed that a bunch of my tests started failing. We do a lot of things like below: 
```
SelenideElement s = someElementsCollection.find(Condition.text(textgoeshere));    
return s.exists();
```
I am finding that the second line works if the element exists, but will crash if it is not found. I know that the find method used to be implemented as 'return someElementsCollection.filter(Condition).get(0)`, but was changed at some point. 

We can change all of our finds to just use the filter method, but this will take a bit of work. Is there any way to get the old functionality back and have it work properly with exists()?

**Comment by juliaviluhina** [comment]
We are working on this error.

**Comment by jaymagpantay** [comment]
Great, thank you. Is there an ETA by any chance?

**Comment by asolntsev** [comment]
@jaymagpantay @juliaviluhina pull request #466 has been merged. We will release it tonight.

**Comment by asolntsev** [comment]
@jaymagpantay @juliaviluhina Selenide 4.3 has been released. Can you try if it solves your problem?

**Comment by jaymagpantay** [comment]
@asolntsev @juliaviluhina Thank you! We will try the fix early next week and will let you know.
