### ISSUE TITLE
GitHub project page has several broken links

### ISSUE THREAD

**Issue by dialex** [codeborne/selenide#468]
@vinogradoff, several badges are broken, have a look at the screenshot below:

![screen shot 2017-02-09 at 15 04 09](https://cloud.githubusercontent.com/assets/2140450/22788853/0cf5b0a6-eed9-11e6-994d-26bc2180bd06.png)

**Comment by asolntsev** [comment]
@dialex I cannot reproduce the problem. Currently I see all the badges: 
![image](https://cloud.githubusercontent.com/assets/279773/22804962/102e52e6-ef24-11e6-935e-4bebb07224b1.png)

**Comment by dialex** [comment]
Sorry, my bad, I was behind a proxy/firewall.
