### ISSUE TITLE
Drag&Drop sometimes doesn't work

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#471]
http://the-internet.herokuapp.com/drag_and_drop

   ` $("#column-a").dragAndDropTo($("#column-b"));`

unfortunately did not do the trick (Firefox legacy, Chrome tested)

**Comment by vinogradoff** [comment]
It is a know problem with Selenium - HTML5 draggable does not work as of today

**Comment by symonk** [comment]
small update, I still think there is universal drag and drop issue(s) with selenium itself.  I opened https://github.com/SeleniumHQ/selenium/issues/6235.  as of the chrome team:

```
ChromeDriver doesn't yet support the Actions commands. The Java language binding translates the Actions requests into corresponding mouse events before sending them to ChromeDriver, however there is no guarantee the translated mouse events are completely equivalent to the original Actions request.

Implementing Actions commands is on our to-do list, but there is no ETA yet.
```

**Comment by asolntsev** [comment]
@symonk Thank you for sharing. So, closing this issue for now.
