### ISSUE TITLE
can you open the setting for close the browser

### ISSUE THREAD

**Issue by fox4it** [codeborne/selenide#472]
can you open the setting for close the browser?

if i debug my test cases, i don't want to close the browser after test completed

**Comment by rmarinsky** [comment]
UseL Configuration.holdBrowserOpen = true;

**Comment by vinogradoff** [comment]
Or -DholdBrowserOpen=true :)

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by fox4it** [comment]
get it，thanks all
