### ISSUE TITLE
Compatibility issue with Spring

### ISSUE THREAD

**Issue by Serzh90** [codeborne/selenide#473]
I was using selenide together with spring-boot-starter-amqp, both have xerces library as a dependency and  gradle was using the one from selenide.  As the result mq client was serializing messages with the wrong library, which cased errors on the receiving end.
Dependecy example:
spring-amqp-1.6.5.RELEASE
selenide:4.0

**Comment by biomaks** [comment]
Why not to ask Spring devs to solve this dependency issue? :) Honestly speaking your use case is pretty rare.

**Comment by ddemin** [comment]
Why are you create an issue at Selenide project ? =)
It is a just problem of dependencies resolving which you can fix at build.gradle (see Gradle docs)

**Comment by vinogradoff** [comment]
With gradle you can use very different  conflict resolution strategies and don’t ask spring or selenide developers to synchronize :)

https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_resolution <https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_resolution> and on…

Please, close issue, if the answer suits you.

**Comment by Serzh90** [comment]
Thanks for fast reaction. The use case is really rare however xerce and it's variations are used very widely so the problem might appear with any spring component as well as with the other frameworks. I'll try suggestion from @vinogradoff .

**Comment by vinogradoff** [comment]
no problem. You can actually never know which version is the „right“ one. Sometimes it doesn’t work when your lib is too old, and sometimes when it is too new.
