### ISSUE TITLE
How to select all the options in select dropdown

### ISSUE THREAD

**Issue by sagarzlp** [codeborne/selenide#474]
With selenium new Select().getOptions() I can fetch all the option in select dropdown. I do not see such method exists in **Selenide API**. I want to iterate through the options before selecting one.
Could someone help?

**Comment by biomaks** [comment]
Hi,
You can use following methods:
`$("selector").selectOptionByValue(String... value); // by value from dropdown list`
`$("selector").selectOption(int... index); // by index from dropdown list`
`$("selector").selectOption(String... text); // by text from dropdown list`
`$("selector").selectOptionContainingText(String text); // by  containing text from dropdown list`

**Comment by biomaks** [comment]
Feel free to close the issue if my answer was helpful

**Comment by vinogradoff** [comment]
If you are sure, you want to iterate through your options (why should you) - you can just use $$(selector) to get Collection of options to iterate through it.

**Comment by asolntsev** [comment]
@sagarzlp Currently we don't have method `$("select").options()` in Selenide. Probably we could add it. But probably it's not a best way: iterating can be slow. You could select the desired option using xpath, text or value. It's definitely a better way. Did @biomaks suggestions help you?

**Comment by rosolko** [comment]
@sagarzlp Is solution provided by @biomaks help to you?

**Comment by VasaviUppada** [comment]
How to select options for hidden elements? 
With Selenium, I used make them as visible at runtime & then selected options. 
How to proceed with Selenium in this scenario?

Here is my HTML Tag : 

<div class="stylize" css="1">
    <select id="numberOfPeopleSelect" title="Number of people" style="display: none;">
        <option value="2" data-menu-rule-id="2" data-description="Easy, delicious recipes for 2 adults." selected="selected">2 people (Classic Menu)</option>
        <option value="3" data-menu-rule-id="3" data-description="Easy, delicious recipes for 4 adults.">4 people (Classic Menu)</option>
        <option value="1" data-menu-rule-id="1" data-description="Quick, kid-friendly recipes for a family of 4.">4 people (Family Menu)</option>
    </select>
    <p class="selVal clicked" style="">2 people (Classic Menu)<span class="caret"></span></p>
    <ul class="stylizeul" style="display: none;">
        <li class="option">
            <a data-value="2" href="#" class="selected" rel="nofollow">
                <p class="dropdown-text">2 people (Classic Menu)</p><p class="text-xs gray-medium">Easy, delicious recipes for 2 adults.</p>
            </a>
        </li>
        <li class="option">
            <a data-value="3" href="#" rel="nofollow">
                <p class="dropdown-text">4 people (Classic Menu)</p>
                <p class="text-xs gray-medium">Easy, delicious recipes for 4 adults.</p>
            </a>
        </li>
        <li class="option" style="border-bottom: none;">
            <a data-value="1" href="#" rel="nofollow">
                <p class="dropdown-text">4 people (Family Menu)</p>
                <p class="text-xs gray-medium">Quick, kid-friendly recipes for a family of 4.</p>
            </a>
        </li>
    </ul>
</div>

**Comment by VasaviUppada** [comment]
Hi @rosolko ,
I can able to choose option using executeJavaScript("$('#numberOfPeopleSelect').attr('style','display:block;')") for my 1st dropdown box.
I have 2 more dropdown boxes which options will change dynamically based on 1st dropdown option selection.
Meaning, If I choose Option-**1** for Dropdown-**A**,  I'll get Options *a,b,c* for Dropdown-**B** 
& If I choose Option-**2** for Dropdown-**A**,  I'll get Options **x,y,z** for Dropdown-**B** 

In this scenario, after selecting, Option-**2** from Dropdown-**A**, my Dropdown-**B** is not getting updated with options-**x,y,z**, instead it is continuing with old Options **a,b,c**.

Here is the HTML code for my next dropdown box : 
```
<div class="col-sm-6" id="number-of-meals-container">
    <p class="semibold text-sm form-label">Default recipes / week</p>
    <div class="stylize">
        <select id="numberOfMealsSelect" class="float-left" style="display: none;">
            <option value="2" data-description="" selected="selected">2 recipes</option>
            <option value="3" data-description="">3 recipes</option>
            <option value="4" data-description="">4 recipes</option>
        </select>
        <p class="selVal clicked">2 recipes<span class="caret"></span></p>
        <ul class="stylizeul" style="display: block;">
            <li class="option">
                <a data-value="2" href="#" class="selected" rel="nofollow">
                    <p class="dropdown-text">2 recipes</p>
                    <p class="text-xs gray-medium"></p>
                </a>
            </li>
            <li class="option">
                <a data-value="3" href="#" rel="nofollow">
                    <p class="dropdown-text">3 recipes</p>
                    <p class="text-xs gray-medium"></p>
                </a>
            </li>
            <li class="option" style="border-bottom: none;">
                <a data-value="4" href="#" rel="nofollow">
                    <p class="dropdown-text">4 recipes</p>
                    <p class="text-xs gray-medium"></p>
                </a>
            </li>
        </ul>
    </div>
</div>
```
```
	public void selectOptionForHiddenElements(WebElement hiddenElement, WebElement optionElement){
		((JavascriptExecutor)getDriver()).executeScript("$(arguments[0]).show();", hiddenElement);
		((JavascriptExecutor)getDriver()).executeScript("$(arguments[0]).prop('selected', true).change();", optionElement);
	}
```

This is the method I used for selenium. Is there any better way to proceed with **selenide**

**Comment by rosolko** [comment]
@VasaviUppada 
No. There aren't. 
It's super individual case.
You can only replace `((JavascriptExecutor)getDriver()).executeScript` with `Selenide.executeScript` and made import for `Selenide` and leave only `executeScript`.

**Comment by rosolko** [comment]
@VasaviUppada Btw `<ul class="stylizeul" style="display: block;">` also hidden and before selection you can try to change style for this ul and then try to select option with selenide.

**Comment by VasaviUppada** [comment]
@rosolko 
Thanks much!
Can able to select option now. Here is the code which I used...

```
        executeJavaScript("$('#numberOfPeopleSelect').attr('style','display: block;')");
        $("#numberOfPeopleSelect").selectOption("4 people (Family Menu)");
        executeJavaScript("$('#numberOfMealsSelect').attr('style','display: block;')");
        $("#numberOfMealsSelect").selectOption("3 recipes");

```
