### ISSUE TITLE
FeatureRequest: add CollectionsCondition textsInAnyOrder(String...)

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#478]
$$().shouldHave(text(String...)) requires that **all** texts of collection are given as parameter.

If collection is "June","July","August" - then $$().shouldHave(text("July")) fails.

New method textsInAnyOrder should pass $$().shouldHave(textsInAnyOrder("July")) and $$().shouldHave(texstInAnyOrder("July", "June")) for that matter.

**Comment by AleksanderPopov** [comment]
@vinogradoff , may be in this case point about part of list also important? I mean that name 'textsInAnyOrder' contains not order-insensitivity check, but also size-insensitivity (texts and exactTextx do size-sensative).
May be 'containsTextsInAntOrder' will be better ?

**Comment by vinogradoff** [comment]
normally it would go mit shouldHave(textsInAnyOrder….) - looks find for me

**Comment by AleksanderPopov** [comment]
@asolntsev , how do you think?

**Comment by asolntsev** [comment]
@vinogradoff @AleksanderPopov We can implemented it, thought I don't see a real case whn it could be useful. I believe you should always exactly know what it expected behaviour of SUT, including order of texts.

**Comment by mseele** [comment]
Something like hasItems in Hamcrest would be very usefull. Because sometimes you only want to check if a ElementsCollection contains a subset of all texts...

**Comment by hyunil-shin** [comment]
I like this functionality. Sometimes, order of texts does not matter in tests.

**Comment by asolntsev** [comment]
@mseele @hyunil-shin Probably. Why not. Somebody could prepare a pull request.

(Thought, I still don't see a real case when it could be useful...)

**Comment by asolntsev** [comment]
Was implemented in PR #589 and released 2.04.2018 in Selenide 4.11.0
