### ISSUE TITLE
Failed tests have to contain correct Error message in case when using of Selenide + Appium

### ISSUE THREAD

**Issue by egorvas** [codeborne/selenide#480]
### Env

- Appium 1.6.3

- Selenide 4.3

- Maven

### Issue

Every time when user get an fail report from selenide it contains error message, for example:
```
Failed tests: 
  SelenideTests.alertTest:35 Element should hidden {By.id: message}
Element: 'WebDriverException: Method has not yet been implemented'
```

Also same issue can be easly reproduced by performing:

> System.out.println($(By.id("your_element")).toString());

Seems that SelenideElement not able to perform toString operation on elements obtained by AndroidBrowser

**Comment by asolntsev** [comment]
@egorvas thank you for reporting! It has been fixed in Selenide 4.4, see https://github.com/codeborne/selenide/issues/494
