### ISSUE TITLE
getJavascriptErrors doesn't return errors

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#485]
``` 
    open("http://the-internet.herokuapp.com/javascript_error");
    List<String> jsErrors = getJavascriptErrors();
    System.out.println(jsErrors);
    assertNoJavascriptErrors();
 ````
This should return one JavaScript error (Cannot read property 'xyz' of undefined), but it doesn't (Firefox 45)

**Comment by asolntsev** [comment]
Yes, method `getJavascriptErrors` has some restrictions. Namely, it only catches JS errors that happens AFTER page loading. Unfortunately it's not technically possible to catch JS errors during page loading with Selenium.

As far as I know, the only way to do it is to use proxy server and inject custom JS code into the server HTML response.
