### ISSUE TITLE
getJavascriptErrors causes exceptions when element is not found in native app on Android

### ISSUE THREAD

**Issue by dkorobtsov** [codeborne/selenide#486]
Researching how Selenide and Appium are working together.
In general, everything works just fine, except for error handling.
Every single time the following line of code is called:

selenide/src/main/java/com/codeborne/selenide/ex/UIAssertionError.java

  protected String uiDetails() {
    return screenshot(screenshot) + jsErrors(jsErrors) + timeout(timeoutMs) + causedBy(getCause());
  }

Appium shows an exception:

Feb 25, 2017 10:58:02 PM com.codeborne.selenide.Selenide getJavascriptErrors
SEVERE: org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)

Wonder if there are any option to turn getJavascriptErrors feature off?

**Comment by asolntsev** [comment]
@dkorobtsov Hi! Actually it's just a log message. Everything still works. As a quick workaround, you can just ignore this log (add a line to log4j configuration).

As a long-term solution, we need to disable getJavascriptErrors feature for Appium. Can you prepare a pull request?

**Comment by dkorobtsov** [comment]
It's not just a log message :) There are more then 100 lines long stacktrace in console and log for every single "element not found" event. Even if it's expected. Not only it's very annoying but also significantly complicates debugging process.

As for pull request - still not sure how to fix this... Suppose something like this would solve the problem for Android native apps:
```
protected String uiDetails() {
     if (WebDriverRunner.getWebDriver() instanceof AndroidDriver) {
        return screenshot(screenshot) + timeout(timeoutMs) + causedBy(getCause());
     } else {
        return screenshot(screenshot) + jsErrors(jsErrors) + timeout(timeoutMs) + causedBy(getCause());
     }
}
```

**Comment by asolntsev** [comment]
@dkorobtsov I have committed the fix. Please review: https://github.com/codeborne/selenide/commit/b4d2cf900bd1c403fbe4f4a600873fbca8bade10

**Comment by dkorobtsov** [comment]
Should work as well, thanks a lot! I'll test changes on my environment and post an update.
