### ISSUE TITLE
Add support for JUnit5

### ISSUE THREAD

**Issue by rmarinsky** [codeborne/selenide#488]
I've already succefully triyed it in repo: https://github.com/rmarinsky/JUnit5SelenideGradle
Have you any suggetions how to simplify support both versions of junit?

**Comment by SergeyPirogov** [comment]
@rmarinsky show to run test for both junit version described in JUnit 5 docs http://junit.org/junit5/docs/current/user-guide/#running-tests-junit-platform-runner

**Comment by asolntsev** [comment]
@rmarinsky @SergeyPirogov Do we really need to change something in Selenide to support JUnit5? 
I think Selenide should be test runner agnostic...

**Comment by SergeyPirogov** [comment]
No, we don't need to do any changes.
