### ISSUE TITLE
$x("xpath") support

### ISSUE THREAD

**Issue by SergeyPirogov** [codeborne/selenide#489]
Chrome dev tools have suport for searching elements by xpath using command **$x("xpath locator")**

It's quite useful to have such alias in Selenide API:
Now:
 - **$(By.xpath("//a"))**
 - **$(xpath(""))**

Featured:
- **$x("//a")**

@rmarinsky  @asolntsev @vinogradoff What do you think?

**Comment by vinogradoff** [comment]
Sweet. Syntax Sugar - why not. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by egorvas** [comment]
Same can be perfect for $(By.id("")) =>> $i(""). This is useful for android devices

**Comment by vinogradoff** [comment]
No, $("#id") is short enough for me

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by egorvas** [comment]
$("#id") its for css selection, not for id what interesting for me in case of appium testing.

**Comment by vinogradoff** [comment]
I can't follow. You mean By.id and By.cssSelector(#..) brings different result on Android?

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by egorvas** [comment]
Yes, its what I mean.
public static final SelenideElement zoomInButton = $("#zoom_in");
Return error:
`org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session`
But
public static final SelenideElement zoomInButton = $(By.id("zoom_in"));
Return correct selenide element

**Comment by vinogradoff** [comment]
Okay, didn’t know that. Probably I should learn how to use selenium on mobile devices one day…

I would not like to make any quick decision on this topic yet. Perhaps it is better, if we transform $(„#zoom_in“) into $(ById(„#zoom_in“)) for mobile clients under the hood.
But it is just one quick idea, I think I must invest some time into automating on mobiles that I can understand the logic and problems with it.

**Comment by egorvas** [comment]
Feel free to contact me for any questions, Im using selenide for my mobile project and already found some bugs and must have features for correct appium support.

**Comment by SergeyPirogov** [comment]
Feel free to fix them in PR

**Comment by rmarinsky** [comment]
@SergeyPirogov good idea for implement $x(""), what about $i(), $n() - its cool idea for testing mobile apps  and do not use Selectors class, for example $(byText()), $(by("",""))
$t("qearyText")

**Comment by rmarinsky** [comment]
I can help for this pr

**Comment by SergeyPirogov** [comment]
I agree only with $x("") because it's Dev Tools  standard feature, all other is a mess

**Comment by SergeyPirogov** [comment]
@rmarinsky  Feel free to provide PR, but I think It will not be merged, because community splitted  ;)

**Comment by asolntsev** [comment]
I think we can implement `$x("//a")` because it works in Chrome devtools. Let's do it!

**Comment by BorisOsipov** [comment]
Done https://github.com/codeborne/selenide/pull/497
