### ISSUE TITLE
Google map automated test

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#490]
I want to make a test of adding markers on the Google map as automated test. but is there any way to do that using selenium OR selenide?

**Comment by vinogradoff** [comment]
I don’t know if this is a right kind of question for Issue in GitHub. Perhaps it is, but one more idea is to post in on StackOverflow, 
because, there are much more reading users who could have already solved this….

**Comment by asolntsev** [comment]
@hana9090 I recommend to google it. The question is not selenide-specific. 

E.g.: http://tech.adstruc.com/post/34230170061/selenium-testing-google-maps
