### ISSUE TITLE
Does selenide support safari browser on iPad

### ISSUE THREAD

**Issue by sagarzlp** [codeborne/selenide#492]
I am using Appium to run the test script in safari browser on real device. I am using IOSDriver provided by Appium library. Also, I found below browsers are supported in Selenide
https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver

Does anyone have know how to use IOSDriver with Selenide API?

**Comment by vinogradoff** [comment]
Selenide supports Safari browser on desktop, but as for mobiles - we didn't try it out yet, so there may well be problems:)

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by sagarzlp** [comment]
@asolntsev Need your help on this issue.

**Comment by asolntsev** [comment]
@sagarzlp Yes, Selenide supports Safari browser. 

You can create such class:

```java
public class CreateIOSDriver implements WebDriverProvider {
public WebDriver createDriver(DesiredCapabilities capabilities) {
  URL appiumUrl = null;
  try {
    appiumUrl = new URL("http://127.0.0.1:4723/wd/hub");
  } catch (MalformedURLException e) {
    fail(e);
  }
  return new IOSDriver(appiumUrl, capabilities);
  }
}
```

And use it: 

```java
setWebDriver((WebDriver) new CreateIOSDriver(capabilities));
Configuration.timeout = 35000;
```
