### ISSUE TITLE
Launching new browser sessions during shut down

### ISSUE THREAD

**Issue by kenston** [codeborne/selenide#493]
I have an application with `JFrame` set to exit the application upon closing:
```java
frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
```

I run this along with a Selenium Server and with some additional shutdown hooks under a multi-threaded test setup (i.e., multiple browser tested at a time).

After closing the Window but before JVM terminates, my shutdown hook will run, but new browser sessions are also created as can be seen in the Selenium Server logs and in the new browser windows being launched.

Is it because the old sessions were cleaned-up under Selenide's shutdown hook, but the Selenide actions are still in the middle of executing new Selenium commands that either find the existing browser session or otherwise launch a new browser session?

**Comment by asolntsev** [comment]
@kenston I really cannot know what happens in your tests. 
I guess you have some commands in your shutdown hook that try to access web elements or take screenshots. Therefore they are opening a new browser. 

P.S. It seems to be a huge overengineering. Why do you need a Swing application for running selenium tests???

**Comment by asolntsev** [comment]
@kenston Any reaction? Can we close the issue, or you want us to fix something?

**Comment by kenston** [comment]
@asolntsev I need some time to check this first. I'll have to ensure that no commands are being issued in my shutdown hooks. Thanks!

**Comment by kenston** [comment]
Hi @asolntsev,

I removed all my shutdown hooks and leave one shutdown hook that contains only `Thread.sleep(10 * 1000)` just to prevent the JVM from terminating immediately. I closed my JFrame to signal an exit and my shutdown hook runs. In this 10-sec period, new browser windows are launching as can be seen in the Selenium Web Server logs below.

My shutdown hook ran at 16:31:20.852. I can see that a Selenium command has just ended at 16:31:20.943 and new sessions are being created after.

```
16:31:20.391 INFO - Executing: [is selected: 18 [[[[FirefoxDriver: firefox on WINDOWS (...)]-> id: x.amount]] -> xpath: .//option[@value = "3"]]])
16:31:20.439 INFO - Done: [is selected: 18 [[[[FirefoxDriver: firefox on WINDOWS (...)] -> id: x.amount]] -> xpath: .//option[@value = "3"]]]
16:31:20.444 INFO - Executing: [click: 18 [[[[FirefoxDriver: firefox on WINDOWS(...)] -> id: x.amount]] -> xpath:.//option[@value = "3"]]])


16:31:20.943 INFO - Done: [click: 18 [[[[FirefoxDriver: firefox on WINDOWS (...)] -> id: x.amount]] -> xpath: .//option[@value = "3"]]]
16:31:20.953 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]])
16:31:20.958 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]
16:31:34.374 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]]
16:31:34.385 INFO - Executing: [maximise window])
16:31:34.456 INFO - Done: [maximise window]
16:31:34.466 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]])
16:31:34.469 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]
16:31:34.566 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]])
16:31:34.569 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]
16:31:46.466 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]]
16:31:58.840 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, pageLoadStrategy=normal, browserName=firefox}]]
```

Is it possible that Selenide's shutdown hook runs while a Selenide command is about to finish its execution resulting to a request for a new session?
