### ISSUE TITLE
Using confirm() returns NoSuchMethodError

### ISSUE THREAD

**Issue by rahusoov** [codeborne/selenide#498]
Versions:
selenide: 4.3
selenium-java: 3.3.1
guava: 21

Use case: 
`    public SignerListForm confirmExpectedAlert(){
        confirm("Expected text");
        return this;
    }`
Error: 
`java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
	at com.codeborne.selenide.Selenide.confirm(Selenide.java:502)
	at *SignerListForm.confirmExpectedAlert(SignerListForm.java:24)`

Is there some kind of version incompatibility? In selenium release notes there is mentioned that FluentWait.until was removed since 3.2.0

**Comment by karinamkl** [comment]
@rahusoov I have the same problem. In Selenium 3.2 method until in FluentWait class is deprecated and confirm() method in Selenide 4.3 is using it. I downgraded Selenium to version 3.0.1 as workaround and confirm() is working now for me because until is not deprecated in there yet.

**Comment by asolntsev** [comment]
Thank you!
Another workaround is to upgrade guava version. We will also do it in next
selenide version.

**Comment by karinamkl** [comment]
@asolntsev I tried selenium 3.3.1 and guava 21 and it didn't resolve issue with NoSuchMethodError. 
Looks like @rahusoov was using these versions too.

**Comment by thasherwin** [comment]
@asolntsev 
Will this issue be solved in version 4.4?

**Comment by asolntsev** [comment]
@rahusoov @karinamkl We found it out. It's the same problem as in issue #506 

It happens because Selenide 4.3 was compiled with selenium-java 3.0.1, but you use newer version selenium-java 3.3.1 (which introduced backward incompatibility). So it's expected behaviour.

I believe upgrading to Selenide 4.4 will solve your problem.

**Comment by asolntsev** [comment]
@rahusoov @karinamkl Hi! Selenide 4.4.1 is available via Maven Central repo.
Please prefer it to 4.4 if you use maven.
