### ISSUE TITLE
Not for CollectionCondition 

### ISSUE THREAD

**Issue by apreg** [codeborne/selenide#501]
Hi,
I'm looking for something like this:
`shouldHave(Condition.not(CollectionCondition.texts("Null")));` or
`shouldNotHave(CollectionCondition.texts("Null"))`
Is it possible somehow?
It would be handy I guess when I have e.g. a collection of error messages and I'd like to know if it does not contain a specifix error message.
Anyway I applied this workaround for now:
`.filter(Condition.matchesText("NullPointerException")).shouldHaveSize(0);`

**Comment by rmarinsky** [comment]
Use shouldBe(Condition.empty);

**Comment by apreg** [comment]
Thanks for the hint. I was sure it can be more readable but I feel it still a workaround.
`.filter(Condition.matchesText("NullPointerException")).shouldBe(**CollectionCondition**.empty);`

**Comment by SergeyPirogov** [comment]
@apreg  use static imports, so code will become more readable

**Comment by rosolko** [comment]
Solution provided so close it.
But feel free to reopen or create a new one if it's really needed.
