### ISSUE TITLE
[question] using SelenideElement variable

### ISSUE THREAD

**Issue by anyone-can-test** [codeborne/selenide#504]
I wonder if there is any difference between the following codes, which are expected to the same action?

```
// case #1
// using SelenidElement variable for reuse
 SelenideElement base = $("#" + statsId + " > div > div.pos-tr > div").should(visible); 
 base.$("button > i").should(visible).click(); 
```

```
// case #2
 $("#" + statsId + " > div > div.pos-tr > div").should(visible).$("button > i").should(visible).click(); 
```

**Comment by SergeyPirogov** [comment]
@anyone-can-test Nope, there is no any difference

**Comment by anyone-can-test** [comment]
@SergeyPirogov 

Thank you for fast feedback.
I have one more question.

Sometimes, "button > i" element is not found in case 1.
(In case 2, I am not sure.)
```
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"button > i"}
```
But, when I inspect the saved html and screenshot, the "button > i" element exists.

What can I do for debugging?

**Comment by SergeyPirogov** [comment]
@anyone-can-test Well, the only thing i can propose is to debug you test by placing brake point and then investigate HTML DOM during test execution

**Comment by rmarinsky** [comment]
@anyone-can-test try selector: "button i". Maybe element with tag "i" it isn't next after "button"

**Comment by anyone-can-test** [comment]
My test had an error.
The element ("button > i") was actually not visible.
When I inspected HTML DOM, the element existed in DOM, but the visible state was false.
