### ISSUE TITLE
NoSuchMethodError when using switchTo().frame(<frame info>); 

### ISSUE THREAD

**Issue by hjr2000** [codeborne/selenide#506]
Hi Andrei and co 👍 

**Config:**
Win10, Chrome 57, Chromedriver 2.28, Selenide 4.3, Selenium 3.3.1

**Steps to reproduce:**
A test runs the following code

`switchTo().frame(<frame info>);`

**Result:**
At runtime:
 org.openqa.selenium.support.ui.FluentWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
        at com.codeborne.selenide.SelenideTargetLocator.frame(SelenideTargetLocator.java:37)

**Expected result:**
No exception, frame to now be active.

**Further info:**
This issue seems to be related to a previously raised issue 498. 
As I am using Maven to manage my Selenium-Java dependencies, Guava 21 is present by default. This issue seems related to the use by Selenide of the deprecated fluentWait class also.

Many thanks,
Haden

**Comment by SergeyPirogov** [comment]
I think it is related to this http://selenium2.ru/blog/187-predicates-in-explicit-waits.html

**Comment by hjr2000** [comment]
Hi @SergeyPirogov,
The page you linked to stated that the problem goes away when you upgrade to Guava 21. However, I believe Selenide already uses Guava 21.
Have a look [here](http://stackoverflow.com/questions/42421148/wait-untilexpectedconditions-doesnt-work-any-more-in-selenium) also.
Kind regards,
Haden

**Comment by SergeyPirogov** [comment]
@hjr2000 Have you explicitly added guava 21 to your project?

**Comment by hjr2000** [comment]
Yes, pretty much the first thing I tried

**Comment by hjr2000** [comment]
Is Selenide 4.4 available yet via Maven?

**Comment by asolntsev** [comment]
@hjr2000 It's easy to check here: http://search.maven.org/#search%7Cga%7C1%7Cselenide

Yes, version Selenide 4.4.1 is available via Maven.
