### ISSUE TITLE
Update javadoc for SelenideElement#setValue

### ISSUE THREAD

**Issue by yashaka** [codeborne/selenide#508]
Currently the [javadoc](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/SelenideElement.java#L34), does not reflect actual [implementation](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/commands/SetValue.java)

Currently setValue() is much more than just:

```
   *   1. WebElement.clear()
   *   2. WebElement.sendKeys(text)
   *   3. Trigger change event</pre>
```

It also can work with radio buttons and dropdowns. It also can be configured via Configuration.fastSetFalue

All this should be described in doc comment before method declaration.

**Comment by yashaka** [comment]
Or... 

Remove JavaDoc except the reference:

```
  /**
   * @see com.codeborne.selenide.commands.SetValue
   */
```

but refactor [implementation](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/commands/SetValue.java) to be more readable

**Comment by asolntsev** [comment]
Sure, we should update javadoc. Feel free to submit a pull request!

**Comment by yashaka** [comment]
So, according to last "private skype discussions", the next steps in context of this issue are:
- make all "setvalue magic" (regarding multi-control behaviour, like setting also value for Select and Radio) configurable and disabled by default
- refactor implementation to be readable
- update javadoc

@asolntsev,
Can you confirm the plan here? :)

**Comment by asolntsev** [comment]
Yes, the plan is good!

Andrei Solntsev

2017-04-04 15:25 GMT+03:00 Iakiv Kramarenko <notifications@github.com>:

**Comment by AleksanderPopov** [comment]
I can create PR for this task

**Comment by AleksanderPopov** [comment]
created https://github.com/codeborne/selenide/pull/518

**Comment by asolntsev** [comment]
Javadoc was added in PR #518
