### ISSUE TITLE
No versions available for org.seleniumhq.selenium:selenium-support:jar:[2.53.0,4.0.0)

### ISSUE THREAD

**Issue by vitassecuriti** [codeborne/selenide#509]
in pom.xml I connect dependence.
according to the instruction from the website http://ru.selenide.org/quick-start.html

<dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>selenide</artifactId>
    <version>4.4.1</version>
    <scope>test</scope>
</dependency>

When I begin assembly of maven I receive a mistake 

"Failed to execute goal on project dashboard-web: Could not resolve dependencies for project atc.cm:dashboard-web:war:1.0-SNAPSHOT: Failed to collect dependencies at com.codeborne:selenide:jar:4.4.1 -> org.seleniumhq.selenium:selenium-java:jar:3.3.1 -> org.seleniumhq.selenium:htmlunit-driver:jar:2.24 -> org.seleniumhq.selenium:selenium-support:jar:[2.53.0,4.0.0): No versions available for org.seleniumhq.selenium:selenium-support:jar:[2.53.0,4.0.0) within specified range -> [Help 1]"

What's the problem?
Earlier I used the <version> 4.0 version </version>

**Comment by asolntsev** [comment]
@vitassecuriti Why closed? Have you found a solution? Can you share it with others?

**Comment by vitassecuriti** [comment]
I have created the new project, I have prescribed dependence, I have started the test - everything works.
I have come to a conclusion that it is a problem in the conflicts of my dependences. And on this I have decided to close this question not to distract you from the solution of real problems.

**Comment by asolntsev** [comment]
Ok, thank you for caring about us :)

**Comment by showtime25st** [comment]
Hello! If you read it in 2022. 
Same problem was when i started project with "Selenium UI Testing" plugin, chouse "selenium 4" and add latest appium version to dependencies in gradle. Solve problem when downgrade to "selenium 3"

**Comment by asolntsev** [comment]
Yes, currently the latest appium version doesn't support Selenium be 4 yet. Need to wait another major update of Appium.
