### ISSUE TITLE
Deprecate Condition.empty, use Condition.blank instead

### ISSUE THREAD

**Issue by yashaka** [codeborne/selenide#511]
The official "Quick Start" says:

> Start writing test
> So easy! No more boring routines, we can start.

> Import required classes:
```java
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.*;
```

...

Since we have such documentation, it's natural to extend the code example with imports to at least:

```java
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.CollectionCondition.*;
```

But... This code will lead to problems when you will try to do:

```java
$$(".item".).shouldBe(empty);
```

Because `CollectionCondition.empty` has a conflict with `Condition.empty`

I believe that:
- it would be just handy and simpler/easier to not have conditions and collection conditions with same names. 
- Condition.blank - better reflects the purpose of the currently named "empty" element condition (it is used to check that input field is blank or element has no text in it...)
- Seems like Condition.empty is not used so often as e.g. CollectionCondition.empty - so this will not affect much, especially if we do not remove the "old" name immediately, but just mark it as deprecated and finally remove in next versions...

**Comment by asolntsev** [comment]
@yashaka @vinogradoff At least in some popular Java libraries, term "blank" is different from "empty".
* "Empty string" means string of length 0
* "Blank string" means string that is empty or contains only spaces. 

In this context "blank" is not correct term. 

I would suggest to deprecate `CollectionCondition.empty` because there is better alternative: `$$().shouldHave(size(0))`.

**Comment by vinogradoff** [comment]
It may even cooler to implement blank as empty or spaces. Because it is not about Java String, it is about what a person see in the input field. If he sees spaces - it is blank. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by yashaka** [comment]
But should not we be "user-oriented" not "developers oriented"? 

Should not we provide the API in "UI users language" at "Acceptance" level not in "dev language" of "unit tests level"... Selenide is the tool for "Acceptance level" not "unit tests level" nevertheless...

I also prefer:
```java
$$().shouldBe(empty)
```
over

```java
$$().shouldHave(size(0))
```

because it's more laconic and readable, and still reflects the "UI user language"... 

Moreover, a user will usually not see spaces in UI, because normally they are collapsed...

Still, your argument about "blank and empty are usually treated differently in programming" makes me not so sure about my original idea...

**Comment by yashaka** [comment]
> It may even cooler to implement blank as empty or spaces. Because it is not about Java String, it is about what a person see in the input field. If he sees spaces - it is blank.

really makes sense... 

In case if somebody wants to check exactly that there are 3 spaces in the input field only, he will do then:

```java
$().shouldHave(value("   "))
```

**Comment by yashaka** [comment]
@asolntsev 

So, what about the following plan: 
1. deprecate Condition.empty with an advice to use Condition.blank or Condition.exactText("") or Condition.value("") correspondingly
2. Implement Condition.blank as 
> "Blank string" means string that is empty or contains only spaces.

?

**Comment by asolntsev** [comment]
Yes, we can add `blank` condition as a synonym for `Condition.empty`. 
But I don't like deprecating `empty` just because there is many people who use it and don't experience any problems/conflicts. Why should they change their code without any reason?

**Comment by asolntsev** [comment]
Closing the feature request. It seems that nobody is interested.
