### ISSUE TITLE
ClassNotFoundException with Selenide 4.4.2

### ISSUE THREAD

**Issue by pkalatski** [codeborne/selenide#512]
Tried to upgrade Selenide from 4.2.1 to 4.4.2 and started getting following error when calling `Selenide.open`: 

```
A needed class was not found. This could be due to an error in your runpath. Missing class: org/openqa/selenium/support/pagefactory/FieldDecorator
java.lang.NoClassDefFoundError: org/openqa/selenium/support/pagefactory/FieldDecorator
```

Here is a list of project dependencies:
https://gist.github.com/pkalatski/21f406190214793536d7435ccebd4edb

**Comment by asolntsev** [comment]
@pkalatski Hi!
For some reason, you are missing a dependency `selenium-support 3.3.1` in your project. Just add it to your build file, it should help.

**Comment by asolntsev** [comment]
@pkalatski Can you share the whole `pom.xml` or `build.gradle`?

**Comment by pkalatski** [comment]
Hey,

Thanks a lot! Adding selenium-support directly to the project worked.

Here is the initial build.sbt (that fails): 
https://gist.github.com/pkalatski/4cb7fd4865a392c1516f05e10bc9bae8

sbt version 0.13.13 was used.

**Comment by asolntsev** [comment]
@pkalatski I tried your `build.sbt`, and it didn't download `selenium-support-3.3.1.jar`.
I guess it's a bug of sbt, because both maven and gradle download it.
