### ISSUE TITLE
Selenide.refresh() does not refresh browser page in FireFox

### ISSUE THREAD

**Issue by lwiedemanlo** [codeborne/selenide#513]
When calling Selenide.refresh() in FireFox the current page is not reloaded. This call works successfully with chromedriver. Tried using both the old firefox driver with FireFox 46 and the latest geckodriver with the latest version of Firefox.

There is a workaround of using the WebDriverRunner class to refresh the page, but it would be great if Selenide.refresh() worked in all browsers.

**Comment by SergeyPirogov** [comment]
Hmm, which command do use from WebDriverRunner?

**Comment by rmarinsky** [comment]
So strange... Have you used method open("/path") before?

Because of Selenide.refresh() implementation it's opne(url());
where url() - it's getCurrentUrl() from WebDriver interface

**Comment by lwiedemanlo** [comment]
@SergeyPirogov WebDriverRunner.getWebDriver().navigate().refresh() works and reloads the page on FireFox.

@rmarinsky If I replace Selenide.refresh() with open(WebDriverRunner.getWebDriver().getCurrentURL()); the page does not reload

**Comment by lwiedemanlo** [comment]
Yeah, no issues with chromedriver. Using the latest geckodriver 0.15.0

**Comment by rmarinsky** [comment]
@lwiedemanlo what returns method "WebDriverRunner.getWebDriver().getCurrentURL()"? 
What is the version of selenium in your libraries?

**Comment by lwiedemanlo** [comment]
We're using Selenide 4.4.2 and using the latest version of Selenium (3.3.1).

**Comment by rosolko** [comment]
@lwiedemanlo Can you please update to latest version and check again?
I ran test an everything looks great.
So, close it for now, but feel free to reopen if needed.
