### ISSUE TITLE
No dependency for selenium-support on 4.4+

### ISSUE THREAD

**Issue by kazuki43zoo** [codeborne/selenide#514]
I've updated to Selenide 4.4.2 + Selenium 3.3.1, it not work fine as follow:
(Until 4.3 + Selenium 3.0.1, it work fine)

My selenide code:
```
	@Test
	public void testOrder() {

		// Open the home page
		open("/"); // #### Error occurred here
		assertThat(title()).isEqualTo("JPetStore Demo");

		// Move to the top page
		$(By.linkText("Enter the Store")).click();
		$(By.id("WelcomeContent")).shouldBe(text(""));

		// ...
	}
```

StackTrace:
```
Tests run: 12, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 6.831 sec <<< FAILURE! - in com.kazuki43zoo.jpetstore.JpetstoreApplicationTests
testOrder(com.kazuki43zoo.jpetstore.JpetstoreApplicationTests)  Time elapsed: 0.04 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/openqa/selenium/support/pagefactory/FieldDecorator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.kazuki43zoo.jpetstore.JpetstoreApplicationTests.testOrder(JpetstoreApplicationTests.java:77)
```

It is reason that there is no dependency to `selenium-support`. (Since `selenium-java` 3.2, it does not depend on `selenium-support`)

I've tried to add the `selenium-support` in my `pom.xml`, it work fine (My changes see [here](https://github.com/kazuki43zoo/mybatis-spring-boot-jpetstore/blob/e3e811ee6a4b1761efe81ed10a203d0dfdcc6076/pom.xml#L150-L155)).

I think it should resolve dependency by `selenide` or `selenium-java`.What do you think ?

**Comment by asolntsev** [comment]
I agree. We will add it in selenide 4.4.3
We will release it soon.

**Comment by kazuki43zoo** [comment]
@asolntsev I withdraw this issue because `selenium-java` depends on `selenium-support` via `htmlunit-driver`.
