### ISSUE TITLE
Whats wrong? java.lang.NoClassDefFoundError: com/codeborne/selenide/Selenide

### ISSUE THREAD

**Issue by StanWos** [codeborne/selenide#519]
We recently decided to add Selenide to our project and after create maven package and run, it throws me an error:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/codeborne/selenide/Selenide`

Please help, It is the first time I deal with Selenide.
[pom.xml](https://gist.github.com/StanWos/9eda7d2249a21f52e8341aaa37e9249c)
 
What may cause the problem?

**Comment by asolntsev** [comment]
@StanWos Please upgrade to Selenide 4.4.3 - it should help.
