### ISSUE TITLE
setSelected method should check value after .click() action

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [codeborne/selenide#520]
setSelected() method should care about the result of .click() action. 
If we need to tick the checkbox, then setSelected() should check that checkbox was selected and vice versa. This will avoid the situation when .click() is sent to wrong item(e.g. element locator is not checkbox).

The most useful way for this would be to check element for selected condition:
element.shouldBe(selected);
element.shouldNotBe(selected);

```
public class SetSelected implements Command<WebElement> {
  Click click = new Click();
  
  @Override
  public WebElement execute(SelenideElement proxy, WebElementSource locator, Object[] args) {
    boolean selected = (Boolean) args[0];
    WebElement element = locator.getWebElement();
    if (element.isSelected() ^ selected) {
      if (element.getAttribute("readonly") != null)
        throw new InvalidStateException("Cannot change value of readonly element");
      click.execute(proxy, locator, NO_ARGS);
    }
    return proxy;
  }
}
```

**Comment by rosolko** [comment]
Good point to check actual behavior on tests level not on framework feature level.
