### ISSUE TITLE
Selenide - IE/Edge on Saucelabs - Cannot run the two out of the box

### ISSUE THREAD

**Issue by paul-nelson-baker** [codeborne/selenide#521]
I'm having an issue getting Selenide to run out of the box with internet explorer/edge on SauceLabs out of the box. Firefox and Chrome run just fine.

I'm using the very most recent version of selenide, at the time of this writing, `4.4.3`.

To replicate:
https://github.com/paul-nelson-baker/selenide-saucelabs-ie-issue

Are there other people who are able to do this (if so how) or is it just me?

**Comment by paul-nelson-baker** [comment]
I found the "issue". I'm not sure there would be a good auto-magic way to do this, but SauceLabs uses different string constants for IE and Edge, while BrowserStack uses different [string constants](https://www.browserstack.com/list-of-browsers-and-platforms?product=automate). I'll close the issue, because it is not an issue from Selenide's perspective.

**Comment by asolntsev** [comment]
Hi Paul!
Thank you for sharing the information.
