### ISSUE TITLE
default Wait.until in switchTo.XXXframe( "css") methods throws NoSuchMethodError

### ISSUE THREAD

**Issue by MartaWdowicka** [codeborne/selenide#522]
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.until(Ljava/util/function/Function;)Ljava/lang/Object;

I tried all combination of your switchTo() method and all trow the same error.
example code:
String id = $("some iframe").getAttribute("id");
switchTo().frame(id);

and at switchTo().frame(id); it trows that error at middle line of this:

public WebDriver frame(String nameOrId) { return (WebDriver)Selenide.Wait().until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(nameOrId));
  }

**Comment by MartaWdowicka** [comment]
Tried with both iframe id and cssSelector

**Comment by asolntsev** [comment]
Hi @MartaWdowicka !
It's a well-known issue when you use newer selenium but older guava.
Try to upgrade to the latest Selenide 4.4.3 - it should solve your problem.

**Comment by MartaWdowicka** [comment]
thanks will try
