### ISSUE TITLE
add usage tracker as opt-out option

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#523]
For Selenide developers it's helpful to know how our framework is used.

Some of the simple parameters could be regularly uploaded anonymously to statistics server.
For example, send weekly how many test runs with specific selenide version was made.
selenide3.3 -> 150,
selenide3.4.1 -> 70.

Save the statistics locally and send to preconfigured server once a week.
Use option for opt-out.

**Comment by SergeyPirogov** [comment]
Are you sure that users will be happy when they find out that selenide send some info? Especially corporate users

**Comment by vinogradoff** [comment]
we should alway be clear what information is uploaded. It will be anonymous and not related to any business.

**Comment by asolntsev** [comment]
@vinogradoff What are we going to do with this information? We actually don't have so much time to analyze it. 

We have download statistics at maven central repository, probably it's enough? 
![image](https://user-images.githubusercontent.com/279773/34394902-49752190-eb65-11e7-9d51-8e3f9971f475.png)
