### ISSUE TITLE
Fix class name of opera driver

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#526]
Method `WebDriverFactory.createOperaDriver()` tries to initialize `com.opera.core.systems.OperaDriver` instance and gets a `java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: com.opera.core.systems.OperaDriver` error. 

The correct way to the OperaDriver is `org.openqa.selenium.opera.OperaDriver`. Fix this bug, please. Thanks.

**Comment by rmarinsky** [comment]
I fixed it

**Comment by asolntsev** [comment]
Fixed by https://github.com/codeborne/selenide/pull/527
