### ISSUE TITLE
Wrong ElementNotFound exception message

### ISSUE THREAD

**Issue by biomaks** [codeborne/selenide#528]
When we are looking for particular option in **select** element using code: 

```java
$("#ddlModel").selectOption("Outlander");
```
in case if that option does not exist, we get following exception:
```java
com.codeborne.selenide.ex.ElementNotFound: Element not found {#ddlTrim}
```
Which does not make any sense, because "#ddlModel" element actually exists

**Comment by asolntsev** [comment]
@biomaks @BorisOsipov Thank you! Resolved by PR #530
