### ISSUE TITLE
Cannot find capabilities with browserName=ie when grid hub url specified in -Dremote

### ISSUE THREAD

**Issue by baranoff-ivan** [codeborne/selenide#529]
**Preconditions:**
```java
Configuration.remote = "<some hub url>";
Configuration.browser = WebDriverRunner.INTERNET_EXPLORER;
```

Failure when running tests with Selenide:
```
Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{nativeEvents=true, acceptSslCerts=true, requireWindowFocus=true, pageLoadStrategy=normal, browserName=ie}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
...
```

**Root cause:**
Selenium node recognizes capabilities with browserName "internet explorer", but not "ie"

Of course, I could just set browser as below:
```java
Configuration.browser = "internet explorer";
```
But Selenide has different workarounds for IE which uses `isIE()` method. And they won't work in such case.

**Comment by asolntsev** [comment]
@baranoff-ivan @BorisOsipov Thank you! Fix with PR #531.
