### ISSUE TITLE
IE specific code doen't work with custom WebDriverProvider

### ISSUE THREAD

**Issue by baranoff-ivan** [codeborne/selenide#532]
If I need to manage webDriver instantiation myself I should implement `WebDriverProvider` interface and specify it in `Configuration.browser` property.
But is Selenide there are IE specific code:
```java
public class GetInnerText implements Command<String> {
  @Override
  public String execute(SelenideElement proxy, WebElementSource locator, Object[] args) {
    WebElement element = locator.getWebElement();
    if (isIE()) {
      return element.getAttribute("innerText");
    }
    return element.getAttribute("textContent");
  }
}
```
and 
```java
protected void navigateToAbsoluteUrl(String url, String domain, String login, String password) {
    if (isIE() && !isLocalFile(url)) {
      url = makeUniqueUrlToAvoidIECaching(url, System.nanoTime());
      if (!domain.isEmpty()) domain += "\\";
    }
...
      if (isIE() && !"".equals(login)) {
        Selenide.switchTo().alert().authenticateUsing(new UserAndPassword(domain + login, password));
      }
```
`isIE` method implementation itself depends on `Configuration.browser` property:
```java
public static boolean isIE() {
    return INTERNET_EXPLORER.equalsIgnoreCase(browser);
}
```
So IE specific code won't work with custom WebDriverProvider.
Any ideas about that?

**Comment by BorisOsipov** [comment]
As well as in case when you set a WebDriver instance through `com.codeborne.selenide.WebDriverRunner#setWebDriver`
I guess we can implement driver type checks in runtime for driver type that has already started.
@baranoff-ivan  do you like to make a pull request with such functionality?

**Comment by baranoff-ivan** [comment]
>  guess we can implement driver type checks in runtime for driver type that has already started.
> @baranoff-ivan do you like to make a pull request with such functionality?

@BorisOsipov Thank you.
Now I have some ideas about that and I will make a pull request later.

**Comment by baranoff-ivan** [comment]
I've made pull request. @BorisOsipov would you please review it?

**Comment by BorisOsipov** [comment]
@baranoff-ivan Thank you for your contribution.
I looked at pr and made some suggestions for you.
I guess Selenide maintainers reviews and merge your pr soon ;)

**Comment by baranoff-ivan** [comment]
IE specific code looks like a hack. And if we need to do some operations depending on the type of webdriver we need to come up with more general solution for determining the type.
