### ISSUE TITLE
how set  browser window max when selenide start

### ISSUE THREAD

**Issue by zhupengfarmer** [codeborne/selenide#536]
use chrome browser
when selenide open google  my browser not max
is not Default max?

**Comment by rmarinsky** [comment]
How do you init browser?

**Comment by zhupengfarmer** [comment]
@rmarinsky 

`		Configuration.browser="chrome";
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chromedriver.exe");`

**Comment by abondarev-sel** [comment]
Did you try updating `Configuration.startMaximized` ?

**Comment by zhupengfarmer** [comment]
@abondarev-sel ye,I have tried
but ,not work, not max

**Comment by zhupengfarmer** [comment]
i know why browser not max,
my chromedriver was not  new  version
when  i  try new chrome 2.29 ,it work

**Comment by zhupengfarmer** [comment]
close
