### ISSUE TITLE
"getJavascriptErrors()" method does not work in Selenide 4.3

### ISSUE THREAD

**Issue by JuliaPion** [codeborne/selenide#540]
**"getJavascriptErrors()" method does not return js errors**

**Pre-Conditions:**
Selenide 4.3
Browser Chrome Version 58.0.3029.110 (64-bit)
chromedriver_v2.28_win32.exe

**Steps To Reproduce:**
Use "getJavascriptErrors()" method like this:
open("http://...com");
List<String> jsErrors = Selenide.getJavascriptErrors();

**Actual Result:**
 jsErrors variable has size 0
 
**Expected Result:**
 jsErrors variable has size 1:
[SEVERE] http://...com/faye/client.js - Failed to load resource: the server responded with a status of 502 (Bad Gateway)

P.s. Selenide.getWebDriverLogs(LogType.BROWSER, Level.SEVERE) -> this works

**Comment by crazyk2** [comment]
@JuliaPion  Is` Configuration.captureJavascriptErrors = true` ? Did you change default settings?

**Comment by JuliaPion** [comment]
@crazyk2, I didn't change "selenide.captureJavascriptErrors" system property

**Comment by Metaun** [comment]
I have the same issue on 4.5 version . With getWebDriverLogs works correct, but getJavascriptErrors return 0 error

**Comment by AlexanderPoleschuk** [comment]
I can't say for sure, but since I've tried this feature with Configuration.captureJavascriptErrors = true, I haven't caught ANY JS error in my logs. 
I use 
```
public static void waitForJquery() {
        Wait().until(webDriver ->
                (Boolean) executeJavaScript("return jQuery.active == 0"));
        checkForJSErrors();
        sleep(250L);
    }

private static void checkForJSErrors() {
        List<String> errors = getJavascriptErrors();
        if (!errors.isEmpty()) {
            LOGGER.warn("There are java script error(s) on the page: " + url());
            LOGGER.warn(Arrays.toString(errors.toArray()));
        }
    }
```
I haven't seen any warn messages in logs since I've implemented this.

**Comment by JuliaPion** [comment]
Any updates?

**Comment by BorisOsipov** [comment]
Hi @JuliaPion 

Looks like a bug and need additional investigation.
If someone from community will have time it will be fixed.
