### ISSUE TITLE
How do I click the hidden menu?

### ISSUE THREAD

**Issue by goushijie** [codeborne/selenide#541]
Hello,
   I need to move the mouse to the hidden menu, and then click on the menu. How do I do that?

  We still can't do this

  
![move](https://cloud.githubusercontent.com/assets/7100718/26488840/95a03c4e-4237-11e7-9f45-818daa887bfe.jpg)

**Comment by asolntsev** [comment]
@goushijie Why you can't do this? What error do you get?

Generally, why do you want to click a hidden menu? If a real user cannot click it, then test also should not click it. Because test should emulate real user's behaviour.

**Comment by rosolko** [comment]
Not an issue.
Cant access to hidden element because hidden == not presented.
So you can't interact with it.
