### ISSUE TITLE
Add option "chromeoptions.binary" 

### ISSUE THREAD

**Issue by nobiinu-and** [codeborne/selenide#547]
This option enables to use both Chrome and Chrome Canary.
We use Chrome Canary for Headless.

refs PR #546

**Comment by ostap-oleksyn** [comment]
PR [#627](https://github.com/codeborne/selenide/pull/627) added the abilty to set browser binary via configuration parameter. I think this issue and related [pull request](https://github.com/codeborne/selenide/pull/546) can be closed .

**Comment by nobiinu-and** [comment]
thanks!
we can close this issue.

**Comment by vbisbest** [comment]
This feature does not appear to work based on the docs on the command-line runner page.  According to docs, you execute:
`selenium-side-runner -c "goog:chromeOptions.binary='/path/to/non-standard/Chrome/install'"`

However this generates an error:
`TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser()?`

Is there an issue in the docs?  Thank you.

**Comment by asolntsev** [comment]
@vbisbest Hi. Are you talking about Selenide? I don't know what is `selenium-side-runner` - Selenide doesn't have such a thing.
