### ISSUE TITLE
browser marionette does not work at all

### ISSUE THREAD

**Issue by torstenwerner** [codeborne/selenide#548]
Hi,

I am new to selenide and i am sorry for that. I did not find any specific instructions for testing with Firefox. I have tried the following.
- clone the sample https://github.com/selenide-examples/google
- run the tests with gradle and verified that everything works fine with chrome which is the default in the sample project
- changed chrome into marionette in build.gradle
- result: several instances of Firefox are starting, nothing happens within them, all tests are failing, and the browser instances do not quit

I am using Firefox 54, geckodriver 0.16.1, and OS X. An unrelated selenium based project works fine with Firefox and that is why I do not assume any local setup error.

**Comment by asolntsev** [comment]
@torstenwerner Hi! I also have Firefox 54, geckodriver 0.16.1 (I also tried 0.16.0 and 0.17.0) and OS X.

This test works on my machine:

```
  @Test
  public void can_user_geckodriver() {
    Configuration.browser = "marionette";
    System.setProperty("webdriver.gecko.driver", "/usr/local/bin/geckodriver");
    open("http://google.com");
    $(By.name("q")).val("selenide").pressEnter();
  }
```

**Comment by torstenwerner** [comment]
I have found the error. The current spring-boot version 1.5.x downgrades selenium to version 2 for unknown reasons. Setting selenium.version = 3.4.0 in my project's gradle.properties fixes it. Sorry for the noise.
