### ISSUE TITLE
Capabilities in Configuration

### ISSUE THREAD

**Issue by SergeyPirogov** [codeborne/selenide#553]
As a Selenide user, I want to have possibility set desired capabilities for different browsers using Config class.

Example:

```
Configuration.browserCapabilities = DesiredCapabilities.CHROME()
```

**Comment by vinogradoff** [comment]
> As a Selenide user, I want to have possibility set desired capabilities for different browsers using Config class.
> 
... to achieve what?
Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by SergeyPirogov** [comment]
To be able to set additional chrome options for example. Now we can set them via command line or System.properties but it's not consistent and not always handy

**Comment by wesmcouch** [comment]
To add to this I have been unable to set chrome options when using remote webdriver, I have tried using system properties, the configuration.chromeSwitches, and everything else and can't seem to get them to stick. I have stepped through the selenide code where it adds the capabilities and it seems to be adding them, but as soon as the remotewebdriver is created they aren't there.

**Comment by andrcuns** [comment]
I agree, being able to set it programmatically allows to have a more consistent configuration set up of tests which would work the same regardless if it is executed from commandline or from IDE runner.

**Comment by BorisOsipov** [comment]
Implemented in https://github.com/codeborne/selenide/pull/664
