### ISSUE TITLE
TextReport() logs in Cucumber Junit test

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#559]
Not an issue but a question.. I did post the same question at https://github.com/selenide-examples/cucumber/issues/2

But i guess that this channel is more populair and for that reason i am asking it here.. 

I wonder if  TextReport() is working in combination with Cucumber JUnit tests? I try adding it into my project but it did not work.. I don't see any logs.

```java
@Rule
  public TestRule report = new TextReport().onFailedTest(true).onSucceededTest(true);
```
Thanks!

**Comment by rosolko** [comment]
> This question is more related to Cucumber than to Selenide.
Looking at issue cucumber/cucumber-jvm#393, I see that JUnit @Rule annotation is not supported by Cucumber. It means that you cannot use built-in TextReport rule with Cucumber, but you can create a very similar hook in Cucumber.
