### ISSUE TITLE
Feature request: Headless Chrome

### ISSUE THREAD

**Issue by andrey-ryoo** [codeborne/selenide#560]
In latest Chrome version there is an option to run chrome with -headless flag. Why not add this feature to selenide to get rid of Xvfb during tests

**Comment by SergeyPirogov** [comment]
You are able to run tests in headless chrome now, just set chrome options

**Comment by andrey-ryoo** [comment]
Selenide uses it's own Driver Management out of the box, so why not implement it in Configuration class like Configuration.browser = "chrome-headless";
Otherwise you need to create your own chromedriver and insert in WebDriverRunner or something like that

**Comment by SergeyPirogov** [comment]
Nope, you jut need to say gradlew test -Dchromeoptions.args="--headless --disble-gpu"

**Comment by mept** [comment]
Any chance to run it headless with maven?
Chrome still runs in gui mode when I use mvn test -Dchromeoptions.args="--headless --disble-gpu"

Linux x64
ChromeDriver 2.30.477691

**Comment by anyone-can-test** [comment]
When I execute with -Dchromeoptions.args="--headless --disble-gpu", it seems to hang at some point. 

```
Gradle Test Executor 1 > com.nhnent.tc.console.ui.BasicCheck STANDARD_ERROR
    7월 31, 2017 12:25:58 오후 com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
    정보: Close webdriver: 12 -> ChromeDriver: chrome on XP (27a2ae9866dfcc5cc07ebc74e669edce)
    7월 31, 2017 12:25:58 오후 com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser run
    정보: Trying to close the browser ChromeDriver ...
    7월 31, 2017 12:25:59 오후 com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
    정보: Closed webdriver in 969 ms
    Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 25077
    Only local connections are allowed.
    7월 31, 2017 12:26:01 오후 org.openqa.selenium.remote.ProtocolHandshake createSession
    정보: Detected dialect: OSS
    7월 31, 2017 12:26:01 오후 com.codeborne.selenide.webdriver.WebDriverFactory adjustBrowserSize
    정보: Set browser size to 1920x1280
    7월 31, 2017 12:26:02 오후 com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
    정보: BrowserName=chrome Version=60.0.3112.78 Platform=XP
    7월 31, 2017 12:26:02 오후 com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
    정보: Selenide v. 4.5.1
    7월 31, 2017 12:26:02 오후 com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
    정보: Selenium WebDriver v. 3.4.0 build time: unknown
    7월 31, 2017 12:26:02 오후 com.codeborne.selenide.impl.WebDriverThreadLocalContainer createDriver
    정보: Create webdriver in current thread 12: ChromeDriver -> ChromeDriver: chrome on XP (5131c2aee01c7863da328638eca1a63f)

// No progress
```

Executing headless Chrome is successful.
```
$ chrome --headless --disable-gpu --print-to-pdf https://www.google.com/
[0731/115014.872:INFO:headless_shell.cc(464)] Written to file output.pdf.

KLIB_SelfTest return : KLR_OK
```

**Comment by SergeyPirogov** [comment]
Yes, because --headless, --disable-gpu is used for command line, but in Selenium you should use headless and disable-gpu. It's because in source code it workds like this 
```
chromeOptions.addArguments("headless","disable-gpu") 
```

**Comment by hyunil-shin** [comment]
@SergeyPirogov 
What should I do to run tests in headless Chrome in Windows?
You mean that the command line is not right way?

My full command line is like.
```
gradle clean test -Palpha --tests=*.BasicCheck -Dchromeoptions.args="--headless --disable-gpu"
```

**Comment by ostap-oleksyn** [comment]
Since selenide 4.8 you can run Chrome and Firefox in headless mode using the headless parameter.
In code:
Configuration.headless = true.
Using parameters:
-Dselenide.headless=true

**Comment by BorisOsipov** [comment]
Yep. thank you @ostap-oleksyn

**Comment by jbarop** [comment]
Please note that `chromeoptions.args` expects all arguments to be comma separated.

-Dchromeoptions.args=--headless,--disable-gpu,--no-sandbox
