### ISSUE TITLE
about $$().size() bug

### ISSUE THREAD

**Issue by zhupengfarmer** [codeborne/selenide#565]
![image](https://user-images.githubusercontent.com/19220083/27727402-ea8cc418-5db0-11e7-9cf7-64083c9bea9f.png)
![image](https://user-images.githubusercontent.com/19220083/27727415-f3582196-5db0-11e7-974f-f5505740dc28.png)
`print $$().size() `   is 0
But  i can `$$().get(0) ` to  get elememnt

**Comment by zhupengfarmer** [comment]
![image](https://user-images.githubusercontent.com/19220083/27727974-30165df8-5db3-11e7-83a9-3ba1fccc1405.png)


if First findelement  by id  work
`List<SelenideElement> pageList1 = $("#work").$$(By.className("ul-0"));
		System.out.println(pageList1.size());`

it worked.

**Comment by zhupengfarmer** [comment]
if Change the order
`	System.out.println($$(By.className("ul-0")).get(0).$$("li").shouldHave(sizeGreaterThan(0)).size());
		//如果存在多页,进行翻页测试
		List<SelenideElement> pageList = $$(By.className("ul-0"));
		System.out.println($$(By.className("ul-0")).size());
		System.out.println($$(By.className("ul-0")));
		System.out.println(pageList.size());`

it worked..........

**Comment by bentys** [comment]
# good
