### ISSUE TITLE
Something wrong in Element should error message

### ISSUE THREAD

**Issue by hyunil-shin** [codeborne/selenide#576]
This is my error message (sorry for Korean).
In the message, the expected string is contained definitely in the actual string.
What may be the cause of the test fail?
It would fail to compare the strings, but when printing the message the actual string was correct. Is that possible? In the Describe class, the element may be re-accessed for printing logs.

```
// error message (from JUnit)

Element should be text '업로드 완료' {#wrap > div.uploadBar.ng-scope > div:nth-child(1)}
Element: '<div>×
3개 파일 업로드 완료.
자세히</div>'
```

```
// source code

uploadLoadingPanel.waitUntil(text("업로드 완료"), 20000);

**Comment by asolntsev** [comment]
@hyunil-shin Yes, theoretically it's possible that element got this text **exactly at the moment** when Selenide started composing the error message. If this is the case, then increasing timeout should help. 

P.S. Probably there is some bug with comparing Korean texts. Is this error reproducible with English texts too?

**Comment by hyunil-shin** [comment]
@asolntsev 
If I get similar issue, I will report it. This might be the first issue, this kind of issue.  I don't think comparing Korean text has some bugs. If so, I had gotten many fails of this issue.
