### ISSUE TITLE
Lets add Allure 2 optional support

### ISSUE THREAD

**Issue by andrey-ryoo** [codeborne/selenide#577]
HI guys, I guess many of us are using Test report tools and I believe Allure is very popular. Lets add an optional support for Yandex Allure 2 @Step support to make issue investigating faster.

**Comment by thasherwin** [comment]
+1

**Comment by BorisOsipov** [comment]
@andrey-ryoo 
What kind of integration do you mean?
Provide more details.

**Comment by andrey-ryoo** [comment]
We can add Allure 2 as dependancy and add @Step annotation to interaction methods like click(), sendKeys(), etc. After, when we use Selenide in inherited project with Allure 2 enabled, all interaction methods will be displayed as nested actions

**Comment by BorisOsipov** [comment]
Not sure that people who don't use Allure will be happy if we add for them allure to classpath along with selenide...

**Comment by andrey-ryoo** [comment]
Allure Annotation will not affect untill you have it enabled in your project

**Comment by Sobolion** [comment]
+1

**Comment by pskvortsov** [comment]
Please no

**Comment by asolntsev** [comment]
@pskvortsov Why no?
@andrey-ryoo I don't like the idea of adding allure.jar to classpath (for those people who don't use Allure). Can we do it in some other way (without adding annotation in Selenide code)?

For example, we could add some interceptors before/after every Selenide method. Can this interceptor call some Allure method like `addStep("click")`?

**Comment by SergeyPirogov** [comment]
Yeah, we faced with the same issue. I have a solution that may help without additions to core Selenide. You can write your custom aspect and intercept Selenide methods. For Java it will work just perfect, except conditions. I am going to talk about this hints at QAFest, but I can share the code with you personally ;)

**Comment by thasherwin** [comment]
I also would like to know how.. This would really help.

**Comment by andrey-ryoo** [comment]
@asolntsev what about distributing 2 versions of selenide: plain one and with allure?

**Comment by BorisOsipov** [comment]
@andrey-ryoo what about fork selenide and do what you want? :)

**Comment by SergeyPirogov** [comment]
Fork brings additional effort =)

**Comment by zhupengfarmer** [comment]
allure  is good

**Comment by iCok** [comment]
If you do it, please make it optional, because not all people want to have logging every click into their allure reports.

**Comment by rmarinsky** [comment]
It can be as an external lib in allure, not as a feature in selenide.
for example module allure-selenide in https://github.com/allure-framework/allure-java

**Comment by jtolotta** [comment]
@rmarinsky 
Agreed a module is the best approach or a personal fork of Selenide and tightly integrate Allure.
Allure is a reporting engine but there are others (such as Serenity BDD), and for Selenide to integrate a specific reporting engine can have harsh future effects such as dependency convergence, increased weight and more integration testing effort.

**Comment by sukhjinder-sdei** [comment]
Allure is good for reporting but should not write each SelenideEvent, Instead can be create a method to log a step and configuration enable Allure.

**Comment by BorisOsipov** [comment]
Hi @andrey-ryoo @Sobolion 

Guys from Allure create integration with Selenide. Maybe it will be interesting for you 
https://github.com/allure-framework/allure-java/pull/169/

**Comment by simple-elf** [comment]
For using this you need to add listener in BeforeClass
```SelenideLogger.addListener("allureSelenide", new AllureSelenide());```
and delete it in AfterClass
```SelenideLogger.removeListener("allureSelenide");```

**Comment by DzmitryHumianiuk** [comment]
> @asolntsev what about distributing 2 versions of selenide: plain one and with allure?
why then don't we have [ReportPortal ](https://github.com/reportportal/reportportal) integration in Selenide ? :)))

**Comment by BorisOsipov** [comment]
@DzmitryHumianiuk 
I guess we need to create separate issue if we need create Report Portal integration

@andrey-ryoo @Sobolion

As I said earlier it's implemented from allure team in https://github.com/allure-framework/allure-java/pull/169
