### ISSUE TITLE
Feature Request: Can we integrate Chromeless

### ISSUE THREAD

**Issue by anilreddy** [codeborne/selenide#580]
Hi,

I have recently saw this project in github [Chromeless](https://github.com/graphcool/chromeless) getting popular every day. It was released recently and gain lot of users attraction. So can it be integrated with selenide? I know it was written in typescript but still can we do that. If not you can close it.

Thanks,
Anil

**Comment by SergeyPirogov** [comment]
What is the main reason? According to the documentation, Chromeless is the same as Headless chrome, so just take your existing tests in selenide and run them in headless mode. Will be the same as chomeless

**Comment by SVPA-BetsyFox** [comment]
I've had our tests running with it for a while now- works like a charm!
It's as simple as adding ```System.setProperty("chromeoptions.args", "headless");``` to your initialization block.

**Comment by BorisOsipov** [comment]
We can't integrate Chromeless somehow. If it needs you can use chrome with headless mode.

**Comment by RomanIsko** [comment]
```java
public class HeadlessTest {

    @BeforeEach
    void setUp() {
        Configuration.browser = "chrome";
        Configuration.headless = true;
    }

    @Test
    void headlessChromeTest() {
        open("https://the-internet.herokuapp.com/login");
        $(By.name("username")).shouldBe(empty);
        $(By.name("password")).shouldBe(empty);
        $(".radius").click();
        $(By.id("flash")).shouldBe(visible);
    }
}
