### ISSUE TITLE
Add threadID info to logging messages

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [codeborne/selenide#582]
Selenide has closeWebDriver method(code is below).

It would be nice to pass threadID along with logged messages, therefore,  
log.severe("Failed to close webdriver in " + closeBrowserTimeoutMs + " milliseconds");
would be 
log.severe("Failed to close webdriver " + thread.getId() + " in " + closeBrowserTimeoutMs + " milliseconds");
where thread.getId() is a presaved id of thread that selenide tried to close. 
It will really help to investigate the reasons of some failures.

```
protected void closeWebDriver(Thread thread) {
    ALL_WEB_DRIVERS_THREADS.remove(thread);
    WebDriver webdriver = THREAD_WEB_DRIVER.remove(thread.getId());
    SelenideProxyServer proxy = THREAD_PROXY_SERVER.remove(thread.getId());
    
    if (webdriver != null && !holdBrowserOpen) {
      log.info("Close webdriver: " + thread.getId() + " -> " + webdriver);
      if (proxy != null) {
        log.info("Close proxy server: " + thread.getId() + " -> " + proxy);
      }

      long start = System.currentTimeMillis();

      Thread t = new Thread(new CloseBrowser(webdriver, proxy));
      t.setDaemon(true);
      t.start();

      try {
        t.join(closeBrowserTimeoutMs);
      } catch (InterruptedException e) {
        log.log(FINE, "Failed to close webdriver in " + closeBrowserTimeoutMs + " milliseconds", e);
      }

      long duration = System.currentTimeMillis() - start;
      if (duration >= closeBrowserTimeoutMs) {
        log.severe("Failed to close webdriver in " + closeBrowserTimeoutMs + " milliseconds");
      }
      else if (duration > 200) {
        log.info("Closed webdriver in " + duration + " ms");
      }
      else {
        log.fine("Closed webdriver in " + duration + " ms");
      }
    }
    else if (proxy != null && !holdBrowserOpen) {
      log.info("Close proxy server: " + thread.getId() + " -> " + proxy);
      proxy.shutdown();
    }
  }
```

**Comment by ddemin** [comment]
As I know you can configure logging via some xml file and change logging format (include displaying of thread ID)

**Comment by AlexanderPoleschuk** [comment]
Well, nice that we have an ability for a workaround, however, I don't see a point to do such kind of crutches.
Since Selenide logs a message of webdriver sessionID when it starts the driver, it should log the same format, when trying to clode the WD.
It's just a natural logic.

**Comment by BorisOsipov** [comment]
@AlexanderPoleschuk can you make PR for these changes?

**Comment by rosolko** [comment]
@AlexanderPoleschuk Ping! We need you response.

**Comment by BorisOsipov** [comment]
fixed by https://github.com/codeborne/selenide/pull/737
