### ISSUE TITLE
Selenide not worked in commandline application?

### ISSUE THREAD

**Issue by Roland4444** [codeborne/selenide#587]
Hello! I git cloned selenide from codeborne/ selenide. After that i build that gradle jar and create command line project with simple  open("127.0.0.1:9000/");

I got error. What i  doing wrong?
![screenshot_2017-08-22_11-10-23](https://user-images.githubusercontent.com/12486232/29555344-e0dca520-8711-11e7-89db-be3bc0a0b2d9.png)
![screenshot_2017-08-22_11-09-59](https://user-images.githubusercontent.com/12486232/29555345-e1060b40-8711-11e7-87e3-3c1f5e7925ca.png)

 
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/SearchContext
	at ch.roman1.Main.main(Main.java:8)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.SearchContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by BorisOsipov** [comment]
Hi @Roland4444 

Selenide works. You need to add to your application classpath  all Selenide dependencies as well.
I suggest you use build tools. These you can find some help -https://github.com/codeborne/selenide/wiki/Quick-Start

**Comment by Svitsky** [comment]
Try to add these deps to your pom
<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>${httpcore.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>${httpclient.version}</version>
		</dependency>

**Comment by Svitsky** [comment]
`<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>${httpcore.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>${httpclient.version}</version>
		</dependency>`

**Comment by BorisOsipov** [comment]
closed due no feeback. feel free to reopen if need.
