### ISSUE TITLE
CollectionCondition's for attribute values and css attributes values

### ISSUE THREAD

**Issue by bobmarks** [codeborne/selenide#592]
Loving Selenide and use it almost daily - good work!  

The existing collection conditions are quite limited (but extremely useful).  For example, if you had the following HTML: -

    <div id="container">
    
        <div class="item">
            <span>Input 1</span>
            <input type="text" id="text1" value="A" style="background: white">
        </div>
    
        <div class="item">
            <span>Input 2</span>
            <input type="text" id="text2" value="B" style="background: blue">
        </div>
    
        <div class="item">
            <span>Input 3</span>
            <input type="text" id="text3" value="C" style="background: red">
        </div>
    
    </div>

A useful collection condition which I've used often is: -
    
    $$(".item span").shouldHave(texts("Input 1", "Input 2", "Input 3"));

However, there isn't any tests on attribute values or CSS attribute values.  I.e. the following don't exist: -

    $$(".item input").shouldHave(attributeValues("id", "text1", "text2", "text3"));

... or for CSS selectors ...

    $$(".item input").shouldHave(cssAttributeValues("background", "white", "blue", "red"));

I've hacked the following together for both so I can make use of the lovely Selenide fluid / highly readable API (and make use of implicit waits) - but probably can be much nicer way to do this! :-)

---
## AttributeValues.java

    public class AttributeValues extends CollectionCondition {
    
        // Fields
    
        private final String attribute;
        private final List<String> expectedValues;
    
        public AttributeValues(String attribute, List<String> expectedValues) {
            this.attribute = attribute;
            this.expectedValues = expectedValues;
        }
    
        @Override
        public boolean apply(List<WebElement> elements) {
            if(elements.size() == 0) {
                return false;
            } else {
                for(int i = 0; i < this.expectedValues.size(); ++i) {
                    WebElement element = (WebElement)elements.get(i);
                    String attributeValue = element.getAttribute(attribute);
                    String expectedValue = (String)this.expectedValues.get(i);
                    if(!attributeValue.equals(expectedValue)) {
                        return false;
                    }
                }
    
                return true;
            }
        }
    
        public void fail(WebElementsCollection collection, List<WebElement> elements, Exception lastError, long timeoutMs) {
            if(elements != null && !elements.isEmpty()) {
                throw new TextsMismatch(collection, ElementsCollection.texts(elements), this.expectedValues, timeoutMs);
            } else {
                ElementNotFound elementNotFound = new ElementNotFound(collection, this.expectedValues, lastError);
                elementNotFound.timeoutMs = timeoutMs;
                throw elementNotFound;
            }
        }
    
        public String toString() {
            return "Attribute values" + this.expectedValues;
        }
    
        // Convenience static methods to create instance of this class
    
        public static AttributeValues attributeValues(String attribute, List<String> expectedValues) {
            return new AttributeValues(attribute, expectedValues);
        }
    
        public static AttributeValues attributeValues(String attribute, String ... expectedValues) {
            return new AttributeValues(attribute, asList(expectedValues));
        }
    
    }

---
## CssAttributeValues.java

    public class CssAttributeValues extends CollectionCondition {
    
        // Fields
    
        private final String cssAttribute;
        private final List<String> expectedValues;
    
        public CssAttributeValues(String cssAttribute, List<String> expectedValues) {
            this.cssAttribute = cssAttribute;
            this.expectedValues = expectedValues;
        }
    
        @Override
        public boolean apply(List<WebElement> elements) {
            if(elements.size() == 0) {
                return false;
            } else {
                for(int i = 0; i < this.expectedValues.size(); ++i) {
                    WebElement element = (WebElement)elements.get(i);
                    String cssAttributeValue = element.getCssValue(cssAttribute);
                    String expectedValue = (String)this.expectedValues.get(i);
                    if(!cssAttributeValue.equals(expectedValue)) {
                        return false;
                    }
                }
    
                return true;
            }
        }
    
        public void fail(WebElementsCollection collection, List<WebElement> elements, Exception lastError, long timeoutMs) {
            if(elements != null && !elements.isEmpty()) {
                throw new TextsMismatch(collection, ElementsCollection.texts(elements), this.expectedValues, timeoutMs);
            } else {
                ElementNotFound elementNotFound = new ElementNotFound(collection, this.expectedValues, lastError);
                elementNotFound.timeoutMs = timeoutMs;
                throw elementNotFound;
            }
        }
    
        public String toString() {
            return "CSS attribute values" + this.expectedValues;
        }
    
        // Convenience static methods to create instance of this class
    
        public static CssAttributeValues cssAttributeValues(String cssAttribute, List<String> expectedValues) {
            return new CssAttributeValues(cssAttribute, expectedValues);
        }
    
        public static CssAttributeValues cssAttributeValues(String cssAttribute, String ... expectedValues) {
            return new CssAttributeValues(cssAttribute, asList(expectedValues));
        }
    
    }

**Comment by BorisOsipov** [comment]
Hi @bobmarks 

Looks like the same feature described here https://github.com/codeborne/selenide/issues/569, am I right?

**Comment by bobmarks** [comment]
You're right `CssAttributeValues` is very similar - `AttributeValues` is different and something which I use more personally.
