### ISSUE TITLE
Not worked wuth Firefox!

### ISSUE THREAD

**Issue by Roland4444** [codeborne/selenide#598]
Just try! Firefox opened but not managed from selenide. Just opened. Version 55 firefox

**Comment by BorisOsipov** [comment]
you need use gecko driver and Configuration.browser="marionette" to deal with this issue.
Have look http://toolsqa.com/selenium-webdriver/how-to-use-geckodriver/

**Comment by BorisOsipov** [comment]
closed due no feeback. feel free to reopen if need.

**Comment by Roland4444** [comment]
bullshit. Selenium better!

**Comment by Roland4444** [comment]
Play 1 Framework testing UI selenium running without any drivers Gecko!

**Comment by asolntsev** [comment]
@Roland4444 Hi Roland!
What exactly do you suggest? Can we make some changes to Selenide that would solve the problem? 

This is known fact that **Selenium webdriver** doesn't work anymore with Firefox (starting from version 48 or like so). You either need to use old Firefox or geckodriver. 

But there is good news: try to upgrade to Selenide 4.8. It now downloads geckodriver automatically, so Firefox tests should now work again without a hassle.
