### ISSUE TITLE
Selenium assert descriptive message looks not good

### ISSUE THREAD

**Issue by Flash652** [codeborne/selenide#600]
With usual asserts, like **assertTrue("Element elementName not found on main page", isElementDisplayed());** in case of failure I had a very informative and good readable console message like: ** java.lang.AssertionError: Element elementName not found on main page**

In Selenide there is a deprecated method: $(locator).shouldBe("Element elementName not found on main page",Condition.exist);

Now, when I wait for element to appear I should use: $(locator).shouldBe(Condition.appear.because("Element elementName not found on main page"));
But in this case console message has no logic: 
By.xpath: "xpath locator" | should be(appear (because Element elementName not found on main page)) | FAIL 

I want to have something like:
By.xpath: "xpath locator" | should be(appear(but Element elementName not found on main page)) | FAIL

How can I do that? This is more logical than "because". Or I misunderstood something :(

**Comment by asolntsev** [comment]
Hi @Flash652 

Yes, the concept of `because` method is a little bit different.

First of all, I think that your error message "Element elementName not found on the main page" is simply not needed. It just duplicates the error message that Selenide throws when the element is not found. It adds nothing more. 

That's why `because` method is needed to **complement** the default Selenide error message. To give more details.  Simply said, Selenide says **what** happened (element X not found), and your provided `because` method says **why** it was expected. 

For example, 

```java
$("#error")
  .shouldBe(visible)
  .shouldHave(text("Please login").because("User should be logged out after entering wrong password 3 times"));
```

**Comment by Flash652** [comment]
Hello, Andrei!

I think I got the point. This `because` message and `assertTrue` message were created for a different purposes.

> It just duplicates the error message that Selenide throws when the element is not found. It adds nothing more. 

The thing is that selenide error message has only the locator which has failed. The path to elenemt, but not its name.
`Element should be hidden {By.xpath: locator}`
So the reason why I was asking about messages is that I want to see **the name of element/locator** to which this locator leads. For example "**Error pop-up** didn't appear" or "**Login button** is missing". In this case I do not have to go to my pageObject and look for the name of failed locator in its list. It was very convenient to see **what** was expected rather than **why**, that's all I'm saying :)

I think that's just a habit thing :) Thank you!

**Comment by Flash652** [comment]
Hello again!
I've tried this `because` style and actually I like it. I think the problem was that I wasn't accustomed to this feature yet.
