### ISSUE TITLE
Add waitUntil for collection

### ISSUE THREAD

**Issue by SergeyPirogov** [codeborne/selenide#601]
Sometimes we need to for some collection condition. There is also method waitUntil for SelenideElement but not for Collections

At our project, we faced with the problem to wait for collection condition. Example
```
$$(".user - names").waitUnti(sizeGreaterThan(0),20000)
```

**Comment by asolntsev** [comment]
@SergeyPirogov Why not. Let's do it! :)

**Comment by pavelpp** [comment]
@SergeyPirogov , In a given example isn't it the same doing $(".user - names").waitUntil(exists, 20000) ? Here you only wait for at least 1 element, but I understand a use case for more than 1 elements.

**Comment by asolntsev** [comment]
Add method `$$.shouldHave(texts(...), 5000);`

**Comment by kovalkuz** [comment]
Hi! Couldn't use $$("locator").waitUntil(condition, timeout) in my test because method has protected access level. Could you please help to understand usage of this new feature?

**Comment by kovalkuz** [comment]
ps: used 4.13.0 version
