### ISSUE TITLE
It takes ages to move on to next scenario at failure

### ISSUE THREAD

**Issue by mikatoba** [codeborne/selenide#603]
I am using Selenide, and when a scenario fails at an assertion, it takes ages to move on to the next scenario.

It looks like it's taking a long time at invoke method of SelenideElementProxy, which looks to be called after getting the failure result at the assertion, and before @After hook.

I am using Selenide 4.6 and selenium-java version is 2.53.1.
Played around with combination of different selenide versions and selenium-java versions but no luck. 

Has anyone come across to this issue?

**Comment by asolntsev** [comment]
Please say your settings:
1. Configuration.timeout
2. Selenium implicit timeout

**Comment by mikatoba** [comment]
Hi @asolntsev,
I set both of them 4 second. 

Thanks,

**Comment by mikatoba** [comment]
Hi @asolntsev,

This issue was solved after deleting the project on my local, and cloning the repository to my local again, but after a few days, it's start happening again..

**Comment by asolntsev** [comment]
@mikatoba Well, how can I help?
Can I stably reproduce the issue?

**Comment by rosolko** [comment]
@mikatoba There are no feedback from you with steps and we not able to reproduce.
Reopen with steps or additional information.
Also update to latest version.
