### ISSUE TITLE
Get SoftAsserts exception when some action performed on some page element in @BeforeMethod 

### ISSUE THREAD

**Issue by esnelubov** [codeborne/selenide#614]
## The problem
Selenide throws `Using soft asserts, but without @SoftAsserts annotation` exception if there is some action performed on some page element in the test method annotated with TestNG' `@BeforeMethod` when using Soft Assertion Mode.

## Environment
* **Selenide Version: 4.7**
* **TestNG Version: 6.11**

## Code To Reproduce Issue

    @Listeners({ SoftAsserts.class })
    public class SimpleTest
    {
        @BeforeClass
        public void beforeClass()
        {
            Configuration.browser = "chrome";
            Configuration.assertionMode = Configuration.AssertionMode.SOFT;
        }
    
        @BeforeMethod(alwaysRun = true)
        public void setUp()
        {
            Selenide.open("https://www.google.com/");
            $(By.xpath("//input[@name='btnI']")).click();
        }
    
        @Test
        public void testMethod()
        {
    
        }
    }

**Comment by ostap-oleksyn** [comment]
Can be fixed with this [pull request](https://github.com/codeborne/selenide/pull/615).

**Comment by asolntsev** [comment]
Fixed in PR https://github.com/codeborne/selenide/pull/615
Going to release in Selenide 4.8
