### ISSUE TITLE
Find element syntax is weird in Kotlin

### ISSUE THREAD

**Issue by bootstraponline** [codeborne/selenide#619]
```kotlin
import com.codeborne.selenide.Selenide.`$`

object Main {

    fun logIn() {
        val user = "testing"
        val loginInput = "input[ng-model='simpleSignInFormData.login']"
   
        `$`(loginInput).value = user
    }
}
```

    `$` is pretty weird.

 $ without escapes isn't a valid method name in Kotlin. Is there a Kotlin friendly syntax for finding elements? I will probably just write a wrapper method for now.

```kotlin
fun find(cssSelector: String): SelenideElement {
  return getElement(By.cssSelector(cssSelector))
}
```

**Comment by asolntsev** [comment]
@bootstraponline Yes, $ is weird in Kotlin. 

Creating your own wrapper is not bad idea at all. Please take a look at these examples: https://github.com/selenide-examples/kotlin/tree/master/src/test/kotlin
