### ISSUE TITLE
What's wrong with ElementsContainer?

### ISSUE THREAD

**Issue by CaBocuk** [codeborne/selenide#620]
Dear Selenide maintainers :)
**Disclaimer:** I'm pleasured to use Selenide itself in my project just because it is absolutely awesome...
I absolutely love the idea of ElementsContainers and strongly recommend to use them in complex test projects. **BUT...** 
While using them in my autotests I faced some discouraging nuances. 

### I warn that it will be a VERY long post. I'm sorry in advance :)

# 1) Initialization of ElementsContainer's fields without FindBy annotation
This issue was described in #617 and fixed in #618 so all executions of my examples will be made on my local copy of repo with #618 being merged. So lets think that it is already fixed.

# 2) Initialization of ElementsContainer's fields without FindBy annotation but with Selenide.$(...) method
```
    public static void main (String[] args) {
        browser = "chrome";
        open("https://yahoo.com");

        $("#uh-search-box").sendKeys("Selenide");
        $("[type=submit]").click();
        $("#results").should(exist);

        SearchResult secondResult = page(SearchPage.class).results.get(1);
        secondResult.title.shouldHave(text("Selenide: concise UI tests in Java"));
    }

    private static class SearchPage {
        @FindBy (css = ".searchCenterMiddle>li")
        List<SearchResult> results;
    }

    private static class SearchResult extends ElementsContainer {
        SelenideElement title = $(".title");
    }
```
## What do I expect to see?
That `title `field of SearchResult class is being initialized correctly with SearchContext being set as one of  SearchResults elements
## What do I actually see?
```
Exception in thread "main" Element should have text 'Selenide: concise UI tests in Java' {.title}
Element: '<h5 class="title">Ad</h5>'
```
That whole driver was set to the title field as SearchContext. So Selenide finds not the title of second search result but some other element with `locator = ".title"`
## What to do?
Nothing :) **It is absolutely my fault**. I've forgotten that using Selenide.$(...) will always set driver as search context. But it opens the door to the 3rd nuance

# 3) Oh, God! I can use getSelf().$(...) !!!
Let's change only SearchResult class
```
   private static class SearchResult extends ElementsContainer {
        SelenideElement title = getSelf().$(".title");
    }
```
## What do I expect to see?
1) I go to ElementsContainer class source
2) I see `SelenideElement self` there and getter+setter for it
3) I get the idea that I can use it to set SearchContext for my `title` field and everything will work okay!
## What do I actually see?
**NullPointerException.**
## Why?
If we go to `SelenideFieldDecorator#initElementsContainer` we see the following code:
```
private ElementsContainer initElementsContainer(Class<?> type, SelenideElement self)
      throws InstantiationException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {
    Constructor<?> constructor = type.getDeclaredConstructor();
    constructor.setAccessible(true);
    ElementsContainer result = (ElementsContainer) constructor.newInstance();
    SelenidePageFactory.initElements(new SelenideFieldDecorator(self), result);
    result.setSelf(self);
    return result;
  }
```
1) Object of our container is being created on the 3rd line of method body after calling `constructor.newInstance()`
2) Alongside with creating the instance of our container - `title` field is being also initialized with `getSelf().$(".title");`
3) But on this line of code getSelf() method will return null just because setSelf(self) is being called only on 5th line :)
## What to do?
In fact I don't know exact solution how to init `self` field before initialization of other fields of Container class. 
Probably we may define a **constructor** in ElementsContainer which will receive SelenideElement as parameter. But at the same time it will make all the classes that extend ElementsContainer to override and reuse these constructors.
But anyway it is not evident for user that if he wants to pass some SearchContext to his container's fields -> he will get NPE.
So in fact the only variant to init fields in container to be sure that they will be initialized correctly - to use FindBy annotation. 
**But should we be sure?..**

# 4) I don't want PageObjects! Let's initialize containers directly with page(...) method!
## What do I expect?
As it is written in some examples... Also @asolntsev mentioned this fact... We can initialize our containers using method `Selenide.page(Container.class)`.
I am a very-very-very smart developer with experience in HtmlElements and I think that if I want to pass a SearchContext for my container's fields I have to specify FindBy annotation right to the container's class!
```
    public static void main (String[] args) {
        browser = "chrome";
        open("https://yahoo.com");
        $("#uh-search-box").sendKeys("Selenide");
        $("[type=submit]").click();
        $("#results").should(exist);

        SearchResult firstResult = page(SearchResult.class);
        firstResult.title.shouldHave(text("Selenide - Wikipedia"));
    }

    @FindBy (css = ".searchCenterMiddle>li")
    private static class SearchResult extends ElementsContainer {
        @FindBy(css = ".title")
        SelenideElement title;
    }
```
## What do I get?
```
Exception in thread "main" Element should have text 'Selenide - Wikipedia' {.title}
Element: '<h5 class="title">Ad</h5>'
```
Hey! Come on! Again? :( The same as in point 2?
## Why?
Let's go to `Selenide#page(T pageObject)` method
```
  public static <PageObjectClass, T extends PageObjectClass> PageObjectClass page(T pageObject) {
    SelenidePageFactory.initElements(new SelenideFieldDecorator(getWebDriver()), pageObject);
    return pageObject;
  }
```
In the first line of the method body we see that it ALWAYS uses WebDriver as SearchContext. It doesn't even look on annotation that may be set for the container's class.
## What to do?
I suggest to check whether we are working with ElementsContainer instance and whether it is annotated with FindBy before calling initElements method. And depending on the object we're decorating we should set different SearchContexts.

# 5) And the last one... ElementsContainer does not implement SelenideElement :(
A bit of discussion about this problem you can read [here](http://ru.selenide.org/documentation/page-objects.html#comment-3538587083) (in Russian) But I will also describe it here.
Selenide is being presented as **'UI tests with clean, short and easy-readable code'**. But what do we see when we try to work with ElementsContainers?..
Let's imagine that we have a case we want to work with our container like with usual element which can be displayed and not displayed. Which can exist and not exist... Etc.
## Example
For example I have a popup which can appear on several pages. I'm a very-very-very smart developer (oh, again) and I know that I can use ElementsContainer not to duplicate the code. And I create class Popup which extends ElementsContainer.
**Popup can:**
- exist/not exist
- be visible/not visible
- find elements in it
- have attributes that we may want to check
- disappear after pressEscape()
- etc.

And if I want to do all of this with my popup, I have to do following:
- `popup.getSelf().should(exist)` instead of `popup.should(exist)`
- `popup.getSelf().shouldBe(visible)` instead of `popup.shouldBe(visible)`
- `popup.getSelf().$(...)` instead of `popup.$(...)`

Also as we've learnt in point 4)... all of these method will throw **NPE** in case if we have initialized our popup with `page(Popup.class)`.
## What to do?
In my opinion it is musthave for ElementsContainer to implement SelenideElement interface with following template:
```
public *** methodName(...) {
  this.getSelf().methodName()
}
```
But in my humble opinion the problem solve should not only in implementing SelenideElement but also in review of all the concept of ElementsContainer. Probably that would be good to present the ElementsContainer not just as container but as **'Element with elements'**.
**And add some rules on working with them e.g.:**
- If you initialize container with `Selenide.page(...)` method -> your container class should be annotated with FindBy or you can pass the element which will be set as `self`
- If you initialize a page which contains a container -> container field or container's class should be annotated with FindBy

 I think that mentioned positioning of ElementsContainers may solve some of issues listed above.

And I'm very sorry again about this long post :)

**Comment by asolntsev** [comment]
@CaBocuk Thank you for such a deep analysis! 

I absolutely agree that the whole concept of `ElementsContainer` should be reviewed. We created it a long time ago, even before inventing `$` method and its lazy evaluation. Later I discovered that `ElementsContainer` is not needed at all, because the same goals can be easily achieved with simple Java code using just `$` method and nothing more. 

Let's modify your initial code a little bit:

```java
public static void main (String[] args) {
        browser = "chrome";
        open("https://yahoo.com");

        $("#uh-search-box").sendKeys("Selenide");
        $("[type=submit]").click();
        $("#results").should(exist);

        SearchResult secondResult = new SearchPage().result(1);
        secondResult.title.shouldHave(text("Selenide: concise UI tests in Java"));
    }

    private static class SearchPage {
        public SearchResult result(int index) {
           return $(".searchCenterMiddle>li", index);
        }
    }

    private static class SearchResult {
       private final SelenideElement result;
       SearchResult(SelenideElement result) {
           this.result = result;
       }
       SelenideElement title() {
            return result.$(".title");
        }
    }
```

You see no annotations, no containers, no magic. Plain and simple. 

So, the easiest way to fix `ElementsContainer` is probably to remove it.

**Comment by asolntsev** [comment]
@CaBocuk Anyway, I will write my thoughts in details.

1. has been merged
2. agree, nothing to do
3. I also think it's a bad design. We should not add method `getSelf()` and especially `setSelf()` - which is, OMG, **public**! It was a long time ago, and we were young. :)
4. We assumed that the right usage of `ElementContainer` is putting `@FindBy` on is declaration:

```java
  private static class MyPage {
    @FindBy (css = "#apostrophes-and-quotes")
    MyContainer container;
  }

  private static class MyContainer extends ElementsContainer {
    SelenideElement headerLink = $("h2>a");
    ElementsCollection options = $$("#hero>option");
  }
```
But probably you are right, method `page(MyContainer.class)` could also understand annotation `@FindBy` on the class itself. But overall, is it worth? Life without containers is just simpler, as I mentioned in previous comment.

5.  Agree, `ElementsContainer` could implement `SelenideElement`. But again, is it worth wasting time implementing it?

**Comment by CaBocuk** [comment]
Hi, @asolntsev. I think it's worth :)

### Is it simple?
First of all, I think you have an error in your first post. If I'm not wrong it should be like:
```Java
    private static class SearchPage {
        public SearchResult result(int index) {
           return new SearchResult($(".searchCenterMiddle>li", index));
        }
    }
```
And does it seem to be plain and simple now?) IMHO - no.
Probably it is my personal thing but I feel pain using constructors directly. Probably because I used to work with frameworks where we had to do `Element el = new Element(driver, By.cssSelector("someselector"));`... But who knows...

### ElementsContainer + SelenideElement
This problem remains the same :) So after removal if smb wants to use his own containers (e.g. popups) in a convenient way -> he will need to develop his own kludges.
So if Selenide is presented as a solution accelerator -> why shouldn't we add it from box? And should we remove it totally?


### What should clients do if we remove ElementsContainers?
As I know there are thousands of projects using Selenide. So can we be sure that no one of them are using ElementsContainer functionality now? Personally I don't think so.
In this case I'm a bit lucky just because I've just started using ElementsContainers and the effort for refactoring it to my own containers won't be so huge. But what about others? Can we be sure that customers or POs will give 'em enough time and money to refactor? I think for some projects it would be much easier not to use latest versions of Selenide

### Extra-functionality
Even if arguments above are not too strong... Just why don't we provide extra-functionality for the users so everyone may use it according to his/her own POV.
As for me, again, I see it to be more convenient not to do everything on my own (calling constructor, implementing SelenideElement and working with its logics) but to define the annotation which is well-known to every Junior-AutoQA and allow some magic to happen :)
I just suggest to make this magic a bit better

### Implementation
I understand that my feature request isn't probably worth the effort of main maintainers just because I'm the first who is complaining about that. 
So I could try to implement the concept-review. The only question is the **concept** itself.

**Comment by asolntsev** [comment]
@CaBocuk Sure, we cannot delete it. Many people probably already use it. It was just a kind of thinking process. :)

Yes, sure, feel free to implement the concept. 

P.S. Still, creating a constructor **is not** more complex than adding an annotation.

**Comment by CaBocuk** [comment]
@asolntsev I knew that kitten's tears will do the job! :)
Anyway to start doing smth I need to have concept being approved.

1. If we decide to implement SelenideElement interface in ElementsContainer -> so that means that ElementsContainer should always have 'self' being initialized.
2. I didn't find good ways to allow initialization of containers' fields with getSelf().$(...) - not sure how to guarantee initialization of 'self' before the fields... Or should we restrict this way of fields initialization? Not sure again... Just because we may to this in usual Pages. What should we do?)
3. If we want to initialize our container with 'page(Container.class)' -> we have to specify @FindBy annotation on the class, right? So it's a good thing to add this feature, but...
4. But what should Selenide do if annotation isn't specified? Exception or smth else?
5. Should we allow to initialize containers in the following way 'page(Container.class, selfElement)'? Or probably it's better to allow to initialize containers with separate methods like 'container(Container.class)' and 'container(Container.class, selfElement)'?

**Comment by vinogradoff** [comment]
Sorry guys, I have not read and understood the whole discussion above (lack of time), will do later.

Just keywords. I solve the "Elements container"-Problem in my tests in the KISS way:

<PageObject class>
```
SelenideElement container=$("div-with-my-widget"),
                       buttonWithNonUniqId=container.$("#button");

```
That's it. If I use it, example:

`new PageObject().buttonWithNonUniqId.shouldBe(visible);`

nothing more. It just work.

Could it possibly solve at least some of your problems?

**Comment by CaBocuk** [comment]
Hi, @vinogradoff. Thank you for the reply
If I understood you correctly -> your advice would help in case if the locator of my container is the same on all pages. So yes, we can do it specifying `SelenideElement container` field, or just doing smth like this if it is important for us to use ElementsContainer's functionality:
```Java
public class Container extends ElementsContainer {
  {
    setSelf($("somelocator"));
  }

  SelenideElement element = getSelf().$("anotherlocator");
}
```
But in other cases (e.g. if I describe some DDL container) -> locators may be different and we have to specify it on every single page that contains the container.

And how to do that in a good way is one of the main questions of this thread)

**Comment by vinogradoff** [comment]
What is the purpose of Container or ElementsContainer classes?

> would help in case if the locator of my container is the same on all pages

Why the same? Any container!

```
class LoginForm
SelenideElement container=$("div1"),
               login=container.$("#login");
```

```
class OrderForm
SelenideElement container=$("div2"),
               orderBtn=container.$("#btn");
```

Do you want to compose e.g. HomePage with LoginForm? No Problem (I don't think, it is necessary at all, but you can).

```
class HomePage
   LoginForm form;
```

If you mean, you have different container "selectors" for different places, like

class OrderForm
SelenideElement container=$("div2/div3"),  // OrderForm at 2 pages, one as div2, second as div3
               orderBtn=container.$("#btn");
```

then you should check if it *is* the same OrderForm. Sometimes it looks the same, but there are 2 classes (copy&paste) in the developer's code. Then I would just mimic it to avoid problems, if the order form will be changed at only one of the side.
So just do OrderFormForBusinessCustomers, OrderFormForPrivateCustomer for example, even if they are the same now - it is probable they will change separately.

**Comment by CaBocuk** [comment]
Hmm... I think I've started understanding your world outlook... But anyway I continue finding examples from my experience that I can't fit to yours concept. Let's look at them:

### Various locators
If I understood you correctly (again)... Your approach with specifying possible locators right inside container class doesn't fit cases when our container can be used in a lot of pages and it has different locators on each page -> our selector for container initializing will be enormous and unmaintainable.

Another example - **tables**. Just imagine that my container describes the usual table on some page. We can do:
```Java
class Table {
  SelenideElement container = $("table");
}
```
And this approach will work in 99% cases. 
But what if we have **two or more** tables in the page? We have to set separate locators for each table e.g. $("table.clients"), $("table.admins"). Now we can do:
```Java
class Page {
  @FindBy(css="table.clients")
  Table table1;

  @FindBy(css="table.admins")
  Table table2;
}
```
But if we don't have ElementsContainers at all... Should we create two (or more) classes with only locators different? Or should we create one super-class Table and its children with only getContainer() being overrided? I think that it just makes the autotest-project structure more complex.

### But we could specify a constructor in Table class!!!
```Java
class Table {
  SelenideElement container;
  public Table (SelenideElement el) {
    container = el;
  }
}
```
But in this we come back to my discussion about them with @asolntsev :) Anyway, even this approach will hardly work with case if we want to deal with **list of containers** -> we'll have to initialize our containers in following way:
```Java
public SearchResult result(int index) {
  return new SearchResult($(".searchCenterMiddle>li", index));
}
```
What doesn't seem to be so nice and simple as Selenide is in all other ares but ElementsContainer :)

### How to work with containers as elements
Also IMO your approach returns us to the last problem from the initial post)
Anyway to check whether our table exists/visible/etc. we'll have to do `form.container.shouldBe(visible)` which is the same as `form.getSelf().shouldBe(visible)`.
But implementing SelenideElement out of the box would allow to use `form.shouldBe(visible)` what is much more cute :)

### Conclusion
I don't mean that your approach is bad. I understand that your ideas will work in most of cases.
But I'm so lucky that I have definitely those cases which don't fit :( And probably I'm not the only one. So I just suggest to add more **flexibility** and increase the range for approaches

**Comment by vinogradoff** [comment]
I find the PageObject Table awful in almost all cases. Do you really have the very same table at every page?
Trying to build  the magical one-size-fit-all "Table" developers are just wasting much time when they handle different tables.
In my Project I just have:
UsersTable, AdminsTable (at AdminPage), CustomersTable, OrdersTable and so on. No inheritance, no coupling and no magic. 
Straight forward code for every single Table, you use just the things you need. 

I can have a common TableControl's widget (like thing with new/edit/delete Button) - because it is really the same each time. Tables are different.

**Comment by CaBocuk** [comment]
I understand that I'm not the most experienced autoqa in the world, but... All tables that I've worked with had rows and columns :) Almost all tables that I've worked with had similar HTML implementation in terms of one project. For example - <table><tr><td></td></tr></table>. 
I've never seen that in terms of one site first table on the page was table-tr-td, and the second one (almost similar) was div-div-div... So it allows us not to duplicate tons of code to work with such tables but to create a separate container which will allow us to use common api to deal with rows, columns and cells.

Probably I'm wrong and there are lots of examples where similar elements are implemented in different ways but anyway the business is not about tables themself but about the approach in general. Table was just an example of some container that could be not alone in the page.
Some other variants are: datepickers (calendars), DDLs (if not usual selects), items in listings (e.g. videos on youtube), textfields with suggestions, etc. Their behaviors can be formalized and be put in one class which will describe these behaviors.
So in my humble opinion creating a separate block for each container will cause huge code-duplication in cases of big projects.

BTW I know about KISS POs from your old talk on QA Fest and I agree with some points. But at the same time IMO even those KISSes are not always suitable)
And again. I just suggest to make Selenide more **flexible** and easy-to-use for some kind of tasks.

**Comment by vinogradoff** [comment]
Just go ahead and write your Table-class and inherit from them, Selenide doesn't regulate any inheritance. Try to formalize every element and write your own Elements framework. It is probably more fun to do, I agree. 

I can't see what do you want to inherit from Table class, which behavior? You probably have different columns, differents rows, different checks every time.

I don't understand methods getColumnAndRow(5,3) in PageObjects, you don't need them. I have methods like - getFirstUsername(), getLatestOrderLine() etc. to check what I need to check without overhead of building Framework which can read any line, and any column.

Tests are: Arrange-Act-Assert, not about generic operation on every element on your pages.

**Comment by vinogradoff** [comment]
I would recommend to deprecate ElementContainer, it was probably a tribute to HTMLElements fashion back then in 2013.... I can do just fine without it.

**Comment by vinogradoff** [comment]
> So, the easiest way to fix ElementsContainer is probably to remove it.

Now I've read it :) Of course it is! :)

Another solution with less code:

```


public static void main (String[] args) {
        browser = "chrome";
        open("https://yahoo.com");

        $("#uh-search-box").sendKeys("Selenide");
        $("[type=submit]").click();
        $("#results").should(exist);

       new SearchResults().secondResultTitle.shouldHave(text("Selenide: concise UI tests in Java"));
    }

  
    private static class SearchResults {
          SelenideElement secondResult=$(".searchCenterMiddle>li",1),
                     secondResutlTitle=secondResult.$(".title");
        }
    }

```

**Comment by asolntsev** [comment]
@CaBocuk What should we do with this issue? Can we close it?
As I remember, you wanted to implement your concept in a separate pull request. Did you have chance to do it?

**Comment by CaBocuk** [comment]
@asolntsev I've reviewed my philosophical views 😄 I think we can close it
