### ISSUE TITLE
Add computedCssValue (other name?) Condition 

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#628]
Selenium has the method getCssValue which can process the actual computed values of css-styles

```
getCssValue("color")
getCssValue("background-color")
getCssValue("font")
getCssValue("font-size")

```
etc.

We should add the condition, that uses this for Selenide Condition to enable easy coding for examples like

```
element.shouldHave(computedCssValue("color","#00FF00"));
element.shouldHave(computedCssValue("font-size","24"));
```

etc. with-in typical Selenide Workflow  to automatically benefit from waiting, screenshoting, clear error messages etc.

**Comment by vinogradoff** [comment]
I think that name "cssValue" will be confusing for many users, who may think, conditions looks in DOM for some css attributes.... 
"Computed" - gives a hint, that it is the actual value which depends on many variables (included css files, css classes, custom style attrbutes etc.).

Perhaps you could think of even better name? 

computedCssStyle perhaps?

**Comment by kkochetov** [comment]
something like that?
```
    public static Condition cssAttribute(final String attributeName, final String expectedValue) {
        return new Condition("cssAttribute") {
            @Override
            public boolean apply(WebElement element) {
                return expectedValue.equalsIgnoreCase(element.getCssValue(attributeName));
            }

            @Override
            public String actualValue(WebElement element) {
                return element.getCssValue(attributeName);
            }
        };
    }
```

**Comment by BorisOsipov** [comment]
>I think that name "cssValue" will be confusing for many users, who may think, conditions looks in DOM for some css attributes. "Computed" - gives a hint, that...

I think it's ok to call it "cssValue" as is in Selenium. It will make reference to the original Selenium method call.

**Comment by vinogradoff** [comment]
I agree.

Viele Grüße

Alexei Vinogradov
