### ISSUE TITLE
Expect ElementNotFoundException when selecting non-existing option from <select>

### ISSUE THREAD

**Issue by cbxp** [codeborne/selenide#633]
Having HTML like this:
```html
<select name="foo">
  <option value="xxx">XXX</option>
</select>
```

And Selenide call like this:
```java
$(By.name("foo")).val("bar");
```

We expect this statement to fail with an exception stating that this option does not exist. Currently it will continue without failing.

**Comment by asolntsev** [comment]
Duplicate of https://github.com/codeborne/selenide/issues/709
Fixed in Selenide 4.12.4
