### ISSUE TITLE
Problems with browser instances

### ISSUE THREAD

**Issue by JoK89** [codeborne/selenide#637]
I don´t know if it´s really reportable, but I´m facing an issue with selenide 4.8 since last week:

Everytime, before my tests are starting, I´m setting properties for the download path in google chrome. Before the update to 4.8 it worked perfectly fine. 
Now everytime trying to open my website with Selenide.open(myURL), there is a new chrome window popping up, logically without the set properties, so the download goes to my default download path and not in my set path.

my environment:
- Selenide Version: 4.7 - 4.8
- Chrome Version: 62
- Browser Driver Version: 2,29

the properties i´m setting: 

        HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.default_directory", downloadDirFilepath.toAbsolutePath().toString());
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("prefs", chromePrefs);
        DesiredCapabilities cap = DesiredCapabilities.chrome();
        cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        cap.setCapability(ChromeOptions.CAPABILITY, options);
        WebDriver driver = new ChromeDriver(cap);
        driver.manage().window().maximize();

**Comment by BorisOsipov** [comment]
Hi
how do you set driver to selenide?
provide full example and console logs.

**Comment by JoK89** [comment]
Hi,

 

i´m not working with the tests at the moment, but i´ll provide you some examples at thursday. There was an Issue with our Gui so i could not work on the tests.

 

Gesendet: Dienstag, 16. Januar 2018 um 11:16 Uhr
Von: "Boris Osipov" <notifications@github.com>
An: codeborne/selenide <selenide@noreply.github.com>
Cc: JoK89 <jo_k@arcor.de>, Author <author@noreply.github.com>
Betreff: Re: [codeborne/selenide] Problems with browser instances (#637)


Hi
how do you set driver to selenide?
provide full example and console logs.

**Comment by JoK89** [comment]
Hi Boris,

 

so here´s my setup for the chrome driver:

 


@Override
public void initialize() {
    logger.info("Setup Chrome browser");

    HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
    chromePrefs.put("profile.default_content_settings.popups", 0);
    chromePrefs.put("download.default_directory", downloadDirFilepath.toAbsolutePath().toString());
    ChromeOptions options = new ChromeOptions();
    options.setExperimentalOption("prefs", chromePrefs);
    DesiredCapabilities cap = DesiredCapabilities.chrome();
    cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
    cap.setCapability(ChromeOptions.CAPABILITY, options);
    WebDriver driver = new ChromeDriver(cap);

    driver.manage().window().maximize();
}

at this point, an new browser window is openend

 

 

I have splittet the setup of every browser in its own class, so in the BaseTest-Class i´m doing this:

 


@BeforeSuite
public void launchSite() throws IOException {
    // create temp download directory
    logger.info("Create temp download directory");
    downloadDirFilepath = Files.createTempDirectory("myDirectory_");

    BrowserSetup.setupConfiguredBrowser(browser, downloadDirFilepath);

    logger.info("Open SWAN on url [{}]", myUrl);
    Selenide.open(myUrl);
}

after this, Selenide is not open the URL in the existing window, but creates a new window with the Selenide.open(), so all properties i´m setting are getting lost.

 

I hope you can see the problem I´m facing.

 

 

 

 



 

Gesendet: Dienstag, 16. Januar 2018 um 11:16 Uhr
Von: "Boris Osipov" <notifications@github.com>
An: codeborne/selenide <selenide@noreply.github.com>
Cc: JoK89 <jo_k@arcor.de>, Author <author@noreply.github.com>
Betreff: Re: [codeborne/selenide] Problems with browser instances (#637)


Hi
how do you set driver to selenide?
provide full example and console logs.

**Comment by BorisOsipov** [comment]
Hi @JoK89 

As I can see In your code you just create your own configured chrome driver, but you don't tell Selenide about it. 
You can do it by `WebDriverRunner.setWebDriver(myChromeDriver)`

Find more details here- https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver#how-to-run-selenide-with-another-browser

**Comment by JoK89** [comment]
well, shame on me. It works perfectly fine. Thanks a lot for your help!
 

Gesendet: Donnerstag, 18. Januar 2018 um 11:29 Uhr
Von: "Boris Osipov" <notifications@github.com>
An: codeborne/selenide <selenide@noreply.github.com>
Cc: JoK89 <jo_k@arcor.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codeborne/selenide] Problems with browser instances (#637)


Hi @JoK89

As I can see In your code you just create your own configured chrome driver, but you don't tell Selenide about it.
You can do it by WebDriverRunner.setWebDriver(myChromeDriver)

Find more details here- https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver#how-to-run-selenide-with-another-browser
