### ISSUE TITLE
 NoSuchSessionException in parallel classes run TestNG

### ISSUE THREAD

**Issue by apanashchenko** [codeborne/selenide#640]
## The problem
Hi to all,
I try run tests in parallel. I use Selenide and testNG. Run test in parallel via http://testng.org/doc/documentation-main.html#parallel-tests .  When my first test class finished and second test class in progress I see:
Caused by: NoSuchSessionException: no such session

## Tell us about your environment
* **Selenide Version: 4.8**
* **Chrome: Version 62.0.3202.94**
* **TestNG: 6.11**
* **OS Version: MacOS**

## Code To Reproduce Issue [ Good To Have ]
Add project example:
[selenide-parallel-example.zip](https://github.com/codeborne/selenide/files/1527172/selenide-parallel-example.zip)

**Comment by BorisOsipov** [comment]
Actually it is TestNg bug https://github.com/cbeust/testng/issues/1185

I modified your project example with printing current thread name in each method.
As you can see some test methods runs in different threads: 
BingTest.setUp: pool-1-thread-2
BingTest.search: pool-1-thread-2
BingTest.findResults: pool-1-thread-2
BingTest.tearDown: pool-1-thread-2
GoogleTest.setUp: pool-1-thread-1
**GoogleTest.search: pool-1-thread-1
GoogleTest.search1: pool-1-thread-1
GoogleTest.findResults: pool-1-thread-2
GoogleTest.findResults2: pool-1-thread-2**
GoogleTest.tearDown: pool-1-thread-2

So removing DependsOnMethods should help you.
Feel free reopen the issue if I am wrong.
