### ISSUE TITLE
Selenide ClassNotFoundException: com.codeborne.selenide.Selenide

### ISSUE THREAD

**Issue by jjunest** [codeborne/selenide#642]
## The problem
MY Problem - ClassNotFoundException!

Hi. i'm trying to use selenide in java web Spring project.

so, i'm following the 'quick start' in selenide site.

i added the selenide by maven in pom.xml and i'm trying to run the code "open("/login");".

Java compiler don't show the error message which is red line when i imported the "import static com.codeborne.selenide.Selenide.*".

but when i run the code, they can not load the Selenide Class, saying ClassNotFoundException.

why is it happened? any clause?

below is what i have done to use the Selenide.

step1) install the firefox browser.
step2) import library in pom.xml (using maven) - selenide & selenium both. 
step3) download the firefox driver. and system setting the firefoxdrier. ( to install gecko driver ? i don't know, )
step4) run the sample code in selenide Site "quick start" menu - only run the "open()" method
step5) ERROR: classNotFound Exception!!!
step6) I can RUN the selenium method with NO PROBLEM like classNotFoundException, BUT selenide didn't work in my project . please help me.

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version:**
	
		<dependency>
			<groupId>com.codeborne</groupId>
			<artifactId>selenide</artifactId>
			<version>4.8</version>
			<scope>test</scope>
		</dependency>

* **Chrome\Firefox\IE Version:**
latest firefox version
* **Browser Driver Version:**
geckodriver-v0.19.1-win64 

* **Selenium Version:**
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.7.1</version>
		</dependency>
* **OS Version:**
window 7 64bit

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.
package com.innovest.hospitalCrawling2;

import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.*;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.codeborne.selenide.Selenide;

/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);
		
		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
		
		String formattedDate = dateFormat.format(date);
		
		model.addAttribute("serverTime", formattedDate );
		System.setProperty("webdriver.gecko.driver",
				"C:\\Users\\Administrator\\Downloads\\dev\\geckodriver-v0.19.1-win64\\geckodriver.exe");
		System.out.println("this is main started");
		WebDriver driver = new FirefoxDriver();
		driver.get("http://www.toolsqa.com");
		open("/login");
		try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		driver.quit();
		
		
		return "home";
	}
	
}
-------------------ERROR happened in open() METHOD : ClassNOTFOUNDException--------------------

**Comment by asolntsev** [comment]
@jjunest  Whaaaat!
Why do you need to run Selenide from **web application**? Why do you need Spring at all?

Selenide is for running from tests. 
Just create a test with JUnit, TestNG or something similar. Then it works.

**Comment by jjunest** [comment]
thanks for your answer.

i'm trying to make web application which can auto-fill behalf of the users.

is selenide library not working in spring web projects?

**Comment by jjunest** [comment]
And i have another question.

when i deleted the <scope>test<scope>, the selenide can load the firefox browser. (when i code run open("http://www.google.com");

but. even firefox browser pops up, the firefox has the error called timeout exception.

only browser pops up, but no actions in browser are showed.

what is the reason of the problem? thanks in advance:)

**Comment by asolntsev** [comment]
@jjunest Selenide works with Spring. But it's not intended to work in web application. Anyway, the problem is definitely with your dependencies. Could you share the entire pom.xml?

**Comment by jjunest** [comment]
hello asolntsev. thanks for your answer.

I solved the problem! it was the <scope>test</scope> in my pom.xml;

when i deleted the <scope>test</scope>, it works in the Spring.

thanks for your advice

**Comment by rosolko** [comment]
Looks like this issue is solved.
Feel free to reopen if needed.
