### ISSUE TITLE
how can I set the headless driver in selenide? like PhantomJsDriver?

### ISSUE THREAD

**Issue by jjunest** [codeborne/selenide#644]
## The problem

Hello. i'm making the web crawler using selenide library.

i'm trying to set the PhantomJsWebDriver .

but when I create PhantomJsWebDriver (which is okay in the other project), with selenide maven import.

It has error saying, [java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.<init>(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker
	at org.openqa.selenium.net.UrlChecker.<init>(UrlChecker.java:66)].

how can i make PhantoJSDriver ??

thanks in advance:) 

 

## Details

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		// Set executable file path to system variable phantomjs.binary.path's value.
		String phantomjsExeutableFilePath = "C:\\Users\\Administrator\\Downloads\\dev\\phantomjs-2.1.1-windows\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe";
		System.setProperty("phantomjs.binary.path", phantomjsExeutableFilePath);

		// Initiate PhantomJSDriver.
		WebDriver driver = new PhantomJSDriver();
		driver.get("https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/8088");

		
		WebDriverRunner.setWebDriver(driver);
		
		System.out.println("this is pageSource:" + driver.getPageSource());
		return "home";
	}

## Tell us about your environment
* **Selenide Version:**  
	<dependency>
			<groupId>com.codeborne</groupId>
			<artifactId>selenide</artifactId>
			<version>4.8</version>
		</dependency>

* **Chrome\Firefox\IE Version:**
 	
		<dependency>
			<groupId>com.codeborne</groupId>
			<artifactId>phantomjsdriver</artifactId>
			<version>1.2.1</version>
		</dependency>

* **Browser Driver Version:**

	
		<dependency>
			<groupId>com.codeborne</groupId>
			<artifactId>phantomjsdriver</artifactId>
			<version>1.2.1</version>
		</dependency>

* **Selenium Version:**
	
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.44.0</version>
		</dependency>

* **OS Version:**
window 7 64bit

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@jjunest The problem is with your dependencies.
You use the latest Selenide version 4.8, but very old Selenium version 2.44.0
You could look that Selenide 4.8 is built with selenium-java 3.6.0

**Comment by espaciomore** [comment]
Hi,

Is there any integration with TrifleJS?

I'm having issues with PhantomJS and the driver is not being supported or updated since more than 2 years. My issue is due to driver not being able to load the content of child frames.

**Comment by rosolko** [comment]
@espaciomore 
If you want to run tests in headless just pass configuration `Configuration.headless=true;` it works for chrome and firefox.
Also integration with trifflejs is missing.

**Comment by espaciomore** [comment]
Is there a way to fake the user-agent string so that I tell Selenide to set the HTTP request as X Web Client?

Because, I'm testing a website that's only visible on IE11.
