### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/security/Credentials at com.codeborne.selenide.Selenide.<clinit>(Selenide.java:37)

### ISSUE THREAD

**Issue by nitrok** [codeborne/selenide#645]
## The problem
First call to selenide code $(By.xpath(LOGIN_EDIT)) cause  exception
java.lang.NoClassDefFoundError: org/openqa/selenium/security/Credentials

	at com.codeborne.selenide.Selenide.<clinit>(Selenide.java:37)
	at com.project_name.LoginPage.getLoginEdit(LoginPage.java:17)

## Tell us about your environment
* **Selenide Version:** 4.8
* **Chrome** Version 63.0.3239.108 (Official Build) (64-bit)
* **Browser Driver Version:** 2.34.522940
* **Selenium Version:** 3.8.1
* **OS Version:** win 10

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by BorisOsipov** [comment]
It is selenium 3.8.0 breaking changes issue.
As workaround downgrade your selenium version.

**Comment by nitrok** [comment]
Thank you @BorisOsipov !
As a workaround selenium version 3.7.1 fixes the issue.

**Comment by BorisOsipov** [comment]
@nitrok  Selenide 3.9 with 3.8.1 compatibility has been released. Try it.
