### ISSUE TITLE
Browserstack element clickable on iPhone8 but not Samsung S8

### ISSUE THREAD

**Issue by irwinj** [codeborne/selenide#647]
## The problem
I have a test suite running on BrowserStack Automate using Selenide. I have a mobile test path that I access via Browserstack's IPhone8 Safari browser and it has no problems accessing any of the elements on the screen and completing the whole path. When I started to try this path on a Samsung S8 in Chrome, I would get to the TOS page and Selenide is unable to click the #tos element below. It finds the element, and thinks it has clicked it, but nothing happens.
 

        > open("https://mywebsite.com");
        > sleep(6000);
        > $(By.name("login")).click();
        > sleep(6000);
        > assertEquals("XXX", title());
        > $(By.name("email")).sendKeys("gandalf@gmail.com");
        > $(By.name("password")).sendKeys("XXXXXXX");
        > $(By.name("submit")).click();
        > sleep(10000);
        > assertEquals("Home", title());
        > $(By.className("nav-btn")).click();
        > $(By.linkText("IP Registration")).click();
        > sleep(6000);
        > assertEquals("XXX Registration", title());
        > $(By.name("firstName")).sendKeys("Grey");
        > $(By.name("lastName")).sendKeys("Pilgrim");
        > $(By.name("email")).sendKeys("mithrandir@gmail.com");
        > $(By.id("role-ip")).click();
        > $(By.name("submit")).click();
        > sleep(6000);
        > assertEquals("XXX Registration", title());
        > executeJavaScript("window.scrollBy(0,1000)", "");
        > sleep(6000);
        > $(By.id("tos")).click();
        > sleep(6000);
        > $(By.name("submit")).click();
        > sleep(6000);
        > $(By.name("p1")).sendKeys("123456789");
        > $(By.name("submit")).click();

## Details
I started introducing elements such as scrolling the window down, additional waits, different types of selectors, all to no avail. The weird thing is that Selenide is finding the #tos element just fine and attempting to click it, but nothing happens. Then I get the "p1 element not visible" on what would be the next page if my errorController didn't stop the test moving forward. I'm a bit at my wit's end - I've tried every Selenide/Selenium fix I can find, including adding onclick listeners to all input fields. It's also quite strange because on the previous page of testing Selenium clicks an input of type radio button with absolutely no issues. I've even removed wrapping CSS styling that could've been getting in the way.
![screen shot 2017-12-18 at 3 39 17 pm](https://user-images.githubusercontent.com/15258971/34133467-c1c8a954-e409-11e7-9400-e290c64fef5f.png)
![screen shot 2017-12-18 at 3 46 59 pm](https://user-images.githubusercontent.com/15258971/34133635-c0cf1aa0-e40a-11e7-9b85-6aec2ebf51fb.png)
Example of users having similar issues:
https://stackoverflow.com/questions/47665226/browserstack-automate-test-click-action-not-work-on-android
Could be related to this as well:
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4637

## Tell us about your environment
* **Selenide Version:** 4.8
* **Chrome\Firefox\IE Version:** Chrome 58.0.3029
* **Browser Driver Version:** 2.29
* **Selenium Version:** 3.6
* **OS Version:** Samsung Galaxy S8, OS 7.0

**Comment by BorisOsipov** [comment]
Selenide uses Selenium underhood. If Selenium can not click to element I guess it is selenium issue and should be appropriately reported to Selenium issue tracker https://github.com/SeleniumHQ/selenium/issues/new

For workaround I can suggest turn on clickViaJs feature in Selenide. See https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/Configurat ion.java#L171

**Comment by BorisOsipov** [comment]
Closed due no feedback.

**Comment by irwinj** [comment]
Oh sorry was trying to find this thread before but couldn't. Tried the clickViaJs thing to no avail, thanks though
