### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/security/Credentials with Selenium 3.8.1

### ISSUE THREAD

**Issue by tiredgin** [codeborne/selenide#648]
## The problem
I'm getting java.lang.NoClassDefFoundError: org/openqa/selenium/security/Credentials on attempt to open URL.

```
org/openqa/selenium/security/Credentials
java.lang.NoClassDefFoundError: org/openqa/selenium/security/Credentials
	at com.codeborne.selenide.Selenide.<clinit>(Selenide.java:37)
```
## Details
I checked Selenium sources and found that `security` package is removed in Selenium 3.8.1, so I think this is the root of a problem.

## Tell us about your environment
* **Selenide Version:**4.8
* **Chrome\Firefox\IE Version:**Chrome 63
* **Browser Driver Version:**2.34
* **Selenium Version:**3.8.1
* **OS Version:**Win10x64

**Comment by BorisOsipov** [comment]
Hi @tiredgin 

You are right it is selenium compatibility issue.
As workaround I can suggest downgrade selenium to 3.8.0.

This issue fixed in https://github.com/codeborne/selenide/pull/638
I will ping you when we release Selenide 3.9 with 3.8.1 compatibility.

**Comment by tiredgin** [comment]
@BorisOsipov Great! Thank you!

**Comment by BorisOsipov** [comment]
@tiredgin 
Selenide 3.9 with 3.8.1 compatibility has been released. Try it.
