### ISSUE TITLE
Provide scrollIntoView to workaround problems in Firefox (equivalent to com.codeborne.selenide.commands.ScrollTo)

### ISSUE THREAD

**Issue by mseele** [codeborne/selenide#649]
## The problem

Let's provide a com.codeborne.selenide.SelenideElement.scrollIntoView() method (like the com.codeborne.selenide.SelenideElement.scrollTo() method) and call this code:

`((JavascriptExecutor) item.getWrappedDriver()).executeScript("arguments[0].scrollIntoView(true);", item.getWrappedElement()); //$NON-NLS-1$`

We need this to provide a workaround for https://github.com/mozilla/geckodriver/issues/776 & https://github.com/mozilla/geckodriver/issues/1039

## Details

Detail please see above

## Tell us about your environment
* **Selenide Version:** 4.8
* **Firefox Version:** 57.0.2
* **Browser Driver Version:** v0.19.1
* **Selenium Version:** 3.8.1
* **OS Version:** Windows 10 1709

## Code To Reproduce Issue [ Good To Have ]

It's just not possible to click to a button outside the scroll pane with firefox due to the bugs i've linked above. To wrap that inside selenide, it would be cool to provide this feature

**Comment by mseele** [comment]
Found a workaround for my problem:


```
// workaround for https://github.com/mozilla/geckodriver/issues/776
Commands.getInstance().add("click", new Click() { //$NON-NLS-1$
	@Override
	protected void click(WebElement element) {
		if (WebDriverRunner.isMarionette()) {
			executeJavaScript("arguments[0].scrollIntoView(true);", element); //$NON-NLS-1$
		}
		super.click(element);
	}
});
```

This is awesome, did not know until now that i can "override" SelenideElement actions. Insane.

**Comment by asolntsev** [comment]
Implemented in Selenide 4.10

**Comment by yvasylenko** [comment]
Hi, @asolntsev I'm interested in this fix for Windows 10 and Microsoft Edge 41, but after I upgraded to 4.10.01 I've got org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error

**Comment by BorisOsipov** [comment]
@yvasylenko please create sepparate issue with code example. We are not psychics to help without any code.

**Comment by yvasylenko** [comment]
@BorisOsipov I reproduced this issue on a simple case yesterday's evening (just open any page). But today everything works fine, without any changes. So there is no issue anymore.

P.S. How/Where can I contact you regarding possible workaround for safaridriver issue? Should I create another issue here?

**Comment by BorisOsipov** [comment]
@yvasylenko 

You can ask in gitter https://gitter.im/codeborne/selenide
Or in Russian speaking gitter https://gitter.im/codeborne/selenide-ru

**Comment by yvasylenko** [comment]
Ok, thanks for your attention, I'll write there.
