### ISSUE TITLE
WebDriverFactory#logBrowserVersion: Change class casting from "RemoteWebDriver" to "HasCapabilities"

### ISSUE THREAD

**Issue by ksimanenka** [codeborne/selenide#654]
## The problem

WebDriverFactory#logBrowserVersion(): Change class casting from "RemoteWebDriver" to "HasCapabilities"
 
Target method:
```
 void logBrowserVersion(WebDriver webdriver) {
    if (!isHeadless()) {
      Capabilities capabilities = ((RemoteWebDriver) webdriver).getCapabilities();
      log.info(
          "BrowserName=" + capabilities.getBrowserName() + " Version=" + capabilities.getVersion()
              + " Platform=" + capabilities.getPlatform());
    }
  }
```

The line to be changed: 
`Capabilities capabilities = ((RemoteWebDriver) webdriver).getCapabilities();`

## Details
I'm implemented a custom DriverFactory. Inside it, I wrap driver using Java Proxy. 
But I'm getting something like this: "java.lang.ClassCastException: com.sun.proxy.$Proxy8 cannot be cast to org.openqa.selenium.remote.RemoteWebDriver".

It seems reasonable to me to cast driver instance to HasCapabilities.

**Comment by asolntsev** [comment]
fixed in Selenide 4.10
