### ISSUE TITLE
Listeners  SoftAsserts:   Screenshot: null   for FAIL test

### ISSUE THREAD

**Issue by VadimGulich** [codeborne/selenide#655]
Listeners  SoftAsserts:   Screenshot: null   for FAIL
Selenide: 4.8
TestNG: 6.11

![image](https://user-images.githubusercontent.com/12964120/34374733-40c6d568-eaeb-11e7-844f-ed0b7a3eb16c.png)

**Comment by BorisOsipov** [comment]
Yes it is.
https://github.com/codeborne/selenide/blob/master/src/test/java/integration/testng/SoftAssertTestNGTest1.java#L13 indicate the same problem
