### ISSUE TITLE
Add editorconf file to the project

### ISSUE THREAD

**Issue by BorisOsipov** [codeborne/selenide#658]
## The problem
Contributes should have ability to avoid code style issues in his changes before commit.

@rosolko proposes his own editorconf in https://github.com/codeborne/selenide/pull/656#issuecomment-354273921 to help IDE applies code formatting automatically.

Need to think how to add it with the smallest changes in project.

**Comment by asolntsev** [comment]
@BorisOsipov @rosolko We can just add file `.editorconf` to the project.
I just tried: it doesn't automatically reformat the whole project. It only reformats those lines that you edit. It's absolutely ok for us.

P.S. Only IDEA supports `.editorconf` by default. Eclipse needs a separate plugin. But we cannot force all developers to install this plugin. So, do you think that the initial problem is solved in this situation?

**Comment by BorisOsipov** [comment]
@asolntsev 
For me the initial problem that Selenide uses Google code style formating by default. By default all IDE uses standard Oracle code style for java code.
`.editorconf` doesn't force users to do smth. It just helps to setup IDE automatically for current project.

P.S.
1) IDEA supports `.editorconf` by plugin too. But it intstalled by default.
2) `.editorconf` some kind of "standard" for code formating approah for different IDE like Atom, VS Code, etc

**Comment by asolntsev** [comment]
@BorisOsipov @rosolko Ok, then please review PR https://github.com/codeborne/selenide/pull/670

**Comment by rosolko** [comment]
editorconfig added
so the next step will be code formatting/refactoring related to config

**Comment by BorisOsipov** [comment]
I guess Andre's idea was to not apply configuration to project and reformat
it in one commit but step by step accept changes with contributors PR.

**Comment by rosolko** [comment]
@BorisOsipov yes, I just summarize next step, but yes, it will be in scope of PR, new functional and refactoring.
