### ISSUE TITLE
Add ability to specify custom capabilities during WebDriver creation

### ISSUE THREAD

**Issue by saboteurserg** [codeborne/selenide#663]
There are cases when you need to specify some custom capabilities. For example, here are some custom capabilities used in Selenoid :

```
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("screenResolution", "800x800x24");
```

It would be good to have parameter for this in configuration (and\or environment variable). For now you need to implement your own factory for webdriver creation if you want to use them.

Thank you!

**Comment by BorisOsipov** [comment]
@saboteurserg 
> For now you need to implement your own factory for webdriver creation if you want to use them.

you don't need.

You can pass any capabilities to driver by environment variables started with `capabilities.`. In maven like that:
`mvn test -Dcapabilities.enableVNC=true -Dcapabilities.screenResolution=800x800x24`
Is this what you wanted to have?

**Comment by saboteurserg** [comment]
@BorisOsipov 

yep that's what I need but example which you provide doesn't have any effect when I run it via IDE or from maven :(

**Comment by BorisOsipov** [comment]
@saboteurserg It is strange. For me it works like a charm. Can you prepare for me a simple project and steps to do to reproduce your issue?

**Comment by rosolko** [comment]
@saboteurserg For IDE you can customize default or selected test run task with custom parameters wia `VM Options` and will affect tests from IDE.

**Comment by saboteurserg** [comment]
@BorisOsipov , @rosolko - works now.. Thanks.. I don't know what I was doing wrong, because now I do everything the same and it's working...  I think this can be closed now
