### ISSUE TITLE
GlobalTextReport and TextReport doesn't work properly together with custom listeners which are implementing ITestListener

### ISSUE THREAD

**Issue by hanushs** [codeborne/selenide#671]
## The problem
GlobalTextReport and TextReport doesn't work properly together with custom listeners which are implementing ITestListener.

## Details
Let say i want do some custom action before and after tests. For this purpose i created custom listener which is implementing ITestListener.

But then when i  i give to my test list of listeners @Listeners({GlobalTextReport.class, ScreenShooter.class, CustomListener.class})  Selenide method SimpleReport.finish() doesn't do correct loging output in reference with invoked method.
What i mean exactly? The output of one test method can go in following test method output.
It is should be some kind of Thread.join() functionality so everything would wait for method fonosh() to finish execution. 

## Tell us about your environment
* Selenide Version: - 4.8
* **Chrome: -latest
* **Browser Driver Version: 
* **Selenium Version: 3.6
* **OS Version: Windows 10

## Code To Reproduce Issue [ Good To Have ]
Annotate any test with @Listeners({GlobalTextReport.class, ScreenShooter.class, CustomListener.class})  described in Details
![custom listener](https://user-images.githubusercontent.com/23035518/34946763-1915a72a-f9d6-11e7-8c21-57bd8b905784.PNG)
![wrong output selenide profiler](https://user-images.githubusercontent.com/23035518/34946764-192730f8-f9d6-11e7-9af6-e0e1c53c0116.PNG)

**Comment by BorisOsipov** [comment]
@hanushs 
1) It's IDEA test runs output and I don't know how IDEA format reference the log file and test tree item. So are there the same problem in plain log file e.g. on running test by maven\gradle\etc? If yes show us, please
2) TestNG doesn't guarantee order of Listeners execution. So you should not rely to execution order at all.

**Comment by hanushs** [comment]
@BorisOsipov thank you for clarification. Looks like output with maven is fine. So that is IDEA problem. Will close issue!! Sorry that i interrupted you.
