### ISSUE TITLE
Lazy field initialisation via collections is broken

### ISSUE THREAD

**Issue by pavelpp** [codeborne/selenide#672]
## The problem
FIY, this  [PR](https://github.com/codeborne/selenide/issues/641) breaks lazy initialisation for fields in form `SelenideElement el = $$(css).get(n);`. Now it will actually try to initialise the field and try to look for the element whenever class default constructor is called.

## Tell us about your environment
* **Selenide Version:** 4.10
* **Chrome\Firefox\IE Version:**  N/A
* **Browser Driver Version:** N/A
* **Selenium Version:** N/A
* **OS Version:** N/A

**Comment by BorisOsipov** [comment]
Looks like it was broken in https://github.com/codeborne/selenide/pull/653/

In this place
https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/ElementsCollection.java#L243-L245

**Comment by BorisOsipov** [comment]
@CaBocuk can you have look?

**Comment by CaBocuk** [comment]
Right - that's because of my fix. 
I'll try to investigate how to fix it without returning to re-evaluating of actual elements on every iteration.
Also it's a point for a unit test :)

**Comment by vinogradoff** [comment]
Looks very critical to me, we should probably revert the pr, if not fixed
very soon.

Viele Grüße

Alexei Vinogradov

**Comment by CaBocuk** [comment]
I think I have some hypotheses about a compromise for this case. Will check it tomorrow morning.

**Comment by BorisOsipov** [comment]
I guess guy from this thread http://automated-testing.info/t/selenide-4-10-perestal-zapuskat-chrome-novye-izmeneniya-v-versii/18420/3 ran into the same issue.
It very similar to @pavelpp problem behaviour.

>we should probably revert the pr, if not fixed
very soon.
+1

**Comment by asolntsev** [comment]
@BorisOsipov @CaBocuk @vinogradoff @pavelpp I have a fix. I am preparing a pull request.

**Comment by asolntsev** [comment]
@BorisOsipov @CaBocuk @vinogradoff Please review the pull request: https://github.com/codeborne/selenide/pull/674

**Comment by asolntsev** [comment]
@pavelpp I personally find that declaring page object field using `$$(css).get(n)` is quite strange. I don't like it. As a reader of this code, it's not obvious that "get" doesn't actually **get**. Lazy evaluation in Selenide was not intended for such things :)

**Comment by pavelpp** [comment]
@asolntsev me neither, so I refactored this finding a better way. ;)

**Comment by vinogradoff** [comment]
And .find() doesnt find either, so it is historically.

$$().last() - or first() is normal assignment imho but probably runs in the
same problem?
Viele Grüße

Alexei Vinogradov

**Comment by vinogradoff** [comment]
Could/should we write a integration test for lazy loading?

Viele Grüße

Alexei Vinogradov

**Comment by vinogradoff** [comment]
I’ve just pushed a Test in master for lazyEvaluation. In my opinion that
could should work, but fails for $$().last();

Feel free to add additional checks, I think LazyEvaluation is a killer
feature of Selenide, so it must work very stable.

Viele Grüße

Alexei Vinogradov

On 17. Januar 2018 at 09:35:11, Alexei Vinogradov (alexei@vinogradoff.de)
wrote:

 Could/should we write a integration test for lazy loading?

Viele Grüße

Alexei Vinogradov

**Comment by asolntsev** [comment]
@pavelpp @BorisOsipov @CaBocuk @vinogradoff We released Selenide 4.10.1 with a fix. It should entirely fix your problem.
