### ISSUE TITLE
Chrome does not start maximized

### ISSUE THREAD

**Issue by tbgdn** [codeborne/selenide#675]
## The problem
Chrome browser does not start maximized on Windows with latest Selenide and Selenium.

## Details
Even if Configuration.startMaximized is enabled by default, Chrome does not start maximized and the logs show the following exception:
`Cannot maximize ChromeDriver: java.awt.HeadlessException`
It seems that Chrome browser is adjusted by using the screen resolution provided by Java toolkit, which fails and no retry mechanism is in place. Apparently, the adjusting method used on other browsers also works on Chrome and maybe this can be used in the catch clause.

## Tell us about your environment
* **Selenide Version:** 4.9.1
* **Chrome Version:** 55 and 63
* **Browser Driver Version:** 2.35
* **Selenium Version:** 3.8.1
* **OS Version:** Windows 7 and 10

## Code To Reproduce Issue [ Good To Have ]
Any code will do.
```
Configuration.browser = "chrome";
Selenide.open("http://www.google.com");
```

**Comment by BorisOsipov** [comment]
Need enhance logic this https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/webdriver/WebDriverFactory.java#L71
catch exception, log them and don't change browser size.

**Comment by BorisOsipov** [comment]
@tbgdn Thanks for reporting this issue

**Comment by SergeyPirogov** [comment]
As I remember Andrey wanted to delete maximize. The motivation is that users should implicitly set browser window

**Comment by jpratt2** [comment]
I cannot duplicate this issue. In Windows 10 and Windows 7, the Chrome browser maximizes to fill the screen. It appears this issue can be marked complete.

**Comment by asolntsev** [comment]
@jpratt2 did you try it in headless mode?

**Comment by leysanka** [comment]
Crashes for me as well with the following error: "Chrome Automation extension has crashed. Click this balloon to reload the extension"

**Comment by asolntsev** [comment]
Yes, `--start-maximized` never worked for me. Instead, you can use Selenide option `Configuration.startMaximized = true;`

But I personally recommend not to start browser maximized, but instead set the browser size explicitly.
It helps you to avoid flaky tests.

**Comment by Neboyarsky** [comment]
> @leysanka Yes, `--start-maximized` never worked for me. Instead, you can use Selenide option `Configuration.startMaximized = true;`
I am sorry for necroposting, I just wanted to share that `Configuration.startMaximized = true` does not seem to work on Big Sur for me. Browser gets to maximum size vertically (but not horizontally) for a split second and then gets back to the default size.
> But I personally recommend not to start browser maximized, but instead set the browser size explicitly.
> It helps you to avoid flaky tests.
Copy that, will stick to explicitly setting the browser size.
