### ISSUE TITLE
can't import BrowserWebDriverContainer

### ISSUE THREAD

**Issue by darkklin** [codeborne/selenide#677]
Hi,
I trying to run my test with docker. 
So I looked at the example" GoogleTestWithDocker.java" 

and just copy the code  
https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver
but I can't import 
org.testcontainers.containers.BrowserWebDriverContainer;
I don't understand why, Please help me 
thanks.

![screenshot_21](https://user-images.githubusercontent.com/25209561/35069093-d1c9f98a-fbe1-11e7-9e00-d6f727902498.png)

**Comment by vinogradoff** [comment]
look at your dependencies in maven or gradle - you must have dependency to TestContainer. If you don't know which one - ask in TestContainer Support (or google it).

Anyway it is not selenide related problem
