### ISSUE TITLE
Webdrivermanager overrides logging 

### ISSUE THREAD

**Issue by tbgdn** [codeborne/selenide#678]
## The problem
I have a Spring Boot application that had stopped logging INFO statements after I switched to latest version of selenide. 

## Details
It seems like the webdrivermanager library (2.0.1 version) contains a logback.xml file that overrides logging settings for every class inside a **org** or **com** package. However, the latest release of this library, 2.1.0 version, does not have this issue anymore.

## Tell us about your environment
* **Selenide Version:** 4.1.0

## Code To Reproduce Issue [ Good To Have ]
Any Spring Boot application code will do.

**Comment by BorisOsipov** [comment]
@tbgdn thanks for reporting, we will fix it.

**Comment by asolntsev** [comment]
@tbgdn @BorisOsipov I will fix it today. Going to release Selenide 4.10.1 soon.

**Comment by asolntsev** [comment]
@tbgdn We released Selenide 4.10.1 with an upgrade to webdrivermanager 2.1.0. Thank you for reporting the problem.

**Comment by tbgdn** [comment]
Thank you @asolntsev
