### ISSUE TITLE
Selenide 4.10.01 + Spring Boot 1.5.8 - Cannot access org.openqa.selenium.interactions.internal.Locatable

### ISSUE THREAD

**Issue by daibertdiego** [codeborne/selenide#682]
Hi,

I have a Spring Boot App back-end with Maven and a Angular App in front-end. I did the steps from quick start, but when I try to write some codes in my test class, I had the message: 
cannot access org.openqa.selenium.interactions.internal.Locatable
  class file for org.openqa.selenium.interactions.internal.Locatable not found

My pom.xml is like that:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com.ibliss</groupId>
    <artifactId>gat-vulnerability</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
        
    </parent>

    <dependencies>
        
        <dependency>
            <groupId>br.com.ibliss</groupId>
            <artifactId>gat-basic</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
            <version>1.2.2.RELEASE</version>
            
        </dependency>

        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.4.0</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.4.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>4.10.01</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

    </build>

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>http://repo.spring.io/libs-snapshot-local</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>http://repo.spring.io/libs-milestone-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>http://repo.spring.io/libs-release-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>`

and when I run the mvn dependency:tree I got this result:

`[INFO] br.com.ibliss:gat-vulnerability:jar:1.0-SNAPSHOT
[INFO] +- br.com.ibliss:gat-basic:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:4.2.3.RELEASE:compile
[INFO] |  |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.23:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-annotations-api:jar:8.5.23:compile
[INFO] |  +- org.springframework:spring-test:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.mongodb.morphia:morphia:jar:1.3.2:compile
[INFO] |  |  +- org.mongodb:mongo-java-driver:jar:3.4.3:compile
[INFO] |  |  +- cglib:cglib-nodep:jar:2.2.2:compile
[INFO] |  |  \- com.thoughtworks.proxytoys:proxytoys:jar:1.0:compile
[INFO] |  +- org.javers:javers-core:jar:3.6.0:compile
[INFO] |  |  +- org.picocontainer:picocontainer:jar:2.15:compile
[INFO] |  |  \- io.github.lukehutch:fast-classpath-scanner:jar:2.4.7:compile
[INFO] |  +- org.javers:javers-persistence-mongo:jar:3.6.0:compile
[INFO] |  |  \- org.mongodb:mongodb-driver:jar:3.4.3:compile
[INFO] |  |     +- org.mongodb:mongodb-driver-core:jar:3.4.3:compile
[INFO] |  |     \- org.mongodb:bson:jar:3.4.3:compile
[INFO] |  +- com.github.jgonian:commons-ip-math:jar:1.31:compile
[INFO] |  +- dnsjava:dnsjava:jar:2.1.7:compile
[INFO] |  +- org.apache.commons:commons-email:jar:1.4:compile
[INFO] |  |  +- com.sun.mail:javax.mail:jar:1.5.6:compile
[INFO] |  |  \- javax.activation:activation:jar:1.1.1:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.3.5.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile
[INFO] |  +- net.lingala.zip4j:zip4j:jar:1.3.2:compile
[INFO] |  +- commons-io:commons-io:jar:2.5:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.8.10:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.10:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- commons-validator:commons-validator:jar:1.5.1:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.3:compile
[INFO] |  |  +- commons-digester:commons-digester:jar:2.1:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- com.opencsv:opencsv:jar:3.10:compile
[INFO] |  +- org.modelmapper:modelmapper:jar:0.7.5:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] |  +- org.apache.commons:commons-csv:jar:1.4:compile
[INFO] |  +- org.springframework:spring-context-support:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.quartz-scheduler:quartz:jar:2.2.3:compile
[INFO] |  |  \- c3p0:c3p0:jar:0.9.1.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.7:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.7:compile
[INFO] |  +- org.apache.directory.api:api-all:jar:1.0.0:compile
[INFO] |  |  +- org.apache.servicemix.bundles:org.apache.servicemix.bundles.xpp3:jar:1.1.4c_7:compile
[INFO] |  |  +- org.apache.servicemix.bundles:org.apache.servicemix.bundles.dom4j:jar:1.6.1_5:compile
[INFO] |  |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  +- commons-pool:commons-pool:jar:1.6:compile
[INFO] |  |  +- org.apache.mina:mina-core:jar:2.0.16:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  \- org.apache.servicemix.bundles:org.apache.servicemix.bundles.antlr:jar:2.7.7_5:compile
[INFO] |  +- org.apache.poi:poi:jar:3.17:compile
[INFO] |  |  \- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] |  \- org.apache.poi:poi-ooxml:jar:3.17:compile
[INFO] |     +- org.apache.poi:poi-ooxml-schemas:jar:3.17:compile
[INFO] |     |  \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |     |     \- stax:stax-api:jar:1.0.1:compile
[INFO] |     \- com.github.virtuald:curvesapi:jar:1.04:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.5.8.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.5.8.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.5.8.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.8.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.8.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.11:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.1.11:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.5.8.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.23:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.23:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.10:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.3.12.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:1.5.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:4.2.3.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:4.2.3.RELEASE:compile
[INFO] +- org.springframework.security.oauth:spring-security-oauth2:jar:2.0.14.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.3.12.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.3.12.RELEASE:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.5.8.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:1.5.8.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:1.5.8.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.2.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.2.1:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.1:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.3:test
[INFO] |  +- junit:junit:jar:4.12:test
[INFO] |  +- org.assertj:assertj-core:jar:2.6.0:test
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  \- org.skyscreamer:jsonassert:jar:1.4.0:test
[INFO] |     \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] +- org.springframework.cloud:spring-cloud-commons:jar:1.2.2.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-crypto:jar:4.2.3.RELEASE:compile
[INFO] +- io.springfox:springfox-swagger2:jar:2.4.0:compile
[INFO] |  +- io.swagger:swagger-annotations:jar:1.5.6:compile
[INFO] |  +- io.swagger:swagger-models:jar:1.5.6:compile
[INFO] |  +- io.springfox:springfox-spi:jar:2.4.0:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:2.4.0:compile
[INFO] |  +- io.springfox:springfox-schema:jar:2.4.0:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:2.4.0:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:2.4.0:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
[INFO] +- io.springfox:springfox-swagger-ui:jar:2.4.0:compile
[INFO] \- com.codeborne:selenide:jar:4.10.01:test
[INFO]    +- io.github.bonigarcia:webdrivermanager:jar:2.1.0:test
[INFO]    |  +- org.rauschig:jarchivelib:jar:0.7.1:test
[INFO]    |  |  \- org.apache.commons:commons-compress:jar:1.9:test
[INFO]    |  \- org.jsoup:jsoup:jar:1.10.2:test
[INFO]    +- org.apache.httpcomponents:httpcore:jar:4.4.8:compile
[INFO]    +- org.seleniumhq.selenium:selenium-java:jar:2.53.1:test
[INFO]    |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.53.1:test
[INFO]    |  |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:2.53.1:test
[INFO]    |  |     \- org.seleniumhq.selenium:selenium-api:jar:2.53.1:test
[INFO]    |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:2.53.1:test
[INFO]    |  |  \- org.apache.commons:commons-exec:jar:1.3:test
[INFO]    |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.53.1:test
[INFO]    |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:2.53.1:test
[INFO]    |  |  +- net.java.dev.jna:jna:jar:4.2.2:test
[INFO]    |  |  \- net.java.dev.jna:jna-platform:jar:4.2.2:test
[INFO]    |  +- org.seleniumhq.selenium:selenium-support:jar:2.53.1:test
[INFO]    |  \- org.seleniumhq.selenium:selenium-leg-rc:jar:2.53.1:test
[INFO]    +- com.google.code.gson:gson:jar:2.8.2:compile
[INFO]    +- net.lightbody.bmp:browsermob-core:jar:2.1.5:test
[INFO]    |  +- net.lightbody.bmp:littleproxy:jar:1.1.0-beta-bmp-17:test
[INFO]    |  +- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
[INFO]    |  +- com.jcraft:jzlib:jar:1.1.3:test
[INFO]    |  +- io.netty:netty-all:jar:4.0.51.Final:test
[INFO]    |  +- org.bouncycastle:bcprov-jdk15on:jar:1.58:test
[INFO]    |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.58:test
[INFO]    |  \- net.lightbody.bmp:mitm:jar:2.1.5:test
[INFO]    \- com.codeborne:phantomjsdriver:jar:1.4.4:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.783 s
[INFO] Finished at: 2018-01-22T22:27:26-02:00
[INFO] Final Memory: 34M/401M
[INFO] ------------------------------------------------------------------------
`

Could you help me?

Cheers.

**Comment by BorisOsipov** [comment]
The same problem as here https://github.com/codeborne/selenide/issues/561
Spring boot parent project takes old (2.53) selenium version to the project in dependency management section.

**Comment by daibertdiego** [comment]
Thank you, than I need to add selenium-api, selenium-remote-driver and selenium-sport at version 3.4.0 in my pom.xml? Or I need to exclude the selenium 2.53 from the Spring Boot parent project?

**Comment by BorisOsipov** [comment]
I don't know how you can exclude selenium 2.53 from the Spring Boot parent project :)

You need somehow solve this dependencies issue. Actual Selenium version is 3.8.1

**Comment by daibertdiego** [comment]
Thanks man. I added the Selenium libs and worked.

`<dependency>
           <groupId>com.codeborne</groupId>
           <artifactId>selenide</artifactId>
           <version>4.10.01</version>
           <scope>test</scope>
       </dependency>

       <dependency>
           <groupId>org.seleniumhq.selenium</groupId>
           <artifactId>selenium-api</artifactId>
           <version>3.8.1</version>
       </dependency>

       <dependency>
           <groupId>org.seleniumhq.selenium</groupId>
           <artifactId>selenium-remote-driver</artifactId>
           <version>3.8.1</version>
       </dependency>

       <dependency>
           <groupId>org.seleniumhq.selenium</groupId>
           <artifactId>selenium-support</artifactId>
           <version>3.8.1</version>
       </dependency>`
