### ISSUE TITLE
can't find the TextReport after running tests

### ISSUE THREAD

**Issue by darkklin** [codeborne/selenide#685]
Hi,
I tried to implement text report on my project without luck
-->
## The problem
can't find text report at build\reports\tests folder after running my test 

## Details
I copped the example from here
https://github.com/codeborne/selenide/blob/master/src/test/java/integration/testng/GoogleTestNGTest.j
    and just ran it 

expected result: find text report in folder build\reports\tests or somewhere else ...

bug???: can't find the report in any folder 
![screenshot_36](https://user-images.githubusercontent.com/25209561/35487301-b2216e2a-0482-11e8-8e9e-12ce11233231.png)

## Tell us about your environment
* **Selenide Version:** 4.10

## Code To Reproduce Issue [ Good To Have ]
https://github.com/codeborne/selenide/blob/master/src/test/java/integration/testng/GoogleTestNGTest.java

**Comment by ostap-oleksyn** [comment]
You should also add @Report annotation to your class. Report will be printed to your console, it's not saved  to a file.

**Comment by darkklin** [comment]
you mean above the class like that?
![screenshot_652](https://user-images.githubusercontent.com/25209561/35506241-52a71408-04f1-11e8-86bf-77d2db4c1719.png)

**Comment by ostap-oleksyn** [comment]
It's a class annotation, in your case it will be like this: 
@Report
@Listeners(TextReport.class)
public class GoogleTestNGTest{

**Comment by darkklin** [comment]
A-ok Thank you!!
