### ISSUE TITLE
Selenide cannot download files with cyrillic (and probably any UTF-8) name

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#688]
## The problem
Given a file with cyrillic letters, Selenide downloads it, but with a wrong name.

## Details
1. Call method `File file = $("a").download();`
2. The downloaded file should contain cyrilic letters (like `файл-с-русским-названием.txt`)
3. But Selenide creates a file with a wrong name in which all cyrillic letters are replaced with spaces (like `    - -       -         .txt`)

**Comment by rosolko** [comment]
Closed via https://github.com/codeborne/selenide/pull/689
