### ISSUE TITLE
For 'selenium-api', version: '3.9.0' getting - net.serenitybdd.core.exceptions.SerenityManagedException: org/openqa/selenium/internal/Killable`

### ISSUE THREAD

**Issue by Ashvinijai** [codeborne/selenide#691]
After adding the latest versions of selenium and serenity not able to launch chrome I am getting an error : net.serenitybdd.core.exceptions.SerenityManagedException: org/openqa/selenium/internal/Killable` Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
Could anyone help me with this issue

compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version:'3.9.0'     
compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version:'3.9.0'
compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.21'
compile group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.9.0'
 compile group: 'org.seleniumhq.selenium', name: 'lift', version: '3.9.0'
compile group: 'org.seleniumhq.selenium', name: 'selenium-remote-driver', version: '3.9.0'
 compile group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.9.0'
compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.21'

**Comment by asolntsev** [comment]
@Ashvinijai And the most important question: what is the Selenide version?

**Comment by Ashvinijai** [comment]
I am not using selenide.
I am using Serenity Frame work with gradle.Do i need to use selenide?

**Comment by asolntsev** [comment]
@Ashvinijai Then why you created a **Selenide** issue?

P.S. Yes, you should use Selenide, it makes you life much easier. :)

**Comment by vinogradoff** [comment]
not relevant to Selenide

**Comment by tlytvyn** [comment]
поржав))

**Comment by Ashvinijai** [comment]
But we are not using selenide..is there any alternative?If i add latest api file i am getting this issue

**Comment by vinogradoff** [comment]
@Ashvinijai maybe there is, but you are in the wrong place here.

It is like asking at android Forums why your iphone doesn't work. We are not serentiy developers and not selenium developers, we don't solve their problems.

**Comment by Ashvinijai** [comment]
This is for a webapplication and not for iphone.I am just asking what is the solution for this issue.Killable class is not present in latest selenium api jar file.Even if i added latest selenium html unit driver it is not working.Showing the same error.Is there any other jar file i need to use?

**Comment by tlytvyn** [comment]
@Ashvinijai You are posting an issue in Selenide repo, not Serenity = these are two totally different projects with different goals) Create your issue here https://github.com/serenity-bdd/serenity-core

**Comment by Ashvinijai** [comment]
okay Thanks :)
