### ISSUE TITLE
with annotation @Listeners({SoftAsserts.class}) - IDE don't show a line of test fail

### ISSUE THREAD

**Issue by AndreyBzhestovskyy** [codeborne/selenide#703]
## The problem
Adding annotation @Listeners({SoftAsserts.class}) makes IDE don't show a line of test fail

## Details
Sample: add listener to base test class
```
@Listeners({SoftAsserts.class})
public abstract class BaseTestGlobal {
Configuration.assertionMode = SOFT;
}
```

## Tell us about your environment
* **Selenide Version: 4.10
* **Chrome\Firefox\IE Version: Chrome 64.0.3282.186
* **Browser Driver Version: Chromedriver 2.36
* **Selenium Version: - 
* **OS Version: Windows 10

## Code To Reproduce Issue [ Good To Have ]
link to report: https://files.gitter.im/codeborne/selenide-ru/5eM8/image.png

**Comment by BorisOsipov** [comment]
@AndreyBzhestovskyy it is not a bug. It is designed behaviour for soft asserts.

**Comment by asolntsev** [comment]
@AndreyBzhestovskyy Actually, the stacktrace was later added to soft assertions. See https://selenide.org/2021/09/28/selenide-5.25.0/  -> "Now we show stacktrace below every error in soft asserts".
