### ISSUE TITLE
Chrome.exe doesn't properly close after Selenide tests complete after 4.10.01 update

### ISSUE THREAD

**Issue by jjloneman** [codeborne/selenide#704]
## The problem
Using an older version of Selenide, my tests worked fine, but Chrome would not maximize after updating Chrome to the latest version. Another forum suggested updating Selenium, so I updated both Selenium and Selenide to the latest version, which re-enabled maximizing the browser (yay!).

However, after running a couple of Selenide tests, I noticed my computer started to severely lag, and Task Manager showed multiple chrome instances running. Once I manually killed all chrome processes, my computer was fine again, but when monitoring task manager when running a Selenide test (normally, not in debug mode), a chrome instance would initialize but never close.

Additionally, I never actually get a "Closing webdriver" statement logged to the console.

**Note: Manually calling `close()` or `quit()` doesn't seem to kill the process either.**

## Details
When inspecting the Chrome.exe process command line argument in Task Manager, it gives me back the following:

```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --enable-automation --enable-logging --log-level=0 --no-sandbox --test-type=webdriver --field-trial-handle=1400,11998484406227630845,5053314566440088946,131072 --service-pipe-token=70069B3597782518049F573644A42A16 --lang=en-US --user-data-dir="C:\PROGRA~2\Temp\scoped_dir19604_27418" --disable-client-side-phishing-detection --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=70069B3597782518049F573644A42A16 --renderer-client-id=5 --mojo-platform-channel-handle=3036 /prefetch:1
```

Here is what gets logged to the console after completing a test:

```
Starting ChromeDriver 2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91) on port 5580
Only local connections are allowed.
Mar 21, 2018 2:53:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Mar 21, 2018 2:53:07 PM com.codeborne.selenide.webdriver.WebDriverFactory logBrowserVersion
INFO: BrowserName=chrome Version=65.0.3325.181 Platform=XP
Mar 21, 2018 2:53:07 PM com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
INFO: Selenide v. 4.10.01
Mar 21, 2018 2:53:07 PM com.codeborne.selenide.webdriver.WebDriverFactory logSeleniumInfo
INFO: Selenium WebDriver v. 3.11.0 build time: 2018-03-11T20:26:55.152Z
Mar 21, 2018 2:53:07 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer createDriver
INFO: Create webdriver in current thread 1: ChromeDriver -> ChromeDriver: chrome on XP (a420c687cc03db2a77fe5e2a5679d4ac)

Process finished with exit code 0
```

## Tell us about your environment
| Description | Version |
| --- | --- |
| Selenide Version | 4.10.01 |
| Chrome Version | 65.0.3325.181 |
| Browser (Chrome) Driver Version | 2.36 |
| Selenium Version | 3.11.0 |
| OS Version | Windows 7 |

## Code To Reproduce Issue [ Good To Have ]
Using the latest Selenide, Selenium, ChromeDriver, and Chrome versions, run any test and monitor Task Manager. When the test finishes, Task Manager will still report the process as running. Executing another test initializes a new instance, leaving the old one still active, eventually causing a memory leak.

**Comment by Denysss** [comment]
Update chromedriver to 2.37

**Comment by BorisOsipov** [comment]
@jjloneman Thank you for detailed report.

It looks like not Selenide issue and should be easyly reproduce by plain Selenium.
Please submit it to chromedriver project 
https://bugs.chromium.org/p/chromedriver/issues/list
