### ISSUE TITLE
Investigate code coverage flashing

### ISSUE THREAD

**Issue by rosolko** [codeborne/selenide#706]
From https://github.com/codeborne/selenide/pull/659 PR

Imvestigate and try to fix issue:
>But some times it reports unexpected coverage changes here and we can't fix it :)

https://github.com/codeborne/selenide/blob/0f2e4502f85b3b46184373536309b2da0db956cb/src/main/java/com/codeborne/selenide/impl/WebDriverThreadLocalContainer.java#L41

**Comment by BorisOsipov** [comment]
btw I can predict your proposal to replace foreach with stream isn't fix coverage flashing
