### ISSUE TITLE
Add method for repeating action until a condition is met

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#712]
## The problem
People often need to re-try `click` if the first click didn't happen.

For example:
1. Click the button
2. A banner should appear
3. If banner hasn't appeared, we conclude that step 1 was not successful (for unknown reason), and we want to re-try step 1.

## Details
We probably should add a "re-trying" method to Selenide:

```java
Selenide.doWhile(
  () -> !$("#banner").isDisplayed(),
  () -> $("#button").click();
);
```

**Comment by pavelpp** [comment]
I have a similar solution as a separate utility class, but it has nothing to do with Selenium, as you can pass any boolean provider / runnable, so not sure if it's worth having it as part of Selenide?

**Comment by pavelpp** [comment]
Btw, re-naming doWhile to doUntil would make more sense

**Comment by asolntsev** [comment]
Ok, it seems that nobody likes the idea. Closing the issue.

**Comment by nazarovvi** [comment]
Such a pitty. Would be a great addition to selinide's arsenal
