### ISSUE TITLE
JUnit5 and selenide SoftAsserts

### ISSUE THREAD

**Issue by MrKorIA** [codeborne/selenide#738]
Hello everyone!

For work selenide SoftAssert need annotation @Rule, but in JUnit5 this is annotation abrogated.  How can this be lived with?
http://selenide.org/2015/05/05/selenide-2.16-and-2.17/ 

* **Selenide Version: 4.11.1
* **JUnit5: 2.6.0

**Comment by rosolko** [comment]
@MrKorIA I wrote simple JUnit5 extension for selenide. 
It's duplicate rule from JUnit4.
You can get it by [link](https://github.com/rosolko/selenide-junit5).
Try his out and give feedback please.

**Comment by rosolko** [comment]
@MrKorIA Ping! Can you please provide some feedback?

**Comment by rosolko** [comment]
@MrKorIA ?

**Comment by rosolko** [comment]
Close due to inactivity.
