### ISSUE TITLE
.text() should default to .getValue() for input fields

### ISSUE THREAD

**Issue by jpratt2** [codeborne/selenide#739]
## The problem
As an enhancement, I suggest that the .text() method automatically call the .getValue() method for input fields. It seems useless to report an empty value when an input field is populated. I can't imagine any input field actually having an innerText value (or any other text value), am I right?

## Details
The new code may look something like this:

```
if(element.getTagName().equals("input")){
            return element.getValue();
        } else{
            return element.getText();
        }
    }
```

**Comment by rmarinsky** [comment]
It depends on developer's implementation how they handle the users' input.
Sometimes it isn't implemented by web (w3c) standards

**Comment by rosolko** [comment]
@jpratt2 Agree with @rmarinsky . It's not an issue. Project specific case. For this just override selenide command for your needs or call getValue method that get exact value, not a text.
