### ISSUE TITLE
refresh() this command is not working properly

### ISSUE THREAD

**Issue by sukhjinder-sdei** [codeborne/selenide#740]
## Environment
* **Selenide Version: 4.11.4**
* **Chrome Version:66.0.3359.139**
* **Browser Driver Version: 2.38**
* **OS Version: Win10**

## Code To Reproduce Issue [ Good To Have ]
refresh()

**Comment by sukhjinder-sdei** [comment]
@rosolko Thanks for ur quick response.

**Comment by BorisOsipov** [comment]
@rosolko I see that this code is five year old. Maybe refresh did't work well 5 years ago...
Don't find any reason to keep it as is.
