### ISSUE TITLE
Need configuration option to set Proxy

### ISSUE THREAD

**Issue by gerasimenko-ivan** [codeborne/selenide#748]
Need configuration option to set Proxy.

Selenide checks/downloads new version of chromedriver.exe on the external web-page, which could not be accessed on machine with connection to internet via proxy.

See also stackoverflow question https://sqa.stackexchange.com/questions/33903/set-up-proxy-for-selenide

**Comment by BorisOsipov** [comment]
Can you try set env variables with proxy settings like
System.setProperty("wdm.proxy", url);
System.setProperty("wdm.proxyUser", url);
System.setProperty("wdm.proxyPass", url);

will it work?

**Comment by BorisOsipov** [comment]
For details see https://github.com/bonigarcia/webdrivermanager#configuration

**Comment by gerasimenko-ivan** [comment]
This works fine:
System.setProperty("wdm.proxy", url);
Thanks!

**Comment by dineshkumarravi** [comment]
Hello everyone .

wdm.proxy property shown as greyed out in properties file and unable to read the value from webdrivermanager.properties file , issue only in Intelij IDE, working fine in eclipse IDE. please response if anybody knows the answer.

Thanks.
