### ISSUE TITLE
Selenide doesn't support separate timeout for Proxy file download.

### ISSUE THREAD

**Issue by YuriIvanov** [codeborne/selenide#758]
## The problem
Selenide doesn't support separate timeout for Proxy file download.

## Details
Imagine you have tests that have to download big files or wait for big reports to be generated. This means you need to wait more than default 4s timeout, maybe even up to 60 secs or more. The only way you can do it is to set **Configuration.timeout** value but this parameter affects not only downloading time but all other Selenide timeouts. So if your test failed before you have reached downloading step you have to wait up to those 60 s. for already failed test to end. Multiply this time on number of your tests...

## Tell us about your environment
* **Selenide Version:** 4.11.4 or higher

## Possible solutions
We have three straight options to solve this problem.
The bad one is to add new special value to **Configuration**, extend **Waiter** class to override wait method and use new class with new value during proxy file download. But this way we will break encapsulation and force users to tie to another global non thread safe variable.
Second is to add download timeout as parameter to download command of **SelenideElement** class. This way any user will be able to decouple from **Configuration.timeout** value in download-related tests and compiler will tell them where to fix **download** method calls.
And number three, the best. Just overload **download** method in **SelenideElement** class with timeout parameter and add corresponding changes to **DownloadFile**, **DownloadFileWithHttpRequest** and **DownloadFileWithProxyServer** classes.

**Comment by asolntsev** [comment]
@YuriIvanov I found that this issue was only valid when download with "get" request. When downloading with "proxy", the timeout parameter is actually ignored. Look at `DownloadFileWithProxyServer`:

```java
private File clickAndInterceptFileByProxyServer(...) {
  ...
  clickable.click();  // this line actually waits until the file is completely downloaded

  waiter.wait(filter, new HasDownloads(), timeout, Configuration.pollingInterval); // this "waiting" doesn't make any sense :) 
  ...
}
```

Or am I wrong?

**Comment by YuriIvanov** [comment]
@asolntsev Eh, I did not manage to add unit tests for that.
clickable.click() uses Configuration.timeout as timeout, but after click performed we need to wait up to out **timeout** for available files. It is fully correct behavior.
For example, we have Configuration.timeout set to 10 seconds. First Selenide will try to click on some download button with this 10 seconds timeout that is absolutely Selenide-like behavior expected by users. And only after that we will wait up to our custom timeout for available files.

**Comment by asolntsev** [comment]
@YuriIvanov Actually `clickable.click()` doesn't use `Configuration.timeout`. It waits as long as file is being downloaded.

**Comment by YuriIvanov** [comment]
@asolntsev If it would be this way it would have waited at least up to server timeout and wait.waiter would be useless here. Moreover, how click command without any parameters can know when there is any file downloaded? Only HasDownloads predicate can know this.

And why click command should even wait until some downloads to complete? It's still CLICK command :)

**Comment by asolntsev** [comment]
@YuriIvanov Look at this test: https://github.com/codeborne/selenide/commit/2de95f83249e11cddb19786725e2be1d31f75494

it reproduces the problem.
