### ISSUE TITLE
Check if radio button is selected

### ISSUE THREAD

**Issue by chudyed** [codeborne/selenide#759]
I have a radio button and want to check if it's selected or not using shouldBe() method.
Trying something like that:

	$("//input[@id='single']").shouldBe(visible, selected, exist);

and it seems working for **visible** and **exist** but doesn't for **selected**:

	$("//input[@id='single']").shouldBe(selected);
"selected cannot be resolved as to a variable"

I think that according to the the documentation it should work like that?

## Tell us about your environment
Selenide version = 4.12.2
Windows 10

**Comment by BorisOsipov** [comment]
@chudyed 

I guess it is a issue with your code. Try to use `Condition.selected`

[Join our Gitter](https://gitter.im/codeborne/selenide) if you have more questions. Thanks!
