### ISSUE TITLE
ElementsCollections shouldHave()

### ISSUE THREAD

**Issue by chudyed** [codeborne/selenide#760]
Trying to find out if my list contains some texts. Accoring to the documentation :

ElementsCollection |
 shouldHave(CollectionCondition... conditions)$$(".error").shouldHave(size(3)) `$$(".error").shouldHave(texts("Error1", "Error2"))`
 
In my particular case:
`$$(".mstatus").shouldHave(texts("Single", "Married"));`

it shows that 
"the method texts(String) is undefinded for the type <myClassName>"

## Tell us about your environment
* **Selenide Version: 4.12.2
* **OS Version: WIndows 10

.

**Comment by BorisOsipov** [comment]
@chudyed can you share full code with imports?

**Comment by chudyed** [comment]
That is my full code:
```
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.*;
import java.io.IOException;
import org.openqa.selenium.By;
import org.testng.annotations.Test;
import com.codeborne.selenide.Condition;
import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;


public class Tests extends BaseScenario{
	
	@Test
	public void test1() throws IOException, InterruptedException {


			open("/");
			$$(".mstatus").shouldHave(texts("Single", "Married"));
	}
```

**Comment by chudyed** [comment]
In BaseScenario I have only:
`Configuration.baseUrl = "http://demoqa.com/registration/";`

**Comment by rosolko** [comment]
I'm trying to use you code but unfortunately I can't find any item on page using provided locator. 
![untitled](https://user-images.githubusercontent.com/11458319/42178965-f19cff56-7e3a-11e8-88ff-c118a7d796d8.png)

**Comment by rosolko** [comment]
@chudyed 
I modified your code a little with correct locator and get text mismatch error:
TextsMismatch 
Actual: [Single, Married, Divorced]
Expected: [Single, Married]
Collection: .radio_wrap > label.first(3)

**Comment by chudyed** [comment]
Ok, maybe it should be 
`$$(".radio_wrap").shouldHave(texts("Single", "Married"));`
but it's not a case here because I cannot even start my test due to error I'm  getting caused by 'text()' method.
It shows that
"the method texts(String) is undefinded for the type "

**Comment by chudyed** [comment]
![2018-07-02_21h33_18](https://user-images.githubusercontent.com/23298175/42182747-8f88f658-7e3f-11e8-9f6b-f4afed414e28.png)

**Comment by asolntsev** [comment]
@chudyed You miss one import. Just add this line to your test:

```java
import static com.codeborne.selenide.CollectionCondition.texts;
```

P.S. That's why IDEA is better than Eclipse.

**Comment by rosolko** [comment]
@chudyed 
Looks like you trying to use `texts` method from another non-selenide package.
Try to add direct static import for condition:
`import static com.codeborne.selenide.CollectionCondition.texts;`
