### ISSUE TITLE
Feature request - add children() and/or siblings() methods for better DOM navigation

### ISSUE THREAD

**Issue by TomaszSzyborski** [codeborne/selenide#765]
## The problem
While writing tests requiring navigation through table elements I have to do what follows:
`List<SelenideElement> headers =invoices.$("tr").$$("th");` or something in similar fashion.

## Proposal
We have parent() method which gives us parent element, it would be very useful to have one going downwards(and/or sideways) to DOM . Then, insted of `List<SelenideElement> headers =invoices.$("tr").$$("th");`  one could write `List<SelenideElement> headers =invoices.children().first().children();` without specifying actual elements selectors.

Then:
siblings() would select all parallel elements except the one from which method is invoked.
etc.

**Comment by asolntsev** [comment]
@TomaszSzyborski I am not sure it's a good idea. This test can be fragile because developers can add some invisible elements to the `<table>` (e.g. `<tbody`) which causes test failure. That's why I think explicitly using `<tr>` or `<td>` is a good idea.

**Comment by TomaszSzyborski** [comment]
@asolntsev I can see that. I was using other framework as well - there is option for going through DOM like  parent, children, siblings etc. - it is especially useful when there is no `<tr>` or `<td>` and everything is built with `<div>` and `<span>` without specific selectors for rows or fields, as follows:
Assume this is table:
```
<div class="table">                     // this is table
    <div>                 // this is row
        <div></div>  // this is field
        <div></div>
        <div></div>
    </div>
    <div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
```
So you can get table by `$('.table')` but `$('.table').$$("div")` would give me all divs and proposed $('.table').children() would give me ElementsCollection of two rows. 

To make things more explicit (although not applicable to example above) would be:
$('.table').children().filter("something") - but then again it's achievable by $('.table').$$("something") if there is specific attribute for rows

But then again explicit is better than implicit - and it's better to have one way to do things (like in Zen of Python :) )

**Comment by rosolko** [comment]
@TomaszSzyborski You can use `$$(.table > div)` and get exact two rows and perform filtering for them.

**Comment by TomaszSzyborski** [comment]
@rosolko fair enough :)
Closing this one, then.
