### ISSUE TITLE
Wait for page loaded waitUntil doesn't work

### ISSUE THREAD

**Issue by brobee** [codeborne/selenide#777]
Hi,

I have a loading icon and I'd like to wait till that loading icon disappeared using Selenide.
```
private static SelenideElement pageLoader = $(By.id("loader"));

public static void waitUntilLoaderDisappears() {
        pageLoader.waitUntil(Condition.hidden, timeOut);
    }
```

It doesn't work, because I got the following error:

```
Element should be hidden {By.className: loader}
Element: <div class="loader"></div>
```

This topic is confusing me. How can I check the actual page is fully loaded (apart from the element check on the page) and how can I wait till something is disappeared?

Do I miss something? Thanks!

**Comment by asolntsev** [comment]
@brobee You are doing it right. This is the right way to check that something has disappeared: 
```
$("#loader").should(disappear);
// or $("#loader").waitUntil(hidden, timeout); // if you really want a custom timeout
```

In your case, this element hasn't disappeared. Probably you used too short timeout? Please copy the full error message.

**Comment by brobee** [comment]
Thanks for that! my problem was the short timeout, but your confirmation was useful!

Still wait question, so it is related. I have a login page, when I fill up the form and click on login, a brand new window appear for the users. I cannot change this behavior, so I need to handle somehow. Any idea, how can selenide wait for a window, not an element? 

Problem in this case: when the window appears, I need to use switchto.window method to use that. I have a frame, so grab an element, need to switch to that frame as well. 

Complex, but need some solution. Thanks!!!

**Comment by tsukakei** [comment]
> Still wait question, so it is related. I have a login page, when I fill up the form and click on login, a brand new window appear for the users. I cannot change this behavior, so I need to handle somehow. Any idea, how can selenide wait for a window, not an element?

I have the same situation!
My solution is to use `Selenide.sleep()`.
I know it's not good one, but a realistic one. @brobee

**Comment by brobee** [comment]
I think, sleeps is not the best moreover a good solution. Can be a workaround, but not a permanent thing. Anyway, thanks!

**Comment by asolntsev** [comment]
@brobee In theory, these 2 lines should work for you:

```java
switchTo().window(...);  // waits until window is available
switchTo().frame(...);  waits until frame is available
```

Both methods can wait if needed.
