### ISSUE TITLE
Enable BasicAuth through Selenide proxy server

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#784]
## The problem
Currently it's only possible to bypass BasicAuth by adding username+password in URL. And this is deprecated now (at least in Chrome). We could add BasicAuth header using Selenide's built-in proxy server.

**Comment by rosolko** [comment]
Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization
