### ISSUE TITLE
Can we log HTTP responses (200/ 400/ 500) if tests are passed/failed

### ISSUE THREAD

**Issue by AshokKumarNarava** [codeborne/selenide#786]
## The problem
Can we log HTTP responses (200/ 400/ 500) if tests are passed/failed

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version: 4.2.1**
* **Chrome\Firefox\IE Version:Version 68.0.3440.106**
* **Selenium Version:3.11**

I am working on a test environment which is very unstable. When tests are failed due to the page not loading it's because of  "500 Internal Server Error" is there is any way to log HTTP errors?

This will help me to debug issues in a better way.

**Comment by asolntsev** [comment]
@AshokKumarNarava Yes, you can do it if you are using `Configuration.fileDownload = PROXY`.
In this case, Selenide starts its own built-in proxy server, and you can add `ResponseFilter` to it. 

This way you can add a filter which logs any requests/responses.
See a working example in [Selenide tests](https://github.com/codeborne/selenide/blob/master/src/test/java/integration/proxy/ProxyServerUsageTest.java)
