### ISSUE TITLE
PhantomJS capabilities are not set through Selenide

### ISSUE THREAD

**Issue by espaciomore** [codeborne/selenide#802]
## Selenide fails to apply DesiredCapabilities on PhantomJS 
When I set the capabilities through the `Configuration.desiredCapabilities` object, the PhantomJS driver does not get the capabilities as desired. Nonetheless, when I explicitly instantiate the `PhantomJSDriver` with the desired capability then it works.

## Tell us about your environment
* **Selenide Version:**4.11.4
* **Selenium Version:**3.12
* **OS Version:**Windows Server 2012 R2

## Code To Reproduce Issue
```
Configuration.browser = "phantomjs";
Configuration.headless = true;
DesiredCapabilities v_caps = new DesiredCapabilities();
v_caps.setCapability("phantomjs.cli.args", new String[]{ "--ignore-ssl-errors=yes", "--port=1010"});
Configuration.browserCapabilities = v_caps;
getWebDriver();
```

```
PhantomJSDriver v_driver = new PhantomJSDriver(Configuration.browserCapabilities);
```

**Comment by espaciomore** [comment]
I needed to use a string array; `ArrayList<String> v_args = new ArrayList<String>();` to add the desired capability `v_caps.setCapability("phantomjs.cli.args", v_args);`

**Comment by espaciomore** [comment]
This was a much better solution:

```
DesiredCapabilities dcap = new DesiredCapabilities();
File logfile = new File("ABSOLUTE_PATH_TO_YOUR_LOG_FILE");
String[] phantomArgs = [ "--webdriver-loglevel=DEBUG" ]
PhantomJSDriverService pjsds = new PhantomJSDriverService.Builder()
              .usingPhantomJSExecutable(f)
              .usingAnyFreePort()
              .withProxy(proxy)
              .usingCommandLineArguments(phantomArgs)
              .withLogFile(logfile)
              .build();
PhantomJSDriver pdriver = new PhantomJSDriver(pjsds, dcap);
```

Source: https://stackoverflow.com/questions/30805635/change-path-for-the-logfile-of-phantomjs-in-java

**Comment by espaciomore** [comment]
@asolntsev could you tell me the default capabilities for PhantomJS when using Selenide?

**Comment by rosolko** [comment]
@espaciomore We don't pass any capabilities for default phantomjs drive.

**Comment by espaciomore** [comment]
@resolko I'm thinking browser viewport, platform, etc...

**Comment by rosolko** [comment]
@espaciomore From browser stuff we just add browser version if it's not null.
**Note:** Miss one point we also add 2 arguments to `phantomjs.cli.args`:
1. --web-security=no
2. --ignore-ssl-errors=yes

**Comment by espaciomore** [comment]
My issue was the viewport so I changed the browser size:

```
v_driver.manage().window().setSize(new Dimension(1920, 1080));
v_driver.manage().window().setPosition(new Point(0, 0));
```

**Comment by rosolko** [comment]
@espaciomore Selenide has configuration for this points:
1. `Configuration.browserSize` - for browser size, be default it has your browser default window size
1. `Configuration.browserPosition` - for browser  position, be default it has your browser default window position
