### ISSUE TITLE
Method $ should NOT automatically open a browser

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#809]
When using Selenide, a normal flow is to first open a browser, and then acting with elements. Like this:

```
open(url);
$(...).do(...);
```

## The problem
If one forgers to call `open` and calls `$`, Selenide still opens a browser. It's kind of unexpected behaviour. It can cause mysterious bugs. 

## Solution
I suggest to change method `$`, so that it throws an exception if a browser is not open yet.

**Comment by asolntsev** [comment]
Implemented in branch `selenide-driver`

**Comment by BorisOsipov** [comment]
@asolntsev just to be sure. For $$().someaction() the same?

**Comment by asolntsev** [comment]
@BorisOsipov Yes, sure. Both `$` and `$$` should throw an exception if browser is not opened.

**Comment by rosolko** [comment]
It's a good point! Awesome 🎉
